mem0ai/mem0

embedchain/embedchain.py
embedchain/vectordb/base_vector_db.py
embedchain/vectordb/chroma_db.py

Introduced a new base class, BaseVectorDB, with abstract methods _get_or_create_db and _get_or_create_collection. This allows for an arbitrary VectorDB implementation to be plugged into the EmbedChain.
- Refactored EmbedChain to take an instance of BaseVectorDB during initialization, promoting greater flexibility and adherence to the Dependency Inversion Principle.
- Implemented ChromaDB as subclasses of BaseVectorDB. These can now be used interchangeably when creating an EmbedChain instance.
This commit makes the EmbedChain more flexible and extensible. Different types of VectorDB can now be used interchangeably with EmbedChain without the need for modifying EmbedChain's code.
To Use:
> chroma_db = ChromaDB('path/to/your/db')
naval_chat_bot = App(chroma_db)

[feat] Refactor VectorDB class hierarchy for flexibility

---

embedchain/embedchain.py

- This commit adds support to skip generating embedding for chunks which are already present in vector db.
- It addresses https://github.com/embedchain/embedchain/issues/23

Skip creating embedding if it already exists

---

embedchain/embedchain.py

I refactored the methods. It still works the exact same, here's the idea, how and why.
The query method is the end user exposed method. It should be as abstract as possible and only combine the use of other methods. No slicing or formatting should be done here.
I created a `retrieve_from_database` for the retrieval process. It includes all database related operations and the filtering.
I moved the prompt generation out of the `generate_answer_from_llm` method, into it's own method.
I cleaned up  `generate_answer_from_llm` and `query`.
**My original intention was to create a dry run method**, where you can test the prompts and your database, without actually sending them and without consuming tokens. After this PR it will be easy, simply by copying the `query` method and leaving out …

refactor: methods used to query

---

.gitignore

all the files that are generated for the db when you run the code currently are not ignored. I guess it depends on where you run it, but I think they should be ignored for the dev experience.

fix: add database to gitignore

---

README.md

There seems to be an error in the Readme file regarding the app instance name. It appears to be assigned as 'naval_ravikant_chat_bot_app' but the subsequent lines of code use 'naval_chat_bot'.

Typo with App instance name

---

embedchain/embedchain.py

This PR will solve the following problem. When no similar document is found in the vector database or the vector database is empty,`result_formatted[0][0].page_content` will be triggered and `IndexError` will be triggered.
eg:
```python
result = self.collection.query(
query_texts=[input_query,],
n_results=1,
)
```

Fix: Solve IndexError when no relevant documents are found in the vector db.

---

embedchain/vectordb/chroma_db.py

In some cases we need to be able to set the OpenAI organization_id along with the OpenAI api_key. This is due to the way OpenAI has their access control organized with respect to users belonging to different Organizations.

Allow setting OpenAI organization along with api_key

---

README.md

The default behavior persists the local vector DB that is reusable. It would be a good thing to point this out to users.

Added to README example for reusing a vector DB

---

embedchain/embedchain.py

`dry_run` func has `if config is None:` check but not able to pass QueryConfig
related to #167

fix:pass QueryConfig to dry_run

---

embedchain/embedchain.py

Fixes #108.
Tested by using the built of the clone instead of pip in prod where I got the error.

fix: ValueError: Expected metadatas to be a list, got ({'url': 'local'},)

---

embedchain/chunkers/base_chunker.py
embedchain/embedchain.py

This PR is renaming `url` variables to `src` in appropriate placse.
There are two reasons for this PR.
1. We use local data too. In `add` and `add_local` this is reflected by naming the arguments `url ` and `content`. So naming all data sources `url` in the following functions is confusing to read when you debug local data. 
2. The `BaseChunker` has `url` as a reused variable. It did not cause problems, but should still be avoided.

refactor: src instead of url

---

embedchain/chunkers/base_chunker.py
embedchain/embedchain.py

This PR solves the issue in #64 
With a large enough data set, the clashing occurs relatively often. We can quickly solve this by adding a random bit into the hash function. Alternatively, we can explore using a set for `ids` instead of a list, which might compromise the data. (ie. what if you're trying to use the bot to make up its own language syntax and communicate via only 10 words)

Prevent clashing chunk IDs

---

embedchain/embedchain.py

this PR makes it so that the `add` method only prints the number of new chunks, instead of the chunk total.
If users are interested in the total amount of chunks, they can use the `count` method at any time, but I think when you add a web page for instance, you want to know how big it is.

feat: add method - only count new chunks and print them

---

tests/test_embedchain.py

Currently, it looks like there are no tests for embedchain python package. Adding basic test case for now that tests the `.add()` and `.query()` class for now.
Test results:
```bash
(base) ➜  embedchain git:(add-basic-test) pytest
====================================================================================== test session starts ======================================================================================
platform darwin -- Python 3.8.8, pytest-6.2.3, py-1.10.0, pluggy-0.13.1
rootdir: /Users/deshrajyadav/Projects/embedchain
plugins: anyio-3.7.0
collected 2 items                                                                                                                                                                               
tests/test_embedchain.py .. …
```

Add unit test for `.add()` and `.query()` function

---

README.md
embedchain/embedchain.py

Added streaming capabilities to OpenSourceApp. Should close #213

added open source app streaming

---

README.md
embedchain/chunkers/docx_file.py
embedchain/chunkers/pdf_file.py
embedchain/chunkers/qna_pair.py
embedchain/chunkers/text.py
embedchain/chunkers/web_page.py
embedchain/chunkers/youtube_video.py
embedchain/config/AddConfig.py
embedchain/data_formatter/data_formatter.py
embedchain/embedchain.py

Resolves: #171 
Changelog:
- `AddConfig` takes two configs as parameter: `ChunkerConfig` and `LoaderConfig`
- `ChunkerConfig` is defined with following parameters
- chunk_size
- chunk_overlap
- length_function
- Default values for these config parameters depend of the `data_type`
- `LoaderConfig` is empty for now
- Updated README with parameters and examples

[Feat] AddConfig should allow configuring Chunker

---

setup.py

adds the actual dev dependencies. they will be installed with `make install`.

chore: add dev dependencies

---

embedchain/config/InitConfig.py
embedchain/vectordb/chroma_db.py

If the instance is created in the init method, it's created even if you want to use an open source model. That's why you need to create it later, depending on the class of the app. That's what the methods `_set_db_to_default` and `_set_embedding_function_to_default` are for.

fix: do not create instance in InitConfig `__init__`

---

setup.py

I thought this came with python, but apparently it doesn't. So I added it as a dev dependency.

chore: add pytest as a dev dependency

---

embedchain/vectordb/chroma_db.py

`InitConfig.py` already sets a default embedding function, so there's no reason to have a duplicate in the `ChromaDb` class.

refactor: no default embedding function

---

embedchain/loaders/sitemap.py

I have previously spoken up against escaping errors. But this is different with bulk jobs like the sitemap. You don't want the whole sitemap to stop processing because one site failed.
This error escapes beautiful soup's `ParserRejectedMarkup` error. I found this happens when a file attachment page made it to the sitemap, that's just the attachment and not an html file.
Example output:
```
2023-07-15 00:50:30,466 [root] [ERROR] Failed to parse https://example.com/verify.png: The markup you provided was rejected by the parser. Trying a different parser or a different encoding may help.
Original exception(s) from parser:
unknown status keyword 'h' in marked section
```

fix: escape bs4 parsing error

---

requirements/dev.txt

Dev requirements are already in `setup.py`. From there you already install them with `make install`. so this is redundant.

chore: remove duplicate dev requirements

---

embedchain/config/InitConfig.py

When creating an app using the latest commit, was getting following error
```
ids, embeddings, metadatas, documents = self._validate_embedding_set(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Tried the published package and realized that db is getting initialized in init config where the embedding function is not available yet.
Bug fix (non-breaking change which fixes an issue)

fix: Dont initialize chroma and embedding function in init config.

---

embedchain/loaders/web_page.py

Was getting divide by zero error when original size is 0
Bug fix (non-breaking change which fixes an issue)

fix: Handle divide by zero error when original size is 0

---

.github/PULL_REQUEST_TEMPLATE.md

I think it's redundant to ask if the change **requires** a documentation update, because that question is already part of the checklist.
Instead what's missing is the option for a type of change the **IS** a documentation update.

chore: documentation handling

---

pyproject.toml

Isort is needed for code formatting, but it's not installed with poetry.
Sidenote: We should consider Jupyter Notebooks as an extra.
-

fix: add isort dev dependency

---

embedchain/chunkers/base_chunker.py
embedchain/data_formatter/data_formatter.py

Added data type to the metadata object.
Fixes #258
Tested by logging metadatas_with_metadata variable before pushing to db for a Youtube video:
```
app = App()
app.add("youtube_video", "https://youtu.be/ilIefxbSJT8")
```
This adds 'embedchain_data_type': 'youtube_video' to the metadata object for each document

added data format to metadata internally

---

docs/advanced/data_types.mdx
embedchain/loaders/sitemap.py
embedchain/utils.py

This feature brings great improvements to the way a sitemap is loaded, in two ways.
1. Only <loc> tags that are direct children of <url > tags are loaded. This should filter out <loc>s that are children of <image> tags. SEOPress and other WordPress plugins seem to include images like this.
2. Filters binary pages. If a page contains less than 95% printable characters, it is excluded. This is the case for pictures and other binary files. For any HTML it should be okay. We can adjust this value, but it worked in all my tests.
More about 1:  If for some reason, the sitemap is structured differently where <url> tags are not used (I could not find an example for this), if the list is empty after using the new method, the previous method that adds all <loc>s is used.
I also added docs that did …

feat: filter sitemap

---

docs/advanced/query_configuration.mdx
embedchain/chunkers/docs_site.py

The config used in `docs_site` has been deprecated.
Also, the default chunker config was not listed in the docs.

fix: `docs_site` use chunker config implementation

---

embedchain/apps/PersonApp.py

When using PersonApp or PersonOpenSourceApp the following error occurs:-
ValueError: ChromaDb cannot be instantiated without an embedding function
The error is caused by these 2 lines in EmbedChainPersonApp class:-
```python
if config is None:
config = BaseAppConfig()
```
Although since the PersonApp inherits from App, and PersonOpenSourceApp inherits from OpenSourceApp, the config is already getting set during their initialization with the super constructor. So the above 2 lines of code can be omitted as they don't provide any functionality that isn't already present, and they cause an error to occur too.
This bug was tested with a small test script as follows:-
```python
naval_chat_bot = PersonApp("Jesse Pinkman")
naval_chat_bot.add("youtube_video", …
```

fix: ValueError: ChromaDb cannot be instantiated without an embedding function

---

embedchain/vectordb/chroma_db.py

Recently updated Chroma db but the way chroma db settings is passed needs to be updated.
if settings involve host and port, we need to use chromadb.HttpClient
if settings involve db dir, we need to use chromadb.PersistentClient
cc @candidosales

bug: Chroma needs diff client as per settings

---

embedchain/apps/PersonApp.py

fixed PersonOpenSourceApp throwing error when trying to query 
Fixes #352 
```from embedchain import PersonOpenSourceApp
app = PersonOpenSourceApp("Yoda")
app.add("youtube_video", "https://youtu.be/ilIefxbSJT8")
print(app.query("What is Oppenheimer about?"))
```

Fixed PersonOpenSourceApp query error

---

docs/quickstart.mdx

Fixed documentation to use correct instance name
Fixes #360

added fix for documentation

---

docs/advanced/query_configuration.mdx

adds back the query config that has gone missing.
Resolves #299 

docs: add back query config

---

embedchain/config/apps/AppConfig.py

fix arguments being in different order in doc string, compared to actual init method implementation.
It's only a doc string change.
Fixes -

docs: fix argument out of order

---

embedchain/apps/CustomApp.py
embedchain/config/ChatConfig.py
embedchain/config/QueryConfig.py
embedchain/config/apps/CustomAppConfig.py

Pass deployment name in config so that OpenAI Azure api integration works.
Example
```
import os
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["OPENAI_API_BASE"] = "https://<endpoint_assigned_to_you>.openai.azure.com"
os.environ["OPENAI_API_KEY"] = "your-id-here"
from embedchain import CustomApp
from embedchain.config import CustomAppConfig, QueryConfig
from embedchain.models import Providers, EmbeddingFunctions
config = CustomAppConfig(embedding_fn=EmbeddingFunctions.OPENAI, provider=Providers.AZURE_OPENAI, deployment_name="text-embedding-ada-002")
query_config = QueryConfig(deployment_name="embedchainpocgpt35")
satya_nadela_bot = CustomApp(config)
satya_nadela_bot.add("web_page", "https://en.wikipedia.org/wiki/Satya_Nadella")
satya_nadela_bot.query("What is the date of birth of …
```

fix: Pass deployment name as param for azure api

---

docs/advanced/data_types.mdx
docs/advanced/query_configuration.mdx
embedchain/chunkers/notion.py
embedchain/data_formatter/data_formatter.py
embedchain/loaders/notion.py
pyproject.toml
setup.py

* notion loader
* notion chunker (copy of text)
* id parser
* docs
* error handling for import error
Missing:
* unit tests
* does definitely **not** work for public pages, I tested this and I guess the connection is not enabled
* documentation how to enable the connection in notion is not included
Notes:
* errors for no connection are really bad (this should ideally be improved by the dependency)
Fixes #26 
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test …

feat: notion loader

---

pyproject.toml

Adds `Flask` and `Twilio` to poetry dependencies
Fixes #464
Yes

Add whatsapp bot poetry dependencies

---

.github/workflows/cd.yml

Adds a workflow to release on pypi and testpypi when a new version is released on github.
This uses the recommended, new OIDC authentication. This means you don't have to store credentials, **all you have to do is authenticate the workflow from the pypi site**.
You can do so here: https://pypi.org/manage/account/publishing/
The workflow name is `cd.yml`
test.pypi is also included, I'm not sure if it will fail if you don't authenticate it, but I think you might as well do it, it's the same exact thing just at https://test.pypi.org/manage/account/publishing/
Fixes #247 
Please …

chore: add release workflow

---

embedchain/embedchain.py
tests/embedchain/test_chat.py

We want to improve our telemetry to improve our package. Hence, adding support for storing the anonymous user_id in telemetry call. **Note that this DOES NOT take any user information from their system.**
We generate a uuid and assign it to the user to track the user event anonymously. 
Tested locally and works fine.

[feat]: add support for sending anonymous user_id in telemetry

---

embedchain/apps/App.py
embedchain/apps/CustomApp.py
embedchain/apps/Llama2App.py
embedchain/apps/OpenSourceApp.py
embedchain/embedchain.py
tests/embedchain/test_query.py

Add `system_prompt` on app level as well.
Fixes #452
Run `poetry run pytest`

System prompt at App level

---

pyproject.toml

Fixes #546 
Fixes `OSError: /lib/x86_64-linux-gnu/libstdc++.so.6: version GLIBCXX_3.4.29' not found`

fix: pin gpt4all version

---

embedchain/__init__.py

Seems like elasticsearch import was added to the __init__.py imports accidentally which makes it mandatory for the embedchain package. Although, ES is not supposed to be mandatory for using embedchain. Hence, fixing this issue.

Remove elasticsearch as mandatory dependency

---

embedchain/helper/json_serializable.py
tests/helper_classes/test_json_serializable.py

adds a convention with `{__type__: ..., data: ...}` to include custom serializers for attributes, which are non-serializable by default.
One example of this is `template`, which was not serializable before this.

fix: serialize non serializable

---

embedchain/loaders/notion.py
pyproject.toml

Use llama hub instead of llama index.
Currently, only Notion is using this in main, so I couldn't run wide compatibility tests.
My notion test actually fails, but after the import. That might be because I just reused my old test code, someone who really uses notion should test this.
```python3
import os
from embedchain.config import AppConfig
config = AppConfig(log_level="DEBUG")
app = App(config=config)
os.environ["NOTION_INTEGRATION_TOKEN"] = "secret"
id = …
```

refactor: use llama hub instead of llama index

---

embedchain/llm/llama2.py

* makes specific defaults for llama2 easier to maintain
* improves serialization
* fixes issue where `max_tokens` are not loaded from config
the only concern: `max_tokens` is now being used in place of `max_length`, when one is actually referring to tokens and the other might be refering to something else (not sure).
Fixes #593

fix: llama2 - use config with specific defaults

---

embedchain/embedchain.py

* made get existing doc id it's own method to cleanup the code
* check for length instead of try-except block
- [X,] Test Script (please provide)
```python
from embedchain.config import AppConfig, ChromaDbConfig
app = App(config=AppConfig(log_level="WARNING"), chromadb_config=ChromaDbConfig(chroma_settings={"allow_reset": True}))
app.db.reset()
app.add(("what is your favorite color?", "green"))
app.add(("what is your favorite color?", "red"))
app.add(("what is your favorite color?", "red")) …
```

refactor: get existing doc id method

---

docs/advanced/interface_types.mdx

- Changed _displays_ to _display_ and _send_ to _sent_.

Fixed minor grammatical issues in documentation: Interface Types

---

embedchain/embedchain.py
embedchain/llm/openai.py
tests/llm/test_query.py

Integrating langsmith in embedchain, so that users can have full visibility of what's happening.
Step 1 in this direction is using OpenAI LLM via langchain so that full trace can be seen.
This PR implements this functionality.

fix: use openai llm via langchain

---

embedchain/vectordb/opensearch.py
pyproject.toml

Currently OpenSearch db doesn't support metadata filering based on the app_id. This PR adds support for the same.
Tested via the script given below:
```python
from embedchain import CustomApp
from embedchain.config import OpenSearchDBConfig, CustomAppConfig
from embedchain.embedder.openai import OpenAIEmbedder
from embedchain.vectordb.opensearch import OpenSearchDB
from embedchain.llm.openai import OpenAILlm
opensearch_url = "https://localhost:9200"
http_auth = ("username", "passsword")
db_config = OpenSearchDBConfig(
opensearch_url=opensearch_url,
http_auth=http_auth,
use_ssl=True,
timeout=30,
)
app_config = CustomAppConfig(id="new_app_id_1")
db = OpenSearchDB(config=db_config)
app1 = CustomApp(config=app_config, llm=OpenAILlm(), …
```

[OpenSearch] Add support for filtering docs based on app_id in opensearch db

---

embedchain/vectordb/opensearch.py
pyproject.toml

With the new changes where we intake the `embeddings` and `skip_embedding` params in `.add()` and `.query()`, those changes are not yet implemented for the opensearch db. Adding support to pass these params to the opensearch db but not use it yet to make the OpenSearch db class usable. 
@rupeshbansal can you please help with adding support for these params in a follow up PR?

[OpenSearch]: Fix `add()` and `query()` for opensearch db

---

.github/workflows/ci.yml
embedchain/models/clip_processor.py
pyproject.toml
tests/models/test_clip_processor.py

Apparently, pypi doesn't allow adding git repo as dependencies and errors out package build with 
```
Uploading embedchain-0.0.66-py3-none-any.whl
25l
0% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 0.0/97.7 kB • --:-- • ?
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.7/97.7 kB • 00:00 • 185.5 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.7/97.7 kB • 00:00 • 185.5 MB/s
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.7/97.7 kB • 00:00 • 185.5 MB/s
[25](https://github.com/embedchain/embedchain/actions/runs/6412333721/job/17409522896#step:8:26)hWARNING  Error during upload. Retry with the --verbose option for more details. 
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/          
Invalid value for requires_dist. Error: Can't have direct dependency:  
'clip @ …
```

[Images] Remove 'clip' from the list of depdencies since pypi doesn't allow it

---

embedchain/embedchain.py

This PR fixes qna pair not being able to load properly.
Fixes #813

[Bug fix] Qna pair not loading properly

---

embedchain/llm/openai.py
pyproject.toml
tests/apps/test_apps.py
tests/llm/test_base_llm.py
tests/llm/test_cohere.py
tests/llm/test_huggingface.py
tests/llm/test_llama2.py
tests/llm/test_openai.py
tests/llm/test_query.py
tests/models/test_data_type.py

This PR fixes Open AI LLM for streaming and adds more tests

Improve and add more tests

---

embedchain/vectordb/chroma.py
tests/vectordb/test_chroma_db.py

We currently dont have any batching in chromadb, which can potentially fail for very large documents.
Fixes #788

Batch Uploading in Chromadb

---

embedchain/chunkers/base_chunker.py
tests/chunkers/test_base_chunker.py

Noticed that there is a minor issue where if you create multiple apps in embedchain but add same data source, it will not try to add data source for the second app since it assumes that it exists. But this behaviour is not correct. We only want to not add data for an app if the data has not been added before for that app only.

[Bugfix]: Fix issue of context overspilling into other apps

---

.gitignore
embedchain/vectordb/chroma.py
tests/vectordb/test_chroma_db.py

In the case of ChromaDB, the existing `reset()` function was designed to clear all data from the database. However, based on our specific requirements, we only need to clear the app's collections context, rather than wiping out the entire database. This PR addresses this issue by modifying the reset() function to clear only the collection data.
This PR also updates the tests accordingly and adds clean up `reset()` calls.
Fixes #842

[Bug fix] reset() erases everything from db

---

embedchain/__init__.py
embedchain/client.py
embedchain/config/__init__.py
embedchain/embedchain.py
embedchain/pipeline.py
tests/conftest.py
tests/embedchain/test_add.py
tests/test_client.py
tests/vectordb/test_chroma_db.py

We want to enable developers to be able to productionize the pipelines that they are creating locally on their own data. This is done by deploying the local embedchain pipeline to production through an API key which is provided by the platform. 
Instructions on how someone can try out this integration:
```python
from embedchain import Pipeline
p = Pipeline.from_config(yaml_path="configs/chroma.yaml")
p.add("https://en.wikipedia.org/wiki/Elon_Musk")
p.add("https://www.forbes.com/profile/elon-musk")
p.add("https://www.youtube.com/watch?v=RcYjXbSJBN8")
p.deploy()
```

[Feature] Add support for deploying local pipelines to Embedchain platform

---

embedchain/apps/app.py
embedchain/pipeline.py
examples/rest-api/requirements.txt
pyproject.toml

This PR fixes the `Pipeline` to use `embedder` as well in the YAML config to support backward compatibility. This PR also adds support to pass `embedding_model` to `App`

Use either `embedder` or `embedding_model` as YAML key

---

embedchain/apps/app.py
embedchain/config/add_config.py
embedchain/embedchain.py
embedchain/pipeline.py
embedchain/utils.py

This PR adds `chunker` key into the YAML config facilitating us to use a default chunker config for the app from the very instantiation of the App. This also handles, length_function gracefully so that user can provide a full module + func_name to access the function directly. Also, now its possible to access chunker config directly from an app,
For example: 
```python
print("App: ", app.chunker)
print(app.chunker.chunk_size)
print(app.chunker.chunk_overlap)
print(app.chunker.length_function)
```
Outputs,
```
App:  <embedchain.config.add_config.ChunkerConfig object at 0x13778a1d0>
100
20
<built-in function len>
```
config.yaml
```yaml
chunker:
chunk_size: 100
chunk_overlap: 20
length_function: 'len'
```

Introduce chunker config in yaml config

---

embedchain/embedchain.py
embedchain/pipeline.py

This PR adds `check_same_thread=False` which will help us use Embedchain directly as a bot or an instance in REST APIs.
Refer: #856

Set `check_same_thread` false so that one App can be used in parallel

---

embedchain/embedchain.py
embedchain/factory.py
embedchain/helper/json_serializable.py
embedchain/telemetry/posthog.py
tests/embedchain/test_embedchain.py
tests/helper_classes/test_json_serializable.py
tests/llm/test_chat.py
tests/llm/test_query.py
tests/telemetry/test_posthog.py

The pull request addresses a refactoring issue, aiming for the marking of private methods with an underscore, as defined in the PEP8 guidelines.
The following methods have been adjusted:
- retrieve_from_database (embedchain.py)
- load_and_embed (embedchain.py)
- register_class_as_deserializable (json_serializable.py)
- get_user_id (posthog.py)
All classes and functions have been reviewed and verified for adjustment.
Fixes #628 

Refactor: Make it clear what methods are private

---

embedchain/loaders/sitemap.py

Accidentally removed the docstring in the last commit. Adding it back for sitemap loader.

[Docs] Add back sitemap loader docstring

---

embedchain/loaders/substack.py
pyproject.toml

Seems like sleep time of 0.4 secs was throwing 429 from substack. Hence bumping to 1 sec for now.

[Bug fix] Update sleep time for substack loader and version bump

---

embedchain/loaders/github.py
embedchain/utils.py

[Feature] Improve GitHub loader

---

embedchain/utils.py

This commit lazily loads the bs4 import. This is needed so that not everyone has to install the bs4 package. 
Without this, it throws an error and requires everyone to install the bs4 package.

Import beautifulsoup pacakge lazily.

---

embedchain/__init__.py
embedchain/apps/app.py
embedchain/embedchain.py
embedchain/pipeline.py
embedchain/store/assistants.py
pyproject.toml

[Bug fix] Fix issue of missing user directory

---

embedchain/loaders/discord.py
embedchain/vectordb/opensearch.py
pyproject.toml

Noticed that if we have more than 100 indexes, the current logic was buggy and it only indexes the first 100 chunks and ignores the rest of them. This PR fixes the issue.

[BugFix] Fix issue of chunks not getting embedded in opensearch index

---

docs/data-sources/github.mdx
docs/data-sources/mysql.mdx
docs/data-sources/overview.mdx
embedchain/data_formatter/data_formatter.py
embedchain/loaders/discord.py
embedchain/loaders/github.py
poetry.lock
pyproject.toml
tests/loaders/test_github.py

This PR adds functionality to load issues and PR from github repos.

[Improvement] improve github loader

---

embedchain/loaders/sitemap.py
pyproject.toml

Avoid using `is_readable` as there could be emojis on the page which are considered unreadable. Emojis could be in markdown file or webpage.

fix sitemap loader

---

docs/get-started/introduction.mdx

A user on slack reported the issue of missing docs on how to get the sources when using the `app.query()` or `app.chat()` functionality. This PR adds documentation for the same.

[Docs] Add documentation about getting source along with the answer

---

pyproject.toml

Used poetry's core to manage package build instead of setuptools so that we can add,
```toml
packages = [
{ include = "embedchain" },
] # to build and install embedchain package only
```
Fixes #759

Fix multiple top level packages

---

embedchain/data_formatter/data_formatter.py
embedchain/loaders/directory_loader.py
embedchain/models/data_type.py
embedchain/utils.py
tests/embedchain/test_utils.py

This PR adds support for loading files from a directory.
```python
import os
from embedchain import Pipeline as App
os.environ["OPENAI_API_KEY"] = "sk-xxx"
app = App()
app.add("./test", data_type="dir")
response = app.query("list all files")
```
```python
import os
from embedchain import Pipeline as App
from embedchain.loaders.directory_loader import DirectoryLoader
os.environ["OPENAI_API_KEY"] = "sk-xxx"
lconfig = {
"recursive": True,
"extensions": [".txt"]
}
loader = DirectoryLoader(config=lconfig)
app = App()
app.add("./test", loader=loader)
response = app.query("what are all the files related to?")
```

directory_loader - load all files from just mentioning path

---

embedchain/loaders/github.py

In github.py, Repo.clone_from(repo_url, local_path) is used twice, causing an error when executed the second time.

Fix the Error Caused by Executing Repo.clone_from Twice

---

docs/get-started/faq.mdx

Removed open ai key statements from our faq

[chore] docs update: don't need open ai key for gpt4all model

---

docs/examples/notebooks-and-replits.mdx
docs/mint.json
notebooks/openai.ipynb

- Added `Notebooks & Replits` page
- removed `deployment_name` from openai google colab notebook

[chore] Remove `deployment_name` for openai embedder and update docs

---

Makefile
pyproject.toml

- Keep `pypdf` and `bs4` in package by default as they are the most used ones (remove friction)
cc @deshraj

[chore] pypdf and bs4 by default in package

---

docs/integration/streamlit-mistral.mdx

The config.yaml example was not parsable and throwing cryptic errors like
```
File "/Users/dhravyashah/Documents/code/raspAI/env/lib/python3.9/site-packages/embedchain/pipeline.py", line 395, in from_config
raise Exception(f"Error occurred while validating the config. Error: {str(e)}")
Exception: Error occurred while validating the config. Error: Key 'app' error:
None should be instance of 'dict'
```
Adding indents solves this issue
Added indents in documentation
Fixes # (no issue)

Fix: indents in yaml file

---

docs/api-reference/pipeline/chat.mdx
docs/api-reference/pipeline/query.mdx
docs/api-reference/pipeline/search.mdx
docs/use-cases/semantic-search.mdx
embedchain/pipeline.py
embedchain/vectordb/chroma.py
embedchain/vectordb/elasticsearch.py
embedchain/vectordb/opensearch.py
embedchain/vectordb/pinecone.py
embedchain/vectordb/qdrant.py
embedchain/vectordb/weaviate.py
embedchain/vectordb/zilliz.py
tests/vectordb/test_chroma_db.py
tests/vectordb/test_elasticsearch_db.py
tests/vectordb/test_zilliz_db.py

This PR enables returning all the metadata we store during indexing at the time of `search/query/chat` when `citations` flag is set to `True`

[Improvement] return all the metadata when citations flag is `True`

---

embedchain/chunkers/rss_feed.py
embedchain/loaders/rss_feed.py

When I tried to used the rss_feed loader, I encoutered errors. The errors were 2 typos when importing the method register_deserializable from json_serializable file.
```sh
from  => embedchain.helper.json_serializable import register_deserializable
to    => embedchain.helpers.json_serializable import register_deserializable
```
I tested it manually after fixing the typos.
No tests files were made for the rss_feed feature.

fix: typo when import helpers.json_serializable on rss_feed files

---

embedchain/embedchain.py

- Remove unused and deprecated app.count() method
- Format imports with pre-commit hook
Fixes #710

#710 | Remove unused and deprecated app.count method

---

embedchain/loaders/slack.py
pyproject.toml

This PR improves the slack loader to fetch maximum possible matching messages when searching using slack API. Max supported count is `100`, otherwise defaults to `20`.

[Improvement] fix slack loader max_count

---

embedchain/loaders/json.py
embedchain/loaders/openapi.py

Fixed below functions
- openapi.py 
- Fix yaml.load function argument to prevent arbitrary code execution
- json.py
- Added character length limitation to fix ReDoS issue

Fix two security issues 

---

embedchain/embedder/base.py
pyproject.toml

Reported by a user on the slack thread here: https://embedchain.slack.com/archives/C05RG7CJKC6/p1704820574470419
Error:
```
ValueError: Expected EmbeddingFunction.__call__ to have the following signature: odict_keys(['self', 'input']), got odict_keys(['self', 'input_'])
```
Checked with the user that the changes in this PR works for them.

[Bug fix] Fix chromadb issue on embedchain version 0.1.58

---

embedchain/app.py
pyproject.toml

[Bug fix] Fix issue of loading other languages in config file

---

docs/api-reference/pipeline/delete.mdx
embedchain/embedchain.py
embedchain/memory/base.py
pyproject.toml
tests/memory/test_chat_memory.py

This PR fixes chat history management when calling `app.reset()`.
- instead of only deleting `default` session, delete all sessions at the time of `app.reset`

[Bugfix] fix chat history management when app.reset

---

notebooks/chromadb.ipynb

This fixes issue #1176 (a bug in the chromadb provider definition, inside `notebooks/chromadb.ipynb`)

Fix #1176 (a bug in the chromadb provider definition example)

---

embedchain/utils/misc.py

[Bugfix] fix import youtube allowed netlocks by defining them locally

---

docs/api-reference/advanced/configuration.mdx
docs/components/llms.mdx
embedchain/config/embedder/base.py
embedchain/embedder/google.py
embedchain/embedder/gpt4all.py
embedchain/embedder/huggingface.py
embedchain/embedder/openai.py
embedchain/embedder/vertexai.py
embedchain/utils/misc.py

This PR enable users to define `vector_dimension` configuration in embedder config to be able to support different huggingface embedding models with different dimensions.

[Improvement] add vector_dimension configuration in embedder config

---

embedchain/vectordb/zilliz.py
tests/vectordb/test_zilliz_db.py

This PR includes following changes:
```python
config = {
"vectordb": {
"provider": "zilliz",
"config": {
"uri": "https://xxx.zillizcloud.com",
"token": "xxx",
"vector_dim": 1536,
"metric_type": "L2",
"collection_name": "zilliz_index",
},
}
}
print(list(map(lambda x: x[1]["url"], context)))
```
Please …

[Bugfix] update zilliz db

---

embedchain/vectordb/qdrant.py
embedchain/vectordb/weaviate.py
tests/vectordb/test_qdrant.py

This PR fixes bugs related to qdrant and weaviate db integration. Specifically, it enables two functionalities with Qdrant and Weaviate.
```python
config = {
"vectordb": {
"provider": "qdrant",
"config": {
"collection_name": "my_qdrant_index"
},
}
}
print(list(map(lambda x: x[1]["url"], context)))
``` …

[Bugfix] fix qdrant and weaviate db integration

---

docs/api-reference/app/chat.mdx
docs/components/data-sources/custom.mdx
embedchain/chunkers/base_chunker.py
pyproject.toml

Reported by a user on discord: https://discord.com/channels/1121119078191480945/1125758905310519327/1201434846803800145
Error:
```
home/karthikeya/.local/lib/python3.10/site-packages/torch/_utils.py:831: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
return self.fget.__get__(instance, owner)()
Traceback (most recent call last):
File "/home/karthikeya/ug/sem8/yogleads/chatdocs/quickstart.py", line 20, in <module>
app.add(gmail_filter, data_type="gmail")
File "/home/karthikeya/.local/lib/python3.10/site-packages/embedchain/embedchain.py", line 201, in add …
```

[Bug fix] Fix issue with gmail loader

---

embedchain/loaders/json.py

This pull request updates the URL validation regex to accommodate URLs with http or https protocols, IP addresses, optional port numbers, and URL-encoded characters, ensuring broader validation coverage. This change allows the system to correctly validate URLs like http://192.168.1.140:9000/1%202%20Inflación-wav.json, which include direct IP access with port specifications and encoded characters, enhancing compatibility with a wider range of URLs.
Fixes #1232

Update URL Validation Regex to Support IP Addresses and Port Numbers

---

embedchain/factory.py
pyproject.toml

Fixes #1241 
```python
app_config = {
"app": {"config": {"id": "embedchain-demo-app"}},
"llm": {
"provider": "huggingface",
"config": {
"model": "mistralai/Mixtral-8x7B-Instruct-v0.1",
"temperature": 0.1,
"max_tokens": 250,
"top_p": 0.1,
},
},
"embedder": {"provider": "huggingface", "config": {"model": "sentence-transformers/all-mpnet-base-v2"}},
}
ec_app = App.from_config(config=app_config)
a = ec_app.query("What is the capital of France?")
print(a)
```

[Bug Fix] Fix issue related to using embedding model from huggingface

---

docs/components/llms.mdx
embedchain/llm/aws_bedrock.py

When I used the AWS Bedrock LLM configuration in my [article](https://how.wtf/how-to-use-embedchain-with-aws-bedrock.html), I got a model access error because the region is hardcoded to `us-west-2` in the source.
`AWS_REGION` is a [widely-accepted environment variable](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html) for AWS credentials.
I ran the following script:
```python
bot = App.from_config(config_path="config.yaml")
bot.add("https://en.wikipedia.org/wiki/Ada_Lovelace")
print(bot.query("Who is Ada Lovelace?"))
```
with my `AWS_REGION` environment variable exported and an AWS profile set.
Here is the configuration:
```yaml
llm:
provider: aws_bedrock
config:
model: anthropic.claude-v2 …
```

[Bug Fix] Add support for `AWS_REGION` override

---

docs/api-reference/app/search.mdx
docs/components/vector-databases.mdx
embedchain/app.py
embedchain/config/vectordb/pinecone.py
embedchain/embedchain.py
embedchain/loaders/json.py
embedchain/vectordb/chroma.py
embedchain/vectordb/pinecone.py
pyproject.toml
tests/vectordb/test_pinecone.py

Requested by one of our users on the slack group. 
This PR adds support for following:
- Metadata filtering on the search API
- Add support for two ways to do metadata filtering: 1) Passing simple key value filters, 2) Passing raw query for the vector database
- Update docs for the same
- Refactor code
```python
import os
os.environ["PINECONE_API_KEY"] = "xxx"
config = {
"vectordb": {
"provider": "pinecone",
"config": {
"metric": "dotproduct",
"vector_dimension": 1536,
"index_name": "ec-test",
"serverless_config": {"cloud": "aws", "region": "us-west-2"},
},
}
}
app.add("https://www.forbes.com/profile/bill-gates", metadata={"type": "forbes", "person": "gates", "year": 2022})
app.add("https://en.wikipedia.org/wiki/Bill_Gates", …
```

[Feature] Add support for metadata filtering on search API

---

README.md
docs/components/data-sources/dropbox.mdx
docs/components/data-sources/google-drive.mdx
embedchain/deployment/fly.io/app.py
embedchain/deployment/modal.com/app.py
embedchain/deployment/render.com/app.py
pyproject.toml

Removing the usage of 'Pipeline' in favor of 'App' class since we have deprecated the 'Pipeline' class. 

[Refactor] Remove usage of 'Pipeline' in favor of 'App'

---

docs/components/data-sources/youtube-channel.mdx

Hey there! Noticed a small typo in the pip install command. The -u flag should actually be -U for upgrading. Just fixing it up to avoid any confusion for fellow users. 😊
-  [x] Documentation update

Typo fixed in youtube-channel.mdx

---

docs/components/data-sources/youtube-video.mdx

`pip install -u "embedchain[youtube]"` command. The `-u` flag should be `-U` for upgrading.
Noticed a small typo in the `pip install` command. The `-u` flag should actually be `-U` for upgrading. Just fixing it up to avoid any 
confusion for fellow users. 😊

Typo fixed youtube-video.mdx

---

embedchain/embedchain.py
embedchain/vectordb/weaviate.py

I was trying to load in a large sitemap and hit a 403 from OpenAI.  Turns out that there are limitations on the embeddings endpoints:
- The input parameter may not take a list longer than 2048 elements (chunks of text).
- The total number of tokens across all list elements of the input parameter cannot exceed 1,000,000. (Because the rate limit is 1,000,000 tokens per minute.)
- Each individual array element (chunk of text) cannot be more than 8191 tokens.
Discussion can be found here: https://github.com/openai/openai-python/issues/519#issuecomment-1636921388
This fixes the first  limit breaking the documents in batches of 2048 elements in the array being sent.
There is also a small fix here for issues that occur when the weaviate provider doesn't retrieve any results.
Please delete …

Fixes to null data results and openAI embedding limits

---

embedchain/utils/misc.py

📄 `is_readable()` in `embedchain/utils/misc.py`
📈 Performance went up by **`101%`** (**`1.01x` faster**)
⏱️ Runtime went down from **`1012.51μs`** to **`504.30μs`**
Explanation and details
<details>
The current program is using a try-except block and calling the logging.warning function when the length of the string is zero. However, this does not need to be caught as an exception and can be handled in a simple if condition check. Also, the `in` operator is inefficient as it scans through all the characters in `string.printable` for every character in `s` resulting in a time complexity of O(n*m). A one-time creation of `set(string.printable)` can greatly improve the execution time. Here is the optimized version of the code:
This version of the program …

⚡️ Speed up `is_readable by` 101% in `embedchain/utils/misc.py`

---

embedchain/config/llm/base.py
embedchain/loaders/discord.py
embedchain/loaders/discourse.py
embedchain/loaders/docx_file.py
embedchain/loaders/local_qna_pair.py
embedchain/loaders/local_text.py
embedchain/loaders/mdx.py
embedchain/loaders/openapi.py
embedchain/loaders/pdf_file.py
embedchain/loaders/rss_feed.py
embedchain/loaders/slack.py
embedchain/loaders/text_file.py
embedchain/loaders/unstructured_file.py
embedchain/loaders/web_page.py
embedchain/loaders/xml.py
embedchain/loaders/youtube_video.py
embedchain/utils/misc.py
pyproject.toml
tests/llm/test_chat.py

Changes:
- Make changes in the default prompt to yield better answers and reduce hallucinations
- Rename var name 'meta_data' to 'metadata' for consistency
- Refactor the clean_string method to parse the context properly

[Improvements] Improve the default prompt and data loader util functions

---

.github/workflows/ci.yml
Makefile
docs/components/vector-databases/pinecone.mdx
embedchain/alembic.ini
embedchain/vectordb/pinecone.py
notebooks/pinecone.ipynb
poetry.lock
pyproject.toml

Changes:
- Add support for python 3.9 to 3.13
- Remove some packages from optional dependencies since they were gating the support for 3.13
- Fix alembic issue of not being able to locate the migrations files

[Feature] Add support for python 3.13 and other migration related fixes

---

docs/components/introduction.mdx
embedchain/app.py
embedchain/client.py
embedchain/config/base_app_config.py
embedchain/constants.py
embedchain/core/db/database.py
embedchain/embedchain.py
embedchain/migrations/env.py
embedchain/utils/misc.py
pyproject.toml
tests/telemetry/test_posthog.py
tests/vectordb/test_chroma_db.py

Changes:
- Add support for passing any db connection params
- Refactor some of the code

Add support for supplying custom db params

---

embedchain/core/db/database.py
pyproject.toml

Forgot to remove the sqlite specific args when making connection for the metadata sql database. Fixed the issue in this PR.
Now, users can try any sql database as their metadata database which stores the chat history and data sources added to their apps.
1. Start postgres db using following command using docker: 
```bash
docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -p 5432:5432 -d postgres
```
2. Now, run embedchain app that uses the created database and stores information there:
```python
import os
os.environ["EMBEDCHAIN_DB_URI"] = "postgresql://postgres:mysecretpassword@localhost:5432/postgres"
app = App()
app.add("https://www.forbes.com/profile/elon-musk")
answer = app.chat("What is the net worth of Elon Musk?")
print(answer)
```
3. …

[Bug fix] Fix issue for using any metadata db apart from sqlite

---

docs/components/llms.mdx
embedchain/factory.py
embedchain/llm/groq.py
embedchain/llm/openai.py
embedchain/utils/misc.py
pyproject.toml

As the title suggests. A lot of folks DM'ed me about Groq LLMs integration with Embedchain.

[Feature] Add support for Groq LLMs

---

embedchain/config/vectordb/pinecone.py
embedchain/embedchain.py
embedchain/vectordb/pinecone.py
pyproject.toml

Changes:
- Delete row from data sources whenever someone calls app.delete()
- Delete the chat history when someone calls app.reset()
- Add support for passing custome bm25encoder when using pinecone vector database

[Feature/Improvements] Delete data sources from metadata db when using `app.delete()`

---

docs/components/llms.mdx
embedchain/config/llm/base.py
embedchain/llm/huggingface.py
embedchain/utils/misc.py
tests/llm/test_huggingface.py

[Feature] Add support for running huggingface models locally

---

embedchain/helpers/callbacks.py
embedchain/llm/aws_bedrock.py
embedchain/llm/cohere.py
embedchain/llm/llama2.py
embedchain/llm/ollama.py
embedchain/llm/together.py
embedchain/llm/vllm.py
pyproject.toml
tests/llm/test_cohere.py
tests/llm/test_llama2.py
tests/llm/test_ollama.py
tests/llm/test_together.py

Seeing some warnings from langchain about __call__ getting deprecated from version 0.2.0. Fixed that warning in this PR.

[Improvement] Fix deprecation warnings

---

docs/components/embedding-models.mdx
docs/components/llms.mdx
embedchain/app.py
embedchain/config/base_app_config.py
embedchain/embedder/nvidia.py
embedchain/factory.py
embedchain/llm/nvidia.py
embedchain/models/vector_dimensions.py
embedchain/store/assistants.py
embedchain/telemetry/posthog.py
embedchain/utils/misc.py
pyproject.toml

[Feature] Add support for NVIDIA AI LLMs and embedding models

---

embedchain/app.py
pyproject.toml

Noticed the issue where `get_data_sources()` function is failing due to the recent change in the schema.

[Bug fix] Fix issue related to get_data_sources() method

---

docs/get-started/quickstart.mdx
embedchain/app.py
pyproject.toml
tests/vectordb/test_qdrant.py

Several folks have mentined this issue that their app data is not persisted when they init the app using `app = App()`. 
This is because we were setting a new app id every time someone does an init. We are changing this behavior to set a default app id unless user specifically configures it in their app configuration during init time.

[Improvement] Set a default app id if not provided in the app configuration

---

configs/ollama.yaml
embedchain/config/llm/base.py
embedchain/llm/ollama.py
embedchain/utils/misc.py

Langchain includes Ollama's base_url for localhost on the default port 11434, but in our case it runs on a different server than Embedchain. We needed to allow customization of this address, so we changed the necessary files to include the custom address to the YAML configuration file.
Create a Ollama server and point the YAML config value "base_url" to the server.

Feature: Custom Ollama endpoint base_url

---

embedchain/config/llm/base.py
pyproject.toml
tests/evaluation/test_answer_relevancy_metric.py
tests/llm/test_openai.py
tests/test_app.py
tests/test_factory.py

Fixing unit tests after adding new feature of base_url for LLMs.

[Bug Fix]: Fix test cases and update version to 0.1.93

---

README.md
embedchain/embedder/openai.py
pyproject.toml

User reported on slack that the new version has a regression resulting into the following error:
```
>>> from embedchain import App
>>> app = App()
>>> app.add("http://deshraj.xyz")
Doc content has not changed. Skipping creating chunks and embeddings
'0d8813f767d2cf9bf728bcc44fc55ff0'
>>> app.chat("Who is Deshraj?")
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/deshrajyadav/Projects/embedchain/embedchain/embedchain.py", line 576, in chat
answer = self.llm.chat(
^^^^^^^^^^^^^^
File "/Users/deshrajyadav/Projects/embedchain/embedchain/llm/base.py", line 278, in chat
answer = self.get_answer_from_llm(prompt)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/deshrajyadav/Projects/embedchain/embedchain/llm/base.py", line 143, in get_answer_from_llm
return …
```

[Bug fix]: Fix issue of OPENAI_API_BASE env variable being mandatory

---

embedchain/factory.py

To support custom or locally hosted Mistral model (or any other) through a VLLM server, the provider type 'vllm' was missing from the list of supported providers in factory.py.
- [y] Bug fix (non-breaking change which fixes an issue)
Tested the change using the embedchain-admin fullstack app.
- [y] My code follows the style guidelines of this project
- [y] I have performed a self-review of my own code
- [y] My changes generate no new warnings
- [y] I have checked my code and corrected any misspellings

added missing provider for 'vllm'

---

Makefile
embedchain/llm/anthropic.py
embedchain/vectordb/qdrant.py
pyproject.toml
tests/llm/test_anthrophic.py

Reported by a user on slack channel: https://embedchain.slack.com/archives/C05RG7CJKC6/p1711609066461749
Tested with the following example:
```python
import os
os.environ['ANTHROPIC_API_KEY'] = 'sk-xxx'
os.environ['OPENAI_API_KEY'] = 'sk-xxx'
config = {
"llm": {
"provider": "anthropic",
"config": {
"model": "claude-3-opus-20240229"
}
}
}
app.query("What is the capital of India?")
```

[Bug Fix] Make claude-3-opus model work

---

docs/components/data-sources/excel-file.mdx
embedchain/chunkers/excel_file.py
embedchain/data_formatter/data_formatter.py
embedchain/loaders/excel_file.py
embedchain/models/data_type.py
embedchain/vectordb/qdrant.py
pyproject.toml
tests/chunkers/test_chunkers.py
tests/loaders/test_excel_file.py

Added support for excel files.
Fixes #1103

Support for Excel files

---

embedchain/config/llm/base.py
embedchain/llm/openai.py
embedchain/utils/misc.py
tests/llm/test_openai.py

Add support for passing headers to requests to OpenAI. This feature is quite useful when using OpenAI with an AI Gateway/proxy. The additional headers are used to pass parameters to the proxies.
Tested locally, by adding instantiating an app and supplying the `default_headers` parameter in the LLM config. Made sure the headers are actually passed as part of the request, by changing the OpenAI baseurl to a local proxy I set up that prints the headers. Added UT as well.

Support supplying custom headers to OpenAI requests

---

embedchain/config/llm/base.py
embedchain/llm/openai.py

embedchain's OpenAI LLM class does not allow the user to provide a custom http client. This can be done through the langchain's ChatOpenAI class which embedchain uses but does not expose the relevant arguments to change the http client. This PR exposes the`http_client` parameter into the config thereby allowing the user to change it.
Fixes #1357 
New feature (non-breaking change which adds functionality)

Added http clients in config

---

embedchain/chunkers/base_chunker.py

📈 Performance went up by **`6%`** (**`0.06x` faster**)
⏱️ Runtime went down from **`1014.51μs`** to **`955.61μs`**
<details>
Changes:
- Changed `sum([len(document.split(" ")) for document in documents])` to `sum(len(document.split(" ")) for document in documents)`. This avoids the memory overhead of creating a list either with list comprehensions or a map - sum accepts a generator, not requiring a separate list at all.
- This makes code more memory efficient, and probably a bit faster, because memory allocation can be an expensive operation and it's not necessary in this case as we are only iterating once over generator and we don't need to use memory to store a list. Python doesn't have to allocate memory to generate a whole new list of word counts and …

⚡️ Speed up `get_word_count()` by 6% in `embedchain/chunkers/base_chunker.py`

---

embedchain/loaders/docs_site_loader.py

📈 Performance went up by **`45%`** (**`0.45x` faster**)
⏱️ Runtime went down from **`1489.11μs`** to **`1029.61μs`**
<details>
To improve the performance of this program, you could apply a few changes:
1. Add a check at the start of the `_get_child_links_recursive()` to return early if the `url` has already been visited. This avoids the overhead of starting an unnecessary HTTP request which is expensive in terms of time.
2. Use `soup.find_all("a", href=True)` to only select anchors with href attribute, this will reduce computation time.
3. Use a generator expression instead of list comprehension for `child_links` and `absolute_paths` to save memory by generating items one at a time, instead of creating the entire list in memory.
4. Instead of looping …

⚡️ Speed up `_get_child_links_recursive()` by 45% in `embedchain/loaders/docs_site_loader.py`

---

embedchain/helpers/json_serializable.py

📈 Performance went up by **`15%`** (**`0.15x` faster**)
⏱️ Runtime went down from **`163.10μs`** to **`142.40μs`**
<details>
Here's a more optimized version of the Python program provided. It provides an improved runtime by avoiding unnecessary dictionary copying and using dictionary comprehension instead of a loop to populate the new dictionary.
This version doesn't change the signature or return value of the function and preserves all the original's necessary features. However, it can provide some runtime efficiency because it directly creates the `dct` dictionary from `obj.__dict__`, skipping the need to make a copy first, and avoiding an unnecessary dictionary size change during iteration. It also replaces the `del dct[key]` operation with simply not …

⚡️ Speed up `_auto_encoder()` by 15% in `embedchain/helpers/json_serializable.py`

---

embedchain/loaders/csv.py

An error occurred in the process of loading csv written in Korean, so the reading method was fixed.
Converted read process to utf-8 and loaded csv file
Example csv
```csv
이름,전화번호
테스트,010-1234-5678
```
Test Source
```py
import os
from dotenv import load_dotenv
load_dotenv()
openai_api_key = os.getenv('OPENAI_API_KEY')
app = App()
app.add('/path/to/file.csv', data_type='csv')  # type: ignore
app.query("테스트 전화번호")
```

[Bug Fix] Fix issue of loading other languages in csv file

---

embedchain/utils/cli.py

📈 Performance went up by **`21%`** (**`0.21x` faster**)
⏱️ Runtime went down from **`842.51μs`** to **`698.00μs`**
<details>
Here is an optimized version of the function. I used an compiled regular expression for better performance and file.readlines() for faster file reading. Here is the code:
This code could be even faster for larger files as it reads the file all at once and uses the compiled regular expression to match lines. It also reduces function calls in the loop, which tend to be expensive, and uses native Python operations.
</details>
The new optimized code was tested for correctness. The results are listed below.
<details>
<summary>(click to show generated tests)</summary>
```python
import pytest …
```

⚡️ Speed up `read_env_file()` by 21% in `embedchain/utils/cli.py`

---

docs/api-reference/advanced/configuration.mdx
embedchain/llm/openai.py
tests/llm/test_openai.py

we can now pass additional arguments to the Chatopenai function, which calls the openai chat. 
This allows user to pass json mode for openai.
Fixes #1156 
I used the following config,
```
llm:
provider: openai
config:
model: 'gpt-3.5-turbo'
temperature: 0.5
max_tokens: 1000
top_p: 1
stream: false
model_kwargs:
response_format: 
type: json_object
```
and a simple rag code 
```
import os
app = App.from_config('/home/pranav/python-projects/website-rag/config.yaml')
app.add("https://en.wikipedia.org/wiki/Butter_chicken")
print(app.query("what is butter chicken good? reply as json with key value 'butter_chicken'"))
```
which gives output - 
```
Inserting batches in chromadb: 100%|███████████████████████████████████| 1/1 …
```

adds model_kwargs to Chatopenai call

---

docs/integration/openlit.mdx

The title in the integration doc for OpenLIT appears to have `:telescope:` instead of 🔭  . This PR fixes the issue and also does a minor update to the description. 
NA
Just title and description update

[Docs]: Fix the Title and Description for OpenLIT Integration

---

embedchain/llm/ollama.py
tests/llm/test_ollama.py

I wanted to create an api which handles streaming responses from an ollama model, but for some reason even though I pass `stream: True` in config, it only streams the output in `stdout`. I was expecting to get a generator given the return type of the function `def _get_answer(prompt: str, config: BaseLlmConfig) -> Union[str, Iterable]`
However I noticed that there is `callback` config which can be used to create the generator from new tokens, but I noticed it is not used in all models, saw it being used in `openai` but in `ollama` we are always by default using `StreamingStdOutCallbackHandler()`.
This PR allows you to use custom callbacks even if you are using `ollama`
Added a test case for this

Allow ollama llm to take custom callback for handling streaming

---

docs/api-reference/advanced/configuration.mdx

Doc fix to show the default vector dimensions of all embedding models

Doc fix for embedders

---

embedchain/config/embedder/google.py
embedchain/config/embedder/ollama.py

Enable adding vector dimensions for Ollama and Google Embedder.
Fixes https://discord.com/channels/1121119078191480945/1125758905310519327/1253049335604580403

Add vector dimension to Ollama embedder

---

docs/api-reference/advanced/configuration.mdx
embedchain/config/embedder/base.py
embedchain/embedder/huggingface.py
embedchain/utils/misc.py

Support for huggingface endpoint for embedding models
Fixes #1434

Add HF endpoint in embedder

---

embedchain/embedder/openai.py
embedchain/llm/azure_openai.py
tests/llm/test_azure_openai.py

Changed the AzureOpenAIEmbeddings import package from "langchain_community.embeddings" to "langchain_openai.embeddings"
Changed the AzureChatOpenAI import package from "langchain_community.embeddings" to "langchain_openai.embeddings"
Changed the default openai_api_version from "2023-05-15" to the newest: "2024-02-01"
Replaced chat(messages).content for chat.invoke(messages).content `BaseChatModel.__call__` is deprecated
Changed the tests for azure open ai to patch the new packages instead of the older ones
Fixes #1373 
Please describe the tests that you ran to verify your …

Fixed Azure OpenAI Deprecations and Adjusted the Tests

---

Makefile
embedchain/config/vectordb/base.py
embedchain/config/vectordb/chroma.py
embedchain/config/vectordb/elasticsearch.py
embedchain/config/vectordb/opensearch.py
embedchain/config/vectordb/pinecone.py
embedchain/config/vectordb/qdrant.py
embedchain/config/vectordb/weaviate.py
embedchain/vectordb/chroma.py
embedchain/vectordb/elasticsearch.py
embedchain/vectordb/opensearch.py
embedchain/vectordb/pinecone.py
embedchain/vectordb/qdrant.py
embedchain/vectordb/weaviate.py
tests/vectordb/test_weaviate.py

Fix issue with prior PR #1448 

Fix batch_size for vectordb

---

docs/api-reference/advanced/configuration.mdx
docs/components/embedding-models.mdx
embedchain/config/embedder/base.py
embedchain/embedder/huggingface.py
embedchain/utils/misc.py
tests/embedder/test_huggingface.py
tests/embedder/test_huggingface_embedder.py

This change allows passing additional params huggingface embedder using `model_kwargs`. This allows the `trust_remote_code=True` option for various models not added to `huggingface/transformers`.
Fixes #1380
I have added unit test for `HuggingFaceEmbedder`. (first unit test for an embedder 🎉)
Also tested using, 
main.py - 
```
import os
app = App.from_config(config_path="./config.yaml")
app.add("https://en.wikipedia.org/wiki/Sun_Tzu")
while True:
question = input("Enter question: ")
if question in ["q", "exit", "quit"]:
break
answer = app.query(question)
print(answer)
```
config.yaml - 
```
llm:
provider: openai
config:
model: 'gpt-3.5-turbo'
temperature: 0.5
max_tokens: 1000
top_p: 1
stream: false
embedder:
provider: …
```

Adding model_kwargs for huggingface embedders.

---

docs/api-reference/advanced/configuration.mdx
embedchain/config/llm/base.py
embedchain/llm/openai.py
embedchain/utils/misc.py
tests/llm/test_openai.py

This would allow users to use pass proxy servers via config. It would allow them to use Embedchain behind a company's proxy setting.
Current implementation lacks creating of `httpx` or any `HttpClient` interface. It expects user a client in config, but there is no documentation on how to use it. I also believe its not possible to pass it this `http_client` value from the config.
This PR allows http proxies to be passed down from config instead, including async proxies (all 
examples in unit tests). It creates a `httpx.Client` or `httpx.AsyncClient` as mentioned in the [Langchain docs](https://python.langchain.com/v0.2/docs/integrations/llms/openai/) on behalf of the user.
Fixes #1452
I tested this on my AzureOpenAI instance, but could not test …

http_client and http_async_client bugfix

---

embedchain/embedchain/app.py
embedchain/embedchain/config/llm/base.py
embedchain/embedchain/llm/base.py
embedchain/poetry.lock
embedchain/tests/conftest.py
embedchain/tests/llm/conftest.py

The metadata database for storing chat history is a sqllite3 db. It is setup up in the app class by using `setup_engine`. 
But running individual tests in llm folder fails because we don't create any app for tests. Individual llm classes are called independently. Thus, `setup_engine` is never called.
This change moves the setup to BaseLlmConfig, which is called every time we load an llm.
Fixes #1400 
Tested individual tests in llm folder, and also tested running my demo app.

Sets up metadata db for every llm class

---

docs/components/llms.mdx
mem0/llms/azure_openai.py
mem0/llms/configs.py
mem0/utils/factory.py
tests/llms/test_azure_openai.py

This PR, built on top of PR #1574 , introduces a dedicated integration with Azure OpenAI LLM. It fixes issues encountered when using Azure OpenAI LLMs via LiteLLM configs and ensures seamless integration.
Fixes #1580 

Support Azure OpenAI LLM

---

docs/platform/quickstart.mdx
mem0/client/main.py
pyproject.toml

Some of the users requested API endpoint to get all the users, agents, apps for which the memories are created.
This PR adds support for the same.

[Mem0] Add support for getting all users in python client

---

mem0/memory/setup.py

If you try to use `mem0` in a lambda function, you'll get a nasty warning like
```
OSError: [Errno 30] Read-only file system: '/home/sbx_user1051'
bla bla bla
in <module>
from mem0.memory.main import Memory
in <module>
from mem0.memory.setup import setup_config\n/tmp/mem0/memory/setup.py:8:
in <module>
os.makedirs(mem0_dir, exist_ok=True)
<frozen os>
bla bla bla
[Errno 30] Read-only file system
```
This is because `~` is read-only on a lambda function.  However, `/tmp` is writeable, as is any mounted EFS directory.  Therefore, if we simply expose the home and `mem0` directories in the code to be injectable as environment variables, we can easily resolve this issue by injecting e.g., `/tmp/mem0`.
I tested the `or` logical locally but didn't …

Make home and mem0 dirs configurable so that the service can work on AWS lambda.

---

mem0/configs/embeddings/base.py
mem0/configs/llms/base.py
mem0/embeddings/openai.py
mem0/llms/openai.py

Some background: Coming from Asian countries with openai restrictions, we cannot directly use the services provided by the openai endpoint, so we have to use a transit service to use openai. So the base_url parameter was added so that users from China can use the products of the mem0 team.
The current PR adds the OPENAI_API_BASE parameter to the config and llm wrapper layers, ensuring that users can set the api_base in the environment variable.
I'm not sure if this is a new feature. If it's not suitable, please tell me in the comment and I will modify it. Thanks 🙏
Please …

[openai_api_base support] - ft/Added openai OPENAI_API_BASE llm config support

---

embedchain/embedchain/embedchain.py

Fix Issue #1520 - The collect_metrics option for the app is not taken into account in all actions. 
Describe the bug
According to the docs, collect_metrics app option allows to turn off sending telemetry data.
However looking at file: (https://github.com/mem0ai/mem0/blob/main/embedchain/embedchain/embedchain.py) this is correct only for add and delete methods.
For each action/method, checked if the collect_metrics was checked before collecting metrics, where it was not the checked it has now been added.
Fixes # 1520
Please advise how this should be tested.

Fixed issue 1520 - the collect_metrics options for the app is now taken into account for all actions

---

mem0/graphs/tools.py
mem0/llms/azure_openai_structured.py
mem0/llms/configs.py
mem0/memory/graph_memory.py
mem0/utils/factory.py

Issue: #1822 
The current graph memory tools have the following:
https://github.com/mem0ai/mem0/blob/965f7a373554433f9f83b666f65abaa7d817e611/mem0/graphs/tools.py#L120
This is good for structured-models of openai but gives error for others.
This is an attempt to change the tool for non-structured models. 
For Azure openai: [here](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/structured-outputs?tabs=python-secure)
_(Support for structured outputs was first added in API version [2024-08-01-preview](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/preview/2024-08-01-preview/inference.json).)_
For openai: [here](https://platform.openai.com/docs/guides/structured-outputs/introduction)
_However, …

[improvement]: Graph memory support for non-structured models.

---

mem0/configs/vector_stores/chroma.py

Remove auto install library for chromadb

---

docs/mint.json
mem0/embeddings/huggingface.py
tests/embeddings/test_huggingface_embeddings.py

Changing the return type of the HuggingFace Embeddings from ndarray to List
Fixes #1752 

Fixing the bug when using Huggingface Models

---

mem0/memory/graph_memory.py
mem0/memory/main.py
tests/test_main.py

Add the `limit` param in get_all and search while using graph.

Add `limit` in get_all and search for Graph

---

mem0/memory/graph_memory.py

Set limit to 100 as default for graph memory.

fix limit param in graph memory

---

docs/components/embedders/models/gemini.mdx
mem0/embeddings/gemini.py
mem0/embeddings/huggingface.py
mem0/embeddings/ollama.py

Refactored and updated embedding models in gemini.py, huggingface.py, and ollama.py. Added documentation for the Gemini embedding model in gemini.mdx.
Fixes #xxxx

[ Refactored ] embedding models and [ Update ] documentation for Gemini model

---

docs/mint.json
mem0/configs/embeddings/base.py
mem0/embeddings/gemini.py
mem0/embeddings/vertexai.py
mem0/utils/factory.py
tests/embeddings/test_vertexai_embeddings.py

Configs related to vertex ai embeddings were missing which has been now added. 

(bug-fix) : fix VertexAI missing configurations 

---

mem0/client/main.py
mem0/memory/main.py
tests/test_main.py

This PR introduces improved error handling in the update method. If a memory_id does not exist, it now handles the situation gracefully without displaying an error. This change enhances the user experience by preventing unnecessary error messages.
Fixes #xxxx

[Add] Error handling for update method in OSS & platform code.

---

mem0/client/main.py

Current endpoint creates a GET_ALL event in the Mem0 Platform. Hence, changing the route to ping endpoint so that it just validates the API key and doesn't do anything else. 
Tested manually and works fine. 
```python
import requests
r = requests.get("https://api.mem0.ai/v1/ping/", headers={"Authorization": "Token m0-xxx"})
r.raise_for_status()
```

Change ping endpoint for validating api key

---

docs/features/direct-import.mdx
docs/mint.json

Add a new platform feature where users can inject their memories directly without going through memory deduction phase.

Updated docs to add the "Direct Memory Storage" feature

---

docs/components/embedders/models/azure_openai.mdx
docs/components/llms/models/azure_openai.mdx
mem0/configs/base.py
mem0/embeddings/azure_openai.py
mem0/llms/azure_openai.py
mem0/llms/azure_openai_structured.py
tests/embeddings/test_azure_openai_embeddings.py
tests/llms/test_azure_openai.py

Add support for customizing the default_headers in AzureOpenAI
Fixes #1924
Simply adding `default_headers` in `azure_kwargs`
```python
import os
os.environ["LLM_AZURE_OPENAI_API_KEY"] = "your-api-key"
os.environ["LLM_AZURE_DEPLOYMENT"] = "your-deployment-name"
os.environ["LLM_AZURE_ENDPOINT"] = "your-api-base-url"
os.environ["LLM_AZURE_API_VERSION"] = "version-to-use"
config = {
"llm": {
"provider": "azure_openai",
"config": {
"model": "your-deployment-name",
"temperature": 0.1,
"max_tokens": 2000,
"azure_kwargs" : {
"azure_deployment" : "",
"api_version" : "",
"azure_endpoint" : "",
"api_key" : ""
"default_headers": {
"Authorization": "xxxx",
"CustomHeader": "xxxx",
}
}
}
}
}
m.add("Likes to play cricket on weekends", …
```

Add Support for Customizing default_headers in Azure OpenAI

---

cookbooks/helper/mem0_teachability.py
mem0/client/main.py
mem0/configs/vector_stores/chroma.py
mem0/memory/main.py
mem0/memory/telemetry.py
tests/embeddings/test_azure_openai_embeddings.py
tests/embeddings/test_gemini.py
tests/embeddings/test_vertexai_embeddings.py
tests/llms/test_gemini_llm.py
tests/llms/test_openai.py
tests/test_main.py
tests/vector_stores/test_chroma.py
tests/vector_stores/test_qdrant.py

Code formatting

---

docs/components/vectordbs/config.mdx
docs/components/vectordbs/dbs/azure_ai_search.mdx
docs/components/vectordbs/overview.mdx
docs/mint.json
mem0/configs/vector_stores/azure_ai_search.py
mem0/utils/factory.py
mem0/vector_stores/azure_ai_search.py
mem0/vector_stores/configs.py

Support Azure AI Search as a vector DB. 
Dependencies: azure-search-documents
```
config = {
"provider": "azure_ai_search",
"config": {
"service_name": "xxxx",
"api_key": "xxx",
"embedding_model_dims": 1536 ,
}
}
}
m.add("Likes to play cricket on weekends", user_id="alice", metadata={"category": "hobbies"})
```
- [] I have added tests that prove my fix is effective or that my feature works
- [] Any dependent changes have been merged and published in downstream modules

Feature - Support Azure AI Search as a Vector DB  

---

mem0/configs/prompts.py

The uuid in get_update_memory_messages.Update prompt is wrong.
There is no old_memory neither.

fix typo in the prompt of get_update_memory_messages

---

mem0/configs/prompts.py
mem0/memory/main.py

For base prompt replace UUID with indexes to reduce hallucinations.

Replace UUID with indexes to reduce hallucinations

---

docs/integrations/vercel-ai-sdk.mdx
docs/mint.json
docs/overview.mdx

Docs: Integration/Vercel AI SDK

---

docs/api-reference/overview.mdx
mem0/client/main.py

Add support for Org/Proj ID. Also added the deprecation warning for names of Org/Proj it will be removed in version `0.1.40`.

Add support for Org/Proj ID

---

docs/integrations/llama-index.mdx
docs/integrations/vercel-ai-sdk.mdx
docs/mint.json

1. llama_index docs added
2. fixed a typo in vercel docs

[docs]: llama index docs added

---

mem0/memory/graph_memory.py
mem0/memory/utils.py

Related issues: 
#1975 
#1906
#1805

[graph_improvement]: Unique Id removed from update prompt

---

docs/integrations/llama-index.mdx

[llama_index_docs]: Added few blocks

---

docs/components/vectordbs/dbs/redis.mdx
docs/components/vectordbs/overview.mdx
docs/mint.json
mem0/configs/vector_stores/redis.py
mem0/utils/factory.py
mem0/vector_stores/configs.py
mem0/vector_stores/redis.py

Supports all functions except `create_col`.

[Redis]: Vector database added. 

---

docs/examples/llama-index-mem0.mdx
docs/examples/overview.mdx
docs/mint.json

Personalised agent using llama-index

[docs]: LlamaIndex ReAct agent tutorial added

---

docs/openapi.json
docs/platform/quickstart.mdx

Doc: show output_format as param in API reference and also change the example showing the current response while using both output_format as `v1.0` and `v1.1`.

Doc: show output_format as param in API reference

---

docs/features/langchain-tools.mdx
docs/mint.json

Added langchain tools for ADD, SEARCH, and GET_ALL

Added langchain tools in the docs

---

docs/integrations/vercel-ai-sdk.mdx
vercel-ai-sdk/README.md
vercel-ai-sdk/package.json
vercel-ai-sdk/src/index.ts
vercel-ai-sdk/src/mem0-chat-settings.ts
vercel-ai-sdk/src/mem0-utils.ts
vercel-ai-sdk/src/provider-response-provider.ts

(Update) Vercel AI SDK Memory Saving Algo

---

mem0/proxy/main.py
pyproject.toml

Openai proxy: allow system prompt from user and Version bump

Openai proxy: allow system prompt from user

---

docs/open-source/graph_memory/overview.mdx
mem0/graphs/tools.py
mem0/graphs/utils.py
mem0/memory/graph_memory.py
mem0/memory/main.py
mem0/memory/utils.py
tests/test_proxy.py

Flow of graph memory addtion:
1. Extracts all the entities/nodes and their types mentioned in the query. (Returns: dictionary of {nodes:type})
2. Eshtablish relations among the extracted nodes. (Input: list of nodes(that does not contains types). Returns: list of source -- relationship -- destination)
_(Note: The above 2 LLM calls are made to ensure that all the facts are retrieved from the query/data. The single LLM seems to be overloaded if we expect source (and their types) -- relationship -- destination (and their types))_
3. Search similar nodes and their respective inbound and outbound relations. 
4. LLM call to find what relationship we want to delete based on the query/data. (it returns the relations that we have to delete 
Now we have a list of entities (source -- relationship -- …

[graph_memory]: improve delete/add graph memory

---

mem0/client/main.py

Hi everyone, whenever I send a request to perform operations on a specific memory, such as `get`, `update`, or `delete`, I consistently encounter the following error:
```
{
"detail": "Invalid API key for this organization."
}
```
Upon investigation, I noticed that the request was missing some parameters. To address this, I added all the required parameters.
I test it in my local python environment.

fix request mem0 without org_id raise error

---

mem0/llms/configs.py
mem0/llms/gemini.py
mem0/memory/main.py
mem0/memory/utils.py

This PR's did the following:
- Fixed missing `gemini` in LLM's provider check.
- Handled case where model returns json in code block.
- Fixed Gemini model not working: removed unnecessary `noop`, updated function to parse function calls returning Gemini (based on their source code/docs).
All tested by my app working properly again.

Fix not working with Gemini models

---

docs/api-reference/memory/create-memory-export.mdx
docs/api-reference/memory/get-memory-export.mdx
docs/mint.json
docs/openapi.json
docs/platform/quickstart.mdx
mem0/client/main.py

Add support for a new API: MemoryExport. This helps in extracting memories into a structured format based on pydantic schema provided.

Add support: MemoryExport API

---

docs/api-reference/project/get-instructions-and-categories.mdx
docs/api-reference/project/update-instructions-and-categories.mdx
docs/features/custom-categories.mdx
docs/features/custom-instructions.mdx
docs/mint.json
docs/openapi.json
mem0/client/main.py

Changes:
- Updated the client to support APIs: Update and Get instructions/categories
- Updated the docs

Add support: Custom instruction/categories for projects

---

mem0/client/main.py
pyproject.toml

Fixes the issue: 
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[24], [line 10](vscode-notebook-cell:?execution_count=24&line=10)
[5](vscode-notebook-cell:?execution_count=24&line=5) print(mem0.__version__)
[8](vscode-notebook-cell:?execution_count=24&line=8) client = AsyncMemoryClient(api_key=API_KEY, org_id=ORG_ID, project_id=PROJECT_ID)
---> [10](vscode-notebook-cell:?execution_count=24&line=10) response = await client.update_project(custom_instructions="Test prompt")
[11](vscode-notebook-cell:?execution_count=24&line=11) print(response)
File ~/.pyenv/versions/3.12.8/lib/python3.12/site-packages/mem0/client/main.py:30, in api_error_handler.<locals>.wrapper(*args, …
```

Fix async client `update_project` method

---

mem0/vector_stores/elasticsearch.py
tests/vector_stores/test_elasticsearch.py

🚨 **URGENT**: This PR fixes critical Elasticsearch query errors that are currently affecting production vector searches.
The current implementation is causing search failures due to incorrect query structure and inefficient index settings. This PR provides essential fixes by:
1. Fixing KNN query structure that was causing search failures
2. Adding proper index settings (shards, replicas, refresh interval)
3. Restructuring mapping to use a more efficient schema
4. Optimizing KNN search with pre-filtering
5. Unifying metadata handling under a single field
6. Improving query performance with term-level filters
These changes will resolve the current search failures and make the vector store more reliable and scalable.
1. Changed field name from `embedding` to `vector`
2. Moved …

Fix/es query filter (🚨 URGENT)

---

mem0/vector_stores/azure_ai_search.py

This pull request fixes the issue where the AzureAISearch vector store does not correctly handle the user_id filter, causing updates intended for one user to overwrite another user's memory.
Fixes [#2170](https://github.com/mem0ai/mem0/issues/2170)
- Bug fix (non-breaking change which fixes an issue)
Ran the sample code provided in the issue to ensure that each user's memories are correctly added and retrieved without interference.
- Test Script (please provide)
```
m_alice = m.add("my name is Alice", user_id="Alice")
m_bob = m.add("my name is Bob", user_id="Bob")
print("m_alice: ", m_alice)
print("m_bob: ", m_bob)
time.sleep(10)
print("Final:")
pprint(m.get_all())
```

Fix query filter in azure ai search

---

embedchain/docs/examples/full_stack.mdx

Doc: Fix full stack link
Fixes #2182 

Doc: Fix full stack link

---

docs/features/advanced-retrieval.mdx
docs/features/enhanced-search.mdx
docs/mint.json

Added search params to improve retrieval

added enhanced search params

---

docs/components/embedders/config.mdx
docs/components/embedders/models/vertexai.mdx
mem0/configs/embeddings/base.py
mem0/embeddings/azure_openai.py
mem0/embeddings/base.py
mem0/embeddings/gemini.py
mem0/embeddings/huggingface.py
mem0/embeddings/ollama.py
mem0/embeddings/openai.py
mem0/embeddings/together.py
mem0/embeddings/vertexai.py
mem0/memory/main.py
tests/embeddings/test_vertexai_embeddings.py
tests/test_main.py

__Feature__  
The feature provides users with multiple options for embedding tasks in Vertex AI, and modifies `EmbeddingBase.embed` to include the memory action that triggered the function call.
__Motivation__  
Vertex AI offers multiple options for embedding tasks, allowing the extraction of text embeddings for specific use cases, such as distinguishing between a "retrieval document" and a "retrieval query."  
If this feature is added, it would give developers greater flexibility in using mem0 based on their needs.  
__Note__  
- To use the feature, need to specify the embedding task type in`mem0.configs.embeddings.base.BaseEmbedderConfig`. 
- I modified `mem0.embeddings.base.EmbeddingBase` structure and codes related to it
Fixes #2259 
Please …

Add config option for vertex embedding tasks

---

mem0/vector_stores/chroma.py
mem0/vector_stores/qdrant.py

Fixes the following issue when using chromadb with mem0 like this:
```python
import logging
logging.basicConfig(level=logging.ERROR, format='%(levelname)s - %(asctime)s - %(pathname)s - %(lineno)s - %(message)s')
config = {
"provider": "chroma",
"config": {
"collection_name": "test",
"path": "db",
}
}
}
memory = Memory.from_config(config_dict=config)
memory.add("Remember my name is Deshraj and I am avid traveler. I like to stay in airbnb and travel to new places preferably in mountains", user_id="deshraj")
existing_memories = memory.get_all(user_id="deshraj")
```
Error:
```
Traceback (most recent call last):
File "/Users/deshraj/Projects/test_v2.py", line 17, in <module>
memory = Memory.from_config(config_dict=config) …
```

[Bug Fix] Fix issue with chromadb not working with 0.6.0 and onwards

---

mem0/vector_stores/chroma.py

We don't need to check whether the collection already exists or not since we use the `client.get_or_create_collection()` which already takes care of this. 
Tested locally and it work fine.

[Misc] Clean up unnecessary checks in chromadb vector store integration

---

docs/features/memory-export.mdx

Added export_instructions parameter to Memory Export documentation. This optional parameter allows users to provide specific guidance on how memories should be processed and structured during export, enabling more customized and refined export results.

Added export instructions to docs

---

docs/components/vectordbs/dbs/elasticsearch.mdx
mem0/configs/vector_stores/elasticsearch.py
mem0/vector_stores/elasticsearch.py
tests/vector_stores/test_elasticsearch.py

The feature supports for custom search queries in elasticsearch vectorstore.   
__Motivation__  
Currently, VectorStore only supports vector-based search for retrieving memories. However, many VectorStore implementations offer additional search capabilities, such as keyword-based search or hybrid search. By allowing customizable search queries, developers can leverage these features to improve search performance and relevance.  
__Changes__  
- Add parameter `query_dict` to `mem0.Memory.search`, `Memory._add_to_vector_store` functions and `search` function of `VectorStoreBase` implementations
- for passing additional query, such as keyword.
- Add variable `custom_search_query`, which function returns custom es query,  to ElasticsearchConfig
- for  allowing custom search query on …

Support Custom Search Query for Elasticsearch

---

docs/components/vectordbs/dbs/azure_ai_search.mdx
mem0/vector_stores/azure_ai_search.py
poetry.lock
pyproject.toml

Fix azure ai vector store

---

mem0/llms/anthropic.py
mem0/llms/aws_bedrock.py
mem0/llms/azure_openai.py
mem0/llms/azure_openai_structured.py
mem0/llms/configs.py
mem0/llms/deepseek.py
mem0/llms/gemini.py
mem0/llms/groq.py
mem0/llms/litellm.py
mem0/llms/ollama.py
mem0/llms/openai.py
mem0/llms/openai_structured.py
mem0/llms/together.py
mem0/llms/xai.py
tests/llms/test_azure_openai.py
tests/llms/test_deepseek.py
tests/llms/test_gemini_llm.py
tests/llms/test_groq.py
tests/llms/test_litellm.py
tests/llms/test_openai.py
tests/llms/test_together.py

As removing `tools` from the LLMs was causing errors when using `graph_store`. Reverting them inorder to keep using the `graph_store` as an option with mem0.

Reverting the  `tools` commit

---

mem0/vector_stores/elasticsearch.py

The default search query in ElasticsearchDB has syntax error. This request fixes it.

URGENT Hotfix - update default Elasticsearch search query

---

docs/components/vectordbs/dbs/azure_ai_search.mdx
mem0/configs/vector_stores/azure_ai_search.py
mem0/configs/vector_stores/elasticsearch.py
mem0/configs/vector_stores/vertex_ai_vector_search.py
mem0/memory/main.py
mem0/vector_stores/azure_ai_search.py
mem0/vector_stores/base.py
mem0/vector_stores/chroma.py
mem0/vector_stores/elasticsearch.py
mem0/vector_stores/milvus.py
mem0/vector_stores/opensearch.py
mem0/vector_stores/pgvector.py
mem0/vector_stores/qdrant.py
mem0/vector_stores/redis.py
mem0/vector_stores/supabase.py
mem0/vector_stores/vertex_ai_vector_search.py
mem0/vector_stores/weaviate.py
tests/vector_stores/test_chroma.py
tests/vector_stores/test_elasticsearch.py
tests/vector_stores/test_opensearch.py
tests/vector_stores/test_qdrant.py
tests/vector_stores/test_supabase.py
tests/vector_stores/test_vertex_ai_vector_search.py
tests/vector_stores/test_weaviate.py

Changes:
- Support for hybrid search in Azure AI vector store
- Update `search` methodt to include `vectors` param and change the funtionality of `query` param

Support for hybrid search in Azure AI vector store

---

docs/components/vectordbs/dbs/pinecone.mdx
mem0/vector_stores/pinecone.py

fix pinecone

---

docs/components/llms/config.mdx
embedchain/embedchain/embedder/openai.py
embedchain/embedchain/llm/openai.py
mem0/embeddings/openai.py
mem0/llms/openai.py

Adds the official environment variable support for base URL key of openai - `OPENAI_BASE_URL`
[This](https://github.com/openai/openai-python/blob/9dea82fb8cdd06683f9e8033b54cff219789af7f/src/openai/_client.py#L130) 
Fixes #2356 
Mem0 -->
```
import os
os.environ["OPENAI_API_KEY"] = ""
os.environ["OPENAI_BASE_URL"] = 'https://api.openai.com/v1'
config_openai = {
"llm": {
"provider": "openai",
"config": {
"model": "gpt-4o",
"temperature": 0.2,
"max_tokens": 1500,
}
},
"embedder": {
"provider": "openai",
"config": {
"model": "text-embedding-3-large"
}
},
"version": "v1.1"
}
def main():
m = Memory.from_config(config_openai)
result = m.add("I am working on improving my tennis skills. Suggest some online courses.", user_id="alice", metadata={"category": "hobbies"}) …
```

Open AI env var fix

---

mem0/memory/graph_memory.py

When passing big prompts or history of conversations, sometimes, tools_calls response for extract_entities is an array. This fixes generating a big graph for given history of chat interactions between user & assistant.
Memories add request that some times fails:
```
{
"messages": [
{"role": "user", "content": "I started yoga classes yesterday."},
{"role": "assistant", "content": "That's wonderful, Sarah! How did you feel after your first yoga session?"},
{"role": "user", "content": "It was relaxing, but a bit challenging."},
{"role": "assistant", "content": "I'll remember that yoga was relaxing yet challenging for you, Sarah. Consistency will make it easier with time."},
{"role": "user", "content": "I'm feeling anxious about my presentation next week."},
{"role": "assistant", "content": …
```

fix: extract entities tool_calls some times is an array 

---

embedchain/docs/api-reference/advanced/configuration.mdx

Update embedchain docs page: `/api-reference/advanced/configuration`
* Add the missing `memory` section in config samples (yaml, py, and json).
* Also, remove commas after the last elements in the JSON config sample. Regular JSON does not support trailing commas.
- Run `mintlify dev` and navigate to `/api-reference/advanced/configuration`.
- To verify JSON formatting, copy the config sample into a separate file and check for errors in the editor.

Doc: add "memory" in EC "Custom config" section and fix typos in the json config sample

---

mem0/memory/main.py
pyproject.toml

Change the collection from `mem0-migrations` to `mem0migrations` in order to avoid error while creating collections. And version bump -> 0.1.95
Fixes #2577 #2589

Fix mem0-migrations issue

---

docs/changelog.mdx
docs/integrations/vercel-ai-sdk.mdx
vercel-ai-sdk/package.json
vercel-ai-sdk/src/mem0-generic-language-model.ts
vercel-ai-sdk/src/mem0-types.ts
vercel-ai-sdk/src/mem0-utils.ts

This PR adds support for Graph Memory in the Mem0 AI SDK.
Changes:
- Added support for Graph Memory in the Mem0 AI SDK.
- Added support for standalone functions.
- Added support for `enable_graph` in the `mem0Config` object.
- Added support for `enable_graph` in the standalone functions.
Any Major Changes:
- In `getMemories`, the return type is now an object with two keys: `results` and `relations`, if `enable_graph` is set to `true`. Otherwise, it will return an array of objects.

Vercel AI SDK / Graph Memory

---

docs/platform/quickstart.mdx

This PR updates the existing documentation section on long-term memory for both users and agents. 
The revisions provide clearer explanations of how the dual-tagging mechanism works when both user_id and agent_id are provided in API calls.

Update Documentation: Clarify Dual-Identity Memory Management

---

mem0/memory/main.py

I figured out that the async memory system shares same metadata object between all create memory actions.  
I guess this is the reason of the issue 2578. 
In AsyncMemory, `_add_to_vector_store` method gets parameter named `metadata`, 
and exact same metadata object is passed to `_create_memory` method which modifies the metadata object and do async await.  
This causes modification on metadata(because all `_create_memory` references on same metadata object) before finishing asyncio job, if the method is called multiple times from `_add_to_vector_store` method.  
I tested my code in local, and it solved the problem(duplicating last metadata for all memories).  
I also added deepcopy to sync memory mechanism for making sure that the system separates metadata between memories.  
Fixes #2578 …

Fix duplicated metadata issue while adding or updating memories

---

mem0/memory/graph_memory.py

On the very first memory addition we get a lot of warnings, which might confuse the user:
Additionally, since you never use the schema, we don't have to fetch it (faster init times)

remove warnings and refresh schema from neo4j

---

mem0/memory/graph_memory.py
mem0/memory/memgraph_memory.py

Updated node type assignment: nodes without a specified type are now renamed to "__User__" instead of being set to 'Unknown'."

Renamed unknown node type

---

mem0/memory/graph_memory.py
mem0/memory/utils.py

Counting the number of times a node or relationship was mention allows us for richer downstream analysis or reranking when retrieving info

Add weights to Neo4j model

---

docs/platform/quickstart.mdx

This PR updates the Mem0 Platform documentation to clarify how memory attribution works when using user_id and agent_id parameters.
Changes:
1. Clarified that with user_id, only messages with "role": "user" are stored
2. Clarified that with agent_id, only messages with "role": "assistant" are stored
3. Added explanation that role-based separation prevents memories of one role from influencing another role

Improve documentation on role-based memory attribution rules

---

docs/api-reference/memory/v2-get-memories.mdx
docs/api-reference/memory/v2-search-memories.mdx
docs/platform/quickstart.mdx

Doc: Add NOT filter for Search and GetAll V2

Doc: Add NOT filter for Search and GetAll V2

---

openmemory/api/app/utils/categorization.py

The Categorisation call utilised Responses API of openAI, migrated to Chat Completions due to default openAI API key support. This is to decrease the number of error request generated because of unconfigured key. 
This update will lead to increase the speed of responses on openMCP Server .

Update Categorisation Flow

---

docs/openapi.json

Updated the OpenAPI documentation to reflect the current `client.update()` method signature that supports both `text` and `metadata` parameters.
- **Python SDK example**: Updated from `client.update(memory_id, message)` to `client.update(memory_id=memory_id, text="...", metadata={...})`
- **JavaScript SDK example**: Updated to use object parameter with `text` and `metadata` properties
- **cURL example**: Added `metadata` field to request body JSON
- **Go example**: Updated payload to include both `text` and `metadata` fields
- **PHP example**: Updated JSON payload to include both parameters using proper PHP array syntax
- **Java example**: Updated request body to include both `text` and `metadata` fields
The `client.update()` method now accepts:
- `memory_id` (required): The ID of the …

Update client.update() method documentation in OpenAPI specification

---

mem0/vector_stores/opensearch.py

Minor issue - Opensearch shows creation warning on every mem0 call. 
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] My code follows the style guidelines of this project
- [x ] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [x ] I have made corresponding changes to the documentation
- [x ] My changes generate no new warnings
- [x ] I have added tests that prove my fix is effective or that my feature works
- [x ] New and …

fix(opensearch): update logger warning

---

docs/changelog.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.types.ts
mem0-ts/src/client/telemetry.ts

Introduced an `immutable` parameter to the `add` method in the client by updating the MemoryOptions interface. Updated documentation and bumped the package version to 2.1.33.

Add immutable param to add method and bump version

---

mem0/embeddings/aws_bedrock.py
mem0/llms/aws_bedrock.py

This commit:
1. Removes the invalid `extract_json` from aws_bedrock embeddings and llm, added in #3013 
2. It adds support for temporary credentials (`AWS_SESSION_TOKEN`). 
3. It updates the tool parsing to properly support graph memory, where previously the `_convert_tool_format` previously dropped nested JSON Schema tool properties and parameters.
```python
import boto3
import os
from .settings import config
from mem0.configs.base import GraphStoreConfig, MemoryConfig, VectorStoreConfig
from …
```

fix: bedrock llm, embeddings, tools, temporary creds

---

docs/components/vectordbs/dbs/mongodb.mdx
mem0/configs/vector_stores/mongodb.py
mem0/utils/factory.py
mem0/vector_stores/mongodb.py
tests/vector_stores/test_mongodb.py

- Fixed MongoDBs string in the vector store factory to match the name of the class. 
- Removed check_auth_and_connection in mongoDB config as its not needed anymore. 
- Added mongo_uri to the mongoDBConfig to replace the host, port, password, and user to match the mongoVector class. This also simplifies the logic and allows users to connect with just the mongo URI. 
- Updated to use pydantic V2 syntax on mongos validation. 
- Updated the test_mongo.py to match the new structure. 
- Fixed the search index model to use dimensions instead of d.

MongoDB Vector Store misaligned strings and classes

---

mem0/llms/vllm.py

This PR adds the missing `import openai` statement in the `vllm.py` file. The absence of this import was causing runtime issues when using vLLM, as noted in [Issue #3057]
Fixes   #3057
- [x ] Bug fix (non-breaking change which fixes an issue)
This is a minor fix (missing import). No tests were run, but the fix aligns with the usage context and should resolve the import error mentioned in Issue #3057.
Please feel free to run tests or suggest improvements if necessary.
Not tested – minor import fix only.
- [x ] closes #xxxx (Replace xxxx with the GitHub issue number)

Fix: Add missing OpenAI import in vLLM module

---

docs/changelog.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.types.ts
mem0-ts/src/client/telemetry.ts

Introduces the structured_data_schema parameter to the MemoryOptions interface in the TypeScript client, allowing users to specify a schema for structured data. Changelog updated to reflect this new feature.

Add structured_data_schema to MemoryOptions interface

---

mem0/memory/memgraph_memory.py

When I initialize Memory, I get an error message saying that the index is created repeatedly
```
File "/home/ubuntu/pyproject/.venv/lib/python3.12/site-packages/mem0/memory/main.py", line 146, in __init__
self.graph = MemoryGraph(self.config)
^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ubuntu/pyproject/.venv/lib/python3.12/site-packages/mem0/memory/memgraph_memory.py", line 58, in __init__
self.graph.query(create_vector_index_query, params={})
File "/home/ubuntu/pyproject/.venv/lib/python3.12/site-packages/memgraph_toolbox/api/memgraph.py", line 111, in query
json_data = [r.data() for r in data]
^^^^
File "/home/ubuntu/pyproject/.venv/lib/python3.12/site-packages/neo4j/_sync/work/result.py", line 398, in __iter__
self._connection.fetch_message()
File …
```

fix: Ignore memgraph index duplicate creation errors

---

mem0/vector_stores/chroma.py
mem0/vector_stores/langchain.py
mem0/vector_stores/mongodb.py
mem0/vector_stores/qdrant.py
tests/vector_stores/test_chroma.py
tests/vector_stores/test_langchain_vector_store.py
tests/vector_stores/test_mongodb.py
tests/vector_stores/test_qdrant.py

This PR fixes the support for the multi id filters for all the vectorstores, also added tests with filters for vector stores.
Fixes #3260 

Added mulit id filters support for all vectorstores

---

docs/examples/ai_companion.mdx
docs/examples/llamaindex-multiagent-learning-system.mdx
docs/examples/memory-guided-content-writing.mdx
docs/examples/openai-inbuilt-tools.mdx
docs/examples/personal-travel-assistant.mdx
docs/integrations/agentops.mdx
docs/integrations/agno.mdx
docs/integrations/autogen.mdx
docs/integrations/elevenlabs.mdx
docs/integrations/google-ai-adk.mdx
docs/integrations/langchain.mdx
docs/integrations/langgraph.mdx
docs/integrations/livekit.mdx
docs/integrations/multion.mdx
docs/integrations/openai-agents-sdk.mdx

Fix #3207 
This PR fixes incorrect handling of the search method's return value structure in documentation examples across `docs/integrations/` and `docs/examples/` directories. The search method returns `{"results": [...]}` but many
examples were accessing results directly or using incorrect field names, causing runtime errors when users follow these examples.
Fixes #(issue number - to be filled when issue is created)
1. **Wrong field access**: `mem['text']` → `mem['memory']`
2. **Direct iteration**: `for mem in memories` → `for mem in memories.get('results', [])`
3. **Wrong root field**: `memories['memories']` → `memories.get('results', [])`
4. **Missing safety**: Added proper null checks and safe field access
**docs/integrations/ (10 files):**
- `multion.mdx` - Fixed field name and …

docs: fix search method return value handling in integration and example docs

---

docs/open-source/graph_memory/overview.mdx

This is a proposed fix to add the missing mention of `Neptune Analytics` on the heading paragraph for graph memory page. 
Fixes # https://github.com/mem0ai/mem0/issues/3263

DOC: Fix missing Neptune Analytics mention on doc

---

mem0/memory/main.py

Added missing else condition to fix an UnboundLocalError 
Bug: In the AsyncMemory._add_to_vector_store method (line
1203-1222), there's an UnboundLocalError when no new facts are
retrieved from the input. The variable new_memories_with_actions is
only defined inside the if new_retrieved_facts: block but is referenced
outside of it at line 1222.
Fix: Added else: new_memories_with_actions = {} to handle the case
when new_retrieved_facts is empty.
Error:
UnboundLocalError: cannot access local variable
'new_memories_with_actions' before assignment
This was causing memory processing to fail completely when the LLM
determined there were no new memorable facts to extract from
conversations
Fixes # (issue): N/A, didn't create an issue yet
None, I don't …

AsyncMemory._add_to_vector_store bugfix when no facts found

---

Makefile
docs/open-source/graph_memory/overview.mdx
examples/graph-db-demo/kuzu-example.ipynb
mem0/__init__.py
mem0/graphs/configs.py
mem0/memory/kuzu_memory.py
mem0/utils/factory.py
pyproject.toml
tests/memory/test_kuzu.py

Hi! This PR adds [Kuzu](https://github.com/kuzudb/kuzu) as an option for the graph memory backend.
Kuzu is an embeddable in-process graph database, which means there is no server to setup. Kuzu just needs a path to a directory for data persistence, but can also run completely in memory, as is the default in this PR.
Reopening this PR as I inadvertently closed the earlier one: https://github.com/mem0ai/mem0/pull/2873

Add support for graph memory using Kuzu

---

mem0/embeddings/ollama.py

Fix function `_ensure_model_exists` when checking model name from model list cause the object parsed from api /api/tags from base url of ollama may not have attribute "name". I added attribute "model"
Keep passing test cases

Fix: Ollama checking model exists

---

openmemory/backup-scripts/export_openmemory.sh

Add export_openmemory.sh migration script

---

mem0/configs/llms/openai.py
mem0/llms/openai.py
tests/llms/test_openai.py

Adds support for an additional parameter `store` in the llm config.
(Not a crucial parameter though as it seem to affect the user in anyway. See [this](https://platform.openai.com/docs/api-reference/responses/create#responses_create-store).)
Fixes #3306 
Locally tested if `store` is being correcly passed to `.generate_response` of `OpenAILLM` and it succeeds.

support `store` for openai

---

mem0/client/project.py
mem0/configs/vector_stores/azure_ai_search.py
mem0/configs/vector_stores/baidu.py
mem0/configs/vector_stores/chroma.py
mem0/configs/vector_stores/databricks.py
mem0/configs/vector_stores/faiss.py
mem0/configs/vector_stores/langchain.py
mem0/configs/vector_stores/milvus.py
mem0/configs/vector_stores/pinecone.py
mem0/configs/vector_stores/qdrant.py
mem0/configs/vector_stores/redis.py
mem0/configs/vector_stores/s3_vectors.py
mem0/configs/vector_stores/upstash_vector.py
mem0/configs/vector_stores/vertex_ai_vector_search.py
mem0/configs/vector_stores/weaviate.py
openmemory/api/app/schemas.py

This updates the `openmemory.api.app.schemas.Memory` and `mem0.client.project.ProjectConfig` pydantic classes to use the modern `ConfigDict` style rather than `class Config:`.
Fixes #3408 
**Before**
```sh
?> uv run python -Wd -c "import mem0"
warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)
```
**After**
```sh
?> uv run python -Wd -c "import mem0"
```
**NOTE**: Since this is a small patch, I didn't get the full dev environment off the ground (I'm not normally a `hatch` user). If CI fails, I'm happy to put in the extra minutes to get it clean locally.

fix: Use ConfigDict instead of class-based Config

---

mem0-ts/src/oss/src/memory/graph_memory.ts

TS OSS Client Graph Memory is hardcoded to OpenAI. This should be replaced with the provider from llm config
Fixes https://github.com/mem0ai/mem0/issues/2872
Have tested locally by adding a memory

fix: :bug: replace hardcoded llm provider with provider from config

---

docs/components/vectordbs/dbs/s3_vectors.mdx
mem0/configs/vector_stores/s3_vectors.py
mem0/vector_stores/s3_vectors.py
tests/vector_stores/test_s3_vectors.py

Support for S3 Vectors was provided in v0.1.117. However, upon testing, it was found that initializing `Memory` via config with `S3VectorConfig` throws an `AttributeError`. Upon further investigation, turns out that `S3VectorConfig` contains the `index_name` attribute, while initializing `Memory` with config requires the `collection_name` attribute to be present in the config object.
This fix uses the `collection_name` attribute name to store the index name to be used within the S3 vector bucket. This aligns with the uniformity provided across other vector stores and their interaction with the `Memory` class.
- leveraged the existing `tests/vector_stores/test_s3_vectors.py` file
- added a test `test_memory_initialization_with_config` to ensure an `AttributeException` exception is not …

Fixed s3 vectors memory initialization issue from configuration

---

docs/docs.json
docs/examples/email_processing.mdx
docs/examples/mem0-agentic-tool.mdx
docs/examples/mem0-google-adk-healthcare-assistant.mdx
docs/examples/personalized-search-tavily-mem0.mdx
docs/integrations/agno.mdx
docs/integrations/autogen.mdx
docs/integrations/google-ai-adk.mdx
docs/integrations/langchain.mdx
docs/integrations/langgraph.mdx
docs/platform/features/direct-import.mdx
examples/mem0-demo/app/api/chat/route.ts
examples/misc/fitness_checker.py
examples/misc/multillm_memory.py
examples/misc/personal_assistant_agno.py
examples/misc/personalized_search.py
mem0/llms/ollama.py

Refactor documentation for v2 and updated examples for 1.0.0beta

refactor: v2 search and update examples

---

pyproject.toml

Support OpenAI 2.x dependency by removing upper version constraint.
Closes #3529
- Updated `pyproject.toml` to remove `<1.110.0` constraint
- Allows OpenAI 2.x while maintaining backward compatibility
- Bug fix (non-breaking change which fixes an issue)
- No code changes required (APIs are stable)
- Verified existing functionality remains intact
- All OpenAI tests pass (7/7) with OpenAI 2.1.0 
- All embedding tests pass (5/5) with OpenAI 2.1.0
- No breaking changes detected
- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- New and existing unit tests pass locally with my changes
- …

support dependency openai 2.x
