mem0ai/mem0

setup.py

- refactor vector db creation so that anyone can use custom vector db and db directory if needed
- skip creating embedding for a dataset for which embedding already exists.

Bump version to 0.0.7

---

embedchain/utils.py

Regex is hard to read, so I added some chatgpt generated documentation to know what's going on.

docs: clean_string function documentation

---

setup.py

- add support for local docs, like question answer pair
- refactor query endpoint to have 3 functions, making it modular
- add doc string for clean string

Bump version to v0.0.8

---

setup.py

- add missing __init__ file in vectordb, making it importable

Bump version to 0.0.9

---

README.md
embedchain/chunkers/text.py
embedchain/embedchain.py
embedchain/loaders/local_text.py

also related to #37, this PR adds support for any local text that you want to add to the database.
I set the chunk size at 1000, comparable to a PDF. But thinking about it, I guess PDFs are somewhere between chapters and books, and texts tend to be the length of a paragraph or multiple paragraphs. So I'm open to change that, as I was for #31.

feat: add local text

---

setup.py

- Add support for `text` data_type in `add_local`
- Fix typos in Readme

Bump version to 0.0.10

---

README.md

Just a tiny fix, for a spelling mistake I noticed during reading the README.

fix: Spelling mistake

---

setup.py

Bump version to 0.0.11

---

.gitignore
README.md
embedchain/loaders/pdf_file.py

Added embedchainjs to README and fixed PYPI link

added embedchainjs to repo

---

embedchain/__init__.py
embedchain/embedchain.py
embedchain/vectordb/chroma_db.py
setup.py

- Add support for [gpt4all](https://gpt4all.io/) as open source LLM
- Add support for Sentence tranformers: all-MiniLM-L6-v2 as open source embedding model.
Addresses Issues https://github.com/embedchain/embedchain/issues/132

Open source embedding and LLM models

---

README.md

This commit updates the readme to introduce a new
app type called OpenSourceApp. It uses gpt4all as
the LLM and sentence transformers as the embedding model. Both models are open source and usage is free.

update: readme to introduce open source app

---

setup.py

- Add OpenSourceApp, uses open source embedding model and LLM. Both are free to use.
- Add support for api_key in OpenAI api call
- Update readme to show how to reuse vector db

Bump version to 0.0.12

---

embedchain/embedchain.py
embedchain/vectordb/chroma_db.py

This commit fixes the dependency of initializing OpenAI env variables for OpenSourceApp.
Fixes https://github.com/embedchain/embedchain/issues/143

bug: Fix dependency of openai env variables for OpenSourceApp

---

setup.py

- fix dependency of using OpenAI env variables in OpenSourceApp

Bump version to 0.0.13

---

README.md
embedchain/embedchain.py

added dry run functionality I described before, the code comments should be enough to explain the purpose and thought behind it.

feat: add dry run

---

setup.py

- Add support for dry run
- Import gpt4all locally

Bump version to 0.0.14

---

README.md
embedchain/embedchain.py

This commit introduces a new endpoint called chat. It maintains the context of the last 5 user messages and continues to do a semantic search to find the context.
Addresses https://github.com/embedchain/embedchain/issues/102

feat: Add support for chat endpoint

---

setup.py

- release a new endpoint called "chat". It preserves 5 last user messages by default.

Bump version to 0.0.15

---

README.md
embedchain/chunkers/doc_file.py
embedchain/chunkers/pdf_file.py
embedchain/embedchain.py
embedchain/loaders/doc_file.py
setup.py

doc support added

---

README.md
embedchain/config/AddConfig.py
embedchain/config/BaseConfig.py
embedchain/config/ChatConfig.py
embedchain/config/InitConfig.py
embedchain/config/QueryConfig.py
embedchain/config/__init__.py
embedchain/embedchain.py

This PR introduces config classes for easier configuration. In accordance with #156 
This is just to lay the framework. It does not actually introduce new config options, you might even say that the config options this far are pretty bad. But we have plenty of other PRs waiting to do that.

refactor: config

---

README.md
embedchain/embedchain.py

Counts the number of embeddings (chunks) in the database.

feat: count

---

embedchain/config/InitConfig.py
embedchain/embedchain.py
embedchain/utils.py

- remove redundant tab/space
- ~~reuse ef declaration~~

[refactor] syntax cleanup

---

setup.py

- Releasing everything mentioned here: https://github.com/embedchain/embedchain/issues/176

Bump version to 0.0.16

---

README.md
embedchain/config/QueryConfig.py
embedchain/embedchain.py

Resolves: #170 
Changelog:
- Adds `template` as an attribute of `QueryConfig`
- Adds validation to custom `template`
- Adds `template` as an argument to `generate_prompt`

[Feat] Add config based template to query function

---

embedchain/__init__.py
embedchain/config/QueryConfig.py
embedchain/embedchain.py

This commit introduces a new bot type called Person. It behaves and speaks like a particular Person.
For this two app types: PersonApp and PersonOpenSourceApp

feat: Add person bot

---

setup.py

Release following PRs
- https://github.com/embedchain/embedchain/pull/92/
- https://github.com/embedchain/embedchain/pull/160/
-

Bump version to 0.0.18

---

README.md
embedchain/embedchain.py

[docs] Add example for custom prompt Template to README

---

README.md
embedchain/config/InitConfig.py
embedchain/embedchain.py

Add logging. This makes it easier to iterate on your bot, see how the embedding behaves and improve it.

feat: add logging

---

setup.py

chore: pin version number for pydantic and chroma

---

embedchain/config/ChatConfig.py
embedchain/config/QueryConfig.py
embedchain/embedchain.py

linting and formatting according to the enforced guidelines

chore: linting

---

embedchain/config/InitConfig.py

App throws error even if api key is passed

---

README.md
embedchain/config/InitConfig.py

docs: chroma client documentation

---

embedchain/embedchain.py

Changes Made:
- Added optional `metadata` parameter to the `add` and `add_local` methods in the `EmbedChain` class.
- Modified the `load_and_embed` method to include the `metadata` parameter when adding documents.
- Updated the `_format_result` method to include metadata in the formatted results.
- If there are any mistakes, please correct this is my first commitment to opensource contribution

Add metadata support to added data sources

---

README.md
embedchain/chunkers/base_chunker.py
embedchain/chunkers/code_docs_page.py
embedchain/config/QueryConfig.py
embedchain/data_formatter/data_formatter.py
embedchain/embedchain.py
embedchain/loaders/code_docs_page.py

This commit introduces a new data type called code_docs_loader.
It is useful for creating qna and chat applications on open source and developer docs project.

feat: Add new data type: code_docs_loader

---

README.md

Updated README.md file for metadata @cachho

Updated README.md file for metadata

---

embedchain/loaders/web_page.py

New features:
1. exclude by id
2. exclude by class
3. logging
Chores:
1. Added ids, classes and tags I found in some blogs
2. a bunch of refactors
With this I reached reductions up to 90%, granted, the majority of this was already done, it was at 75% before. (edit: switched mode of comparison, now the savings can't be this great.)
This will also help with #272

feat: webpage - exclude by class and id, add logging

---

.github/workflows/ci.yml
Makefile
embedchain/__init__.py
embedchain/config/InitConfig.py
embedchain/embedchain.py
embedchain/vectordb/chroma_db.py
setup.py

Ran linting on the codebase to make sure that CI passes.

chores: run lint and format

---

embedchain/embedchain.py

This commit adds support to browse search results and get results from there. It uses duckduckgo api for browsing.
Add browse the internet capability in a bot. This can be turned by `app.online = True`. When turned on, the bot can browse duck duck go search results, get an answer and append it to the content.

feat: Add browse the internet or online functionality.

---

embedchain/embedchain.py

Fix: PersonApp and PersonOpenSourceApp would give errors when using the chat function

fix: template for personapp

---

notebooks/embedchain-docs-site-example.ipynb

As the title suggest. Seems like my previous PR didn't add the saved notebook.

example: fix notebook for docs site loader

---

docs/advanced/configuration.mdx
docs/advanced/query_configuration.mdx
embedchain/apps/OpenSourceApp.py
notebooks/embedchain-chromadb-server.ipynb

docs: app config instead of init config

---

embedchain/__init__.py
embedchain/apps/CustomApp.py
embedchain/apps/OpenSourceApp.py
embedchain/apps/PersonApp.py
embedchain/config/apps/CustomAppConfig.py
embedchain/config/apps/OpenSourceAppConfig.py
embedchain/embedchain.py
pyproject.toml

Sorry for the confusion and that I merged unlinted stuff. The problem was #315. It looked like there were no errors when the linter just didn't work.
I did all the linting and formating in this PR.

fix: format lint

---

docs/advanced/query_configuration.mdx

Explains how to use AddConfig, because the fact that you pass other config objects to it is  quite unique.

docs: explain `AddConfig`

---

embedchain/vectordb/chroma_db.py
pyproject.toml
tests/vectordb/test_chroma_db.py

Upgrade Chroma v0.4.0: https://www.trychroma.com/blog/chroma_0.4.0
Migration: https://docs.trychroma.com/migration

update: chroma v0.4.0

---

embedchain/embedchain.py

fix: init metadata as empty

---

docs/advanced/configuration.mdx

fixes an issue with the template, it's not using named arguments. 
Fixes an issue reported on discord.

docs: fix template

---

docs/quickstart.mdx
embedchain/apps/PersonApp.py

Fix for PersonApp not working with config
Fixes #367 
```
from embedchain import PersonOpenSourceApp
from embedchain.config import QueryConfig
from string import Template
app = PersonOpenSourceApp("Winston Churchill")
app.add("youtube_video", "https://youtu.be/ilIefxbSJT8")
print(app.query("What is Oppenheimer about?", dry_run=True, config=QueryConfig(stream=False, template=Template("""
Use the context to answer the query in a sarcastic tone.
$context
Query: $query
Helpful Answer:
"""))))
```

fix for personapp not working with config

---

embedchain/embedchain.py
embedchain/loaders/base_loader.py
embedchain/loaders/docs_site_loader.py
embedchain/loaders/docx_file.py
embedchain/loaders/local_qna_pair.py
embedchain/loaders/local_text.py
embedchain/loaders/pdf_file.py
embedchain/loaders/sitemap.py
embedchain/loaders/web_page.py
embedchain/loaders/youtube_video.py

* add BaseLoader class
* typing in `embedchain.py`
- [] I have added tests that prove my fix is effective or that my feature works

refactor: loader chunker typing

---

docs/advanced/app_types.mdx
embedchain/apps/CustomApp.py
embedchain/models/Providers.py
tests/vectordb/test_chroma_db.py

Add support for the Azure OpenAI model which was requested by some folks in the community. 
Haven't been able to test but it should work since the change is easy one.
```python
from embedchain import CustomApp
from embedchain.config import CustomAppConfig
from embedchain.models import Providers, EmbeddingFunctions
config = CustomAppConfig(embedding_fn=EmbeddingFunctions.OPENAI, provider=Providers.AZURE_OPENAI)
satya_nadela_bot = CustomApp(config)
satya_nadela_bot.add("web_page", "https://en.wikipedia.org/wiki/Satya_Nadella")
satya_nadela_bot.query("What is the date of birth of Satya Nadella?")
```

[Feature]: Add support for azure openai model

---

embedchain/apps/CustomApp.py

fix: remove debug logging that accidentally remained in code.
Fixes # None

fix: remove debug logging

---

docs/advanced/showcase.mdx

update: docs showcase

---

embedchain/utils.py

For some reason, when you use logging in utils, it destroys the logger.
After this long debugging process,  I wanted to add a unit test but this doesn't seem to work since pytest internally sets the loglevel. So I didn't manage to figure this out.
> Your issue seems to be related to the way pytest handles loggers compared to a typical python runtime environment.
> When you are running pytest, it modifies the behavior of the root logger (and potentially other loggers as well) to fit its own configuration, which by default doesn't include DEBUG-level logging.
Fixes #376 
Please …

fix: no logging in pysqlite replacement

---

embedchain/utils.py

Zero divisions can always happen, so it's better to escape them.

fix: is readable - zero division error

---

tests/chunkers/test_text.py

added chunker unit tests
Regards #306

test: added chunker unit tests

---

embedchain/utils.py

escape pysqlite swapping
Fixes discord issue

fix: escape pysqlite swapping

---

embedchain/data_formatter/data_formatter.py

* if a user doesn't want to use notion, current setup still requires user to install the notion loader.
* this PR lazy loads the notion loader and fixes the above.

Fix: lazy load Notion loader

---

docs/examples/api_server.mdx
docs/mint.json
embedchain/config/apps/CustomAppConfig.py
embedchain/data_formatter/data_formatter.py
embedchain/utils.py
examples/api_server/.dockerignore
examples/api_server/.gitignore
examples/api_server/Dockerfile
examples/api_server/api_server.py
examples/api_server/docker-compose.yml
examples/api_server/requirements.txt
examples/api_server/variables.env
tests/vectordb/test_chroma_db.py

Added the API server example along with the instructions in documentation.
Tested the program locally. Added docker-compose to run the server using docker.

add: api server

---

embedchain/loaders/notion.py

fixes suggested command in notion install error message to use new extra dependency name.

fix: notion install error message

---

embedchain/embedchain.py

feat: session id for telemetry

---

embedchain/embedchain.py

Adds telemetry to add local 
Fixes #423 

fix: add telemetry to add_local

---

README.md

Added development and documentation guides to readme.
Fixes #445
Yes

Add guide links to readme

---

docs/advanced/configuration.mdx
docs/advanced/query_configuration.mdx
embedchain/apps/App.py
embedchain/apps/CustomApp.py
embedchain/apps/Llama2App.py
embedchain/apps/OpenSourceApp.py
embedchain/config/ChatConfig.py
embedchain/config/QueryConfig.py
tests/embedchain/test_query.py

Allow passing of a system prompt.
Fixes #443 

feat: system prompt

---

.github/ISSUE_TEMPLATE/feature_request.yml

Issue creation should be easy but at the same
time it should have as much structured info as
possible.
Alternative and additional context was rarely used.

Github: Improve issue template.

---

.github/ISSUE_TEMPLATE/documentation_issue.yml

Added Github issue template for documentation
Fixes #457 

Create documentation_issue.yml as Github Issue Template for documentation

---

.github/workflows/cd.yml

fix: python version string

---

embedchain/embedchain.py

If someone creates multiple bots in the same process, then both the bots share the same history due to global variable that we use right now for maintaining memory. Adding the change to make sure that memory is part of the App instantiated rather than using global variable.
See the code below:
```python
```python
In [1]: from embedchain import App
...: from embedchain.config import AppConfig
...: 
...: app_config1 = AppConfig(collection_name="app1")
...: app_config2 = AppConfig(collection_name="app2")
...: 
...: app1 = App(config=app_config1)
...: app2 = App(config=app_config2)
...: 
In [2]: 
In [2]: app1
Out[2]: <embedchain.apps.App.App at 0x127460790>
In [3]: app1.memory
Out[3]: ConversationBufferMemory(chat_memory=ChatMessageHistory(messages= …

[bug-fix] fix issue related to bot memory when using multiple bots at the same time

---

pyproject.toml

Forgot to update the version previously. Updating it here.

Update package version to 0.0.49

---

README.md

Used [Contributors Rock](https://contrib.rocks/preview?repo=angular%2Fangular-ja) to add contributor graphic to the readme
Fixes # (485)
https://github.com/embedchain/embedchain/issues/485
Checked readme locally and in github after push

added contribution img to readme using contrib.rocks embedding

---

embedchain/vectordb/chroma_db.py
pyproject.toml
tests/vectordb/test_chroma_db.py

Bump up LangChain version to the latest and bugfixed a unit test
Fixes #533
N/A

Bump up LangChain version and bugfix

---

docs/advanced/app_types.mdx
docs/advanced/data_types.mdx
docs/advanced/interface_types.mdx
docs/advanced/vector_database.mdx

docs: fix typos

---

embedchain/embedder/base_embedder.py
embedchain/vectordb/elasticsearch_db.py

Fixes numerous issues with wrongly assigned class attributes for elastic search.
Brought up in #498 

fix: Elasticsearch - use correct class attributes

---

pyproject.toml

Add `flask` and `twilio` to extras as similar to other bots requriments.
Fixes #483 

Add flask and twilio to extras

---

tests/embedchain/test_embedchain.py

fix failing tests by not mocking `get`.

fix: do not mock get

---

embedchain/llm/base.py
embedchain/loaders/mdx.py

Fixes lint issues which is blocking the new package version release.

[chore] fix lint issues

---

embedchain/embedchain.py
embedchain/loaders/local_qna_pair.py
embedchain/models/data_type.py
tests/models/test_data_type.py

* categorizes data types into `DirectDataType`, `IndirectDataType` or `SpecialDataType`
* direct data type does not check to update existing embeddings
* indirect data types uses the existing embedding manager
* special data type has custom logic
* added custom logic for `qna_pair`, where the answer is updated if the question remains the same.
* added inline comments and docstrings
Fixes #611 
```python
from embedchain.config import AppConfig, ChromaDbConfig
app = App(config=AppConfig(log_level="WARNING"), …
```

fix: url metadata for all datatypes

---

README.md

Fix a typo
README update for a minor typo.
N/A
N/A

Fix a typo - accpeting -> accepting

---

README.md
docs/quickstart.mdx

Updated Docs example and readme file only.
Fixes #612

Changed Tesla url to Forbes Url

---

tests/vectordb/test_chroma_db.py

Changed instances of app.count to app.db.count
Fixes #603 
Improvement
Run python file

change app.count to app.db.count

---

embedchain/embedchain.py
pyproject.toml

Online in app is fixed
Fixes #646

bug: app.online fixed

---

docs/advanced/data_types.mdx

docs: large csv file error

---

docs/examples/discord_bot.mdx
examples/discord_bot/discord_bot.py

Add chat to discord_bot example
Fixes #434

Add chat to discord_bot example

---

pyproject.toml

Bump version to 0.0.59

---

docs/mint.json

Fixed slack to Mint.js in Nav bar and Footer
**Added Slack in Mint.js in Footer and Navbar** 
Fixes #718  
_Added Slack in Footer in Navbar in Mint.js_

Fix #718 Added Slack in Mint.Js

---

embedchain/llm/azure_openai.py

This pull request updates the `AzureOpenAILlm` class in the codebase. The primary change is to rename the method `_get_azure_openai_answer` to `_get_answer` in the `AzureOpenAILlm` class
Fixes #656 

Rename _get_azure_openai_answer to _get_answer

---

pyproject.toml

Update version to 0.0.62

---

embedchain/llm/gpt4all.py

This pull request updates the `GPT4ALLLlm` class in the codebase. The primary change is to rename the method `_get_gpt4all_answer` to `_get_answer`.
##657

Rename method _get_gpt4all_answer to _get_answer

---

docs/advanced/app_types.mdx
embedchain/llm/openai.py

This pull request updates the OpenAI model name from "gpt-3.5-turbo-0613" to "gpt-3.5-turbo" .
Fixes #126 

Update outdated 'OpenAI' Model

---

README.md

As the title suggests. Minor improvements in README.

[docs]: update readme

---

tests/loaders/test_pdf_file.py

F699: add full coverage to pdf_file loader

---

.env.example

As a fairly new coder, seemingly obvious things such as - In the .env file the openai api key value should be a string is not so obvious. Keeping this in mind, I've updated the .env.example to include double quotes so that it is helpful to beginners.
Fixes the user-friendliness of the module.

Improve user readability of .env.example

---

embedchain/vectordb/chroma.py
embedchain/vectordb/elasticsearch.py
embedchain/vectordb/opensearch.py

We recently added 2 new arguments to the add and query method of the vectordbs, but they were not recorded in the documentation.
Fixes #783

Added docs for skip_embedding and embeddings argument of vectordbs

---

pyproject.toml
tests/loaders/test_docs_site_loader.py

Adds 100% test coverage for DocsSiteLoader
Fixes #697 

Feat: Improve test coverage of DocsSiteLoader

---

pyproject.toml

Bump version to 0.0.68

---

README.md

As the title suggests. We want to provide transparency in terms of what data is collected and how it is being used.

[docs]: add telemetry information in readme

---

pyproject.toml

Update version to 0.0.69

---

embedchain/bots/base.py
tests/apps/test_apps.py
tests/bots/test_base.py
tests/embedder/test_embedder.py
tests/llm/test_antrophic.py
tests/llm/test_azure_openai.py
tests/llm/test_vertex_ai.py

This PR aims to add and cover tests for the following modules:

Improve tests

---

.gitignore
configs/azure_openai.yaml
docs/components/embedding-models.mdx
docs/components/llms.mdx
docs/components/vector-databases.mdx
embedchain/factory.py
notebooks/azure-openai.ipynb

Azure OpenAI docs were missing from the docs. Adding support for it in this PR. Also, updated the docs for the Zilliz vector database.
Fixes #509 #770 
Tested locally by running the example mentioned in the docs.

[Docs] Add docs for Azure OpenAI provider

---

pyproject.toml

Update version to v0.0.72

---

pyproject.toml

Bump version to v0.0.73

---

docs/components/vector-databases.mdx
embedchain/config/vectordb/qdrant.py
embedchain/factory.py
embedchain/llm/openai.py
embedchain/models/__init__.py
embedchain/models/vector_databases.py
embedchain/vectordb/qdrant.py
pyproject.toml
tests/llm/test_base_llm.py
tests/llm/test_cohere.py
tests/llm/test_huggingface.py
tests/llm/test_jina.py
tests/llm/test_llama2.py
tests/llm/test_openai.py
tests/llm/test_query.py
tests/models/test_data_type.py
tests/vectordb/test_qdrant.py

Add support for qdrant db
Fixes #112

Feat: Add Qdrant support

---

README.md
embedchain/chunkers/unstructured_file.py
embedchain/data_formatter/data_formatter.py
embedchain/loaders/unstructured_file.py
embedchain/models/data_type.py

I have added UnstructuredFileLoader for handling unstrcutured content. datatype: USF
- [* ] New feature
I have tested it in my APP.

Unstructured File Loader Support - USF

---

.github/workflows/ci.yml
embedchain/data_formatter/data_formatter.py
embedchain/loaders/json.py
embedchain/models/data_type.py
pyproject.toml
tests/chunkers/test_chunkers.py
tests/loaders/test_json.py

Update version to v0.0.74

---

docs/advanced/configuration.mdx
docs/components/embedding-models.mdx
docs/components/llms.mdx
docs/get-started/faq.mdx

This PR updates the docs to show the proper way of passing models to "llm" in a YAML config.

[chore] Update LLM YAML config docs

---

docs/examples/api_server.mdx
docs/examples/full_stack.mdx

Add links to example repos in `examples/`

[docs] add links to example repositories

---

.github/workflows/ci.yml

Used [snok/install-poetry](https://github.com/snok/install-poetry) GH Action to create a vitrual env and cache dependencies. This will hugely save our time as installing dependencies are taking about 13 minutes.

Cache dependencies in CI

---

embedchain/__init__.py
embedchain/config/__init__.py
embedchain/config/pipeline_config.py
embedchain/pipeline.py

More about this in the later PRs. The idea is that we want the users to be able to create pipelines in Embedchain for retrieval purpose.

[Feature] Setup base for creating pipelines in embedchain

---

pyproject.toml

Bump version to v0.0.75

---

pyproject.toml

Update package version to v0.0.76

---

embedchain/llm/llama2.py
embedchain/llm/vertex_ai.py

Refer: https://colab.research.google.com/drive/157gl1vwM2YWT80arZehQ-RmfvhRO71Sv?usp=sharing

[Bug fix] import App shouldn't throw other llm deps errors

---

embedchain/llm/gpt4all.py
embedchain/pipeline.py
pyproject.toml

Upgrading the package version to v0.0.77 along with some improvements:
- Fix issues related to pipeline creation
- Lint code
- Uprev package version

Update version to v0.0.77

---

embedchain/factory.py
embedchain/llm/gpt4all.py
tests/llm/test_gpt4all.py

Add tests for gpt4all llm

---

examples/api_server/Dockerfile
examples/api_server/api_server.py
examples/api_server/docker-compose.yml
examples/api_server/requirements.txt
pyproject.toml

Fixes #856 
Tested locally by running the API server example on the latest version of Embedchain.

[Bug fix] Fix sqlite related issue with api server example

---

docs/mint.json
docs/pipelines/quickstart.mdx
embedchain/pipeline.py
pyproject.toml

Some improvements:
- Support for init pipelines with name
- Support for fetching pipelines with `id`

[Pipelines] Improvements in pipelines feature

---

embedchain/loaders/gmail.py
pyproject.toml
tests/loaders/test_gmail.py

Fixes the issue of llama index dependency in v0.0.79.

[Bug fix] Fix missing dependency issue with gmail

---

poetry.lock
pyproject.toml

[version] Update openai version to 0.28.0

---

notebooks/anthropic.ipynb
notebooks/azure-openai.ipynb
notebooks/chromadb.ipynb
notebooks/cohere.ipynb
notebooks/elasticsearch.ipynb
notebooks/embedchain-chromadb-server.ipynb
notebooks/embedchain-docs-site-example.ipynb
notebooks/gpt4all.ipynb
notebooks/hugging_face_hub.ipynb
notebooks/jina.ipynb
notebooks/llama2.ipynb
notebooks/openai.ipynb
notebooks/opensearch.ipynb
notebooks/pinecone.ipynb
notebooks/vertex_ai.ipynb

- Use Pipeline instead of App
- Install `dataloaders` package separately

Update notebooks to work with the latest version

---

embedchain/data_formatter/data_formatter.py
pyproject.toml

This PR adds lazy loading support for all our loaders and chunkers so that we only import what we need.

Lazy load loaders and chunkers

---

poetry.lock
pyproject.toml

As the title suggest. Requested here: https://github.com/embedchain/embedchain/issues/779#issuecomment-1786082050

[version] Update langchain to v0.0.303

---

embedchain/data_formatter/data_formatter.py
embedchain/loaders/json.py
tests/loaders/test_json.py
tests/telemetry/test_posthog.py

Make JSON loader available to use across all OS platforms.
Update the JSON loader to use llama-hub json loader, to remove the `jq` package dependency.
Fixes # ()
```
import os
from embedchain.pipeline import Pipeline as App
os.environ["OPENAI_API_KEY"] = "sk-xxx"
app = App()
response = app.query("What is the net worth of Elon Musk as of October 2023?")
source_id = app.add("temp.json")
print("Added doc with ", source_id)
response = app.query("What is the net worth of Elon Musk as of October 2023?")
```
```JSON
{
"question": "What is your net worth, Elon Musk?",
"answer": "As of October 2023, Elon Musk's net worth is $255.2 billion, making him one of the wealthiest individuals in the world."
}
```

Embedchain json loader update

---

docs/mint.json
embedchain/telemetry/posthog.py

[Telemetry] Update anonymous telemetry API key

---

pyproject.toml

[version] bump package version to v0.0.87

---

poetry.lock
pyproject.toml
tests/telemetry/test_posthog.py

Changes:
- Remove `jq` dependency
- Fix posthog

[misc] remove jq as a dependency

---

pyproject.toml

As the title suggests. Reported on discord here: https://discord.com/channels/1121119078191480945/1169163168828891136/1169166476226351144

[misc] add `json` extra in pyproject.toml file

---

embedchain/loaders/json.py

Clean json data before loading

---

embedchain/loaders/json.py
pyproject.toml

[Data loader] Make json data loader work for other languages 

---

README.md
docs/api-reference/getting-started.mdx
docs/rest-api/getting-started.mdx
examples/rest-api/README.md
examples/rest-api/utils.py

Changes:
- update docs
- update name of docker image for REST API

[REST API] Change docker image name and update docs

---

docs/rest-api/create.mdx
docs/rest-api/getting-started.mdx

Added steps to,
1. create
2. add data sources
3. query app
using the REST API

Improve getting started page by adding steps

---

docs/data-sources/json.mdx
examples/rest-api/main.py
examples/rest-api/models.py
examples/rest-api/services.py

Beautify JSON docs

---

docs/get-started/faq.mdx
docs/get-started/quickstart.mdx
docs/mint.json

Updated theming and faqs in the documentation.

[Docs] Update developer documentation

---

docs/examples/discord_bot.mdx
examples/discord_bot/Dockerfile
examples/discord_bot/README.md

- Dockerize discord bot and update docs to run the bot correctly
- added screenshots
- now we have two ways of running the bot

Dockerize discord bot and update docs to run the bot correctly

---

docs/examples/full_stack.mdx
examples/full_stack/backend/Dockerfile
examples/full_stack/docker-compose.yml
examples/full_stack/frontend/Dockerfile

- Slimified the docker images by ~70% and deployed the images to the docker hub
- Also updated the docs to use one command to spin up a full-stack app

Deploy Full stack docker image

---

configs/chunker.yaml
configs/full-stack.yaml
docs/advanced/configuration.mdx

Adds chunker config docs to our docs and in sample YAML files

Chunker config docs

---

docs/data-sources/overview.mdx
docs/data-sources/postgres.mdx
embedchain/apps/app.py
embedchain/chunkers/postgres.py
embedchain/constants.py
embedchain/data_formatter/data_formatter.py
embedchain/embedchain.py
embedchain/loaders/json.py
embedchain/loaders/postgres.py
embedchain/models/data_type.py
embedchain/pipeline.py
embedchain/utils.py
pyproject.toml
tests/chunkers/test_chunkers.py
tests/embedchain/test_embedchain.py
tests/loaders/test_postgres.py

Add support for loading data from Postgres.

[Feature] Add Postgres data loader

---

poetry.lock

Updating poetry.lock file for postgres loader dependencies.

[chore] update poetry.lock file

---

docs/data-sources/gmail.mdx
docs/data-sources/json.mdx
docs/data-sources/openapi.mdx
docs/get-started/openai-assistant.mdx
embedchain/store/assistants.py
pyproject.toml

Changes:
- Update docs for assistant
- Add support for better file name for assistants
- Update docs for json, postgres and openapi loader

[Docs] Update docs and improve assistant api

---

docs/get-started/openai-assistant.mdx
embedchain/store/assistants.py
pyproject.toml

Adding anonymous telemetry for OpenAIAssistant and updated docs on how to disable it.

[Feat] Add anonymous telemetry to assistant

---

examples/rest-api/requirements.txt
pyproject.toml

- Update package version to 0.1.3
- Update rest api's embedchain version

Update package version to 0.1.3

---

embedchain/embedchain.py
embedchain/memory/base.py
embedchain/memory/message.py
pyproject.toml
tests/memory/test_memory_messages.py

Changes:
- Adds support for reloading the history of an existing app id
- Add util function to get app history
- Update package version

[Improvement] Add support for reloading history for an existing app

---

embedchain/pipeline.py
pyproject.toml

Noticed that this issue is popping up on Google colab now due to us not creating the embedchain user directory if user doesn't have one.
Seeing the following error:

[bug] Fix issue of missing user directory on first init

---

embedchain/bots/base.py

Update the `BaseBot` to use Pipeline rather than our old `App` which soon will be marked deprecated

[refactor] Use pipeline for bots instead of App

---

embedchain/apps/app.py

This PR fixes missing dir error from `App` as well, supporting backward compatibility.

[Bug fix] missing dir on first init for App

---

embedchain/apps/app.py
embedchain/bots/base.py
embedchain/embedchain.py
embedchain/vectordb/chroma.py
pyproject.toml

[Bug Fix] fix chromadb where clause for query and delete

---

embedchain/embedchain.py
embedchain/store/assistants.py
pyproject.toml

Adding support for a new feature called "AIAssistant" in Embedchain. More details to be added in a new PR with docs.

[Feature] Add support for AIAssistant

---

embedchain/apps/app.py
embedchain/pipeline.py
pyproject.toml

[Bugfix] Fix issue of "unable to open database file"

---

docs/examples/slack_bot.mdx
examples/slack_bot/Dockerfile
examples/slack_bot/requirements.txt

Add slack_bot docker image

---

docs/data-sources/overview.mdx
docs/data-sources/slack.mdx
embedchain/chunkers/slack.py
embedchain/data_formatter/data_formatter.py
embedchain/loaders/postgres.py
embedchain/loaders/slack.py
embedchain/models/data_type.py
examples/rest-api/main.py
tests/chunkers/test_chunkers.py
tests/loaders/test_slack.py

This PR allows you to load data from your slack organization app.

[Feature] Add Slack Loader

---

docs/data-sources/discourse.mdx
docs/data-sources/overview.mdx
docs/data-sources/youtube-video.mdx
embedchain/chunkers/discourse.py
embedchain/data_formatter/data_formatter.py
embedchain/embedchain.py
embedchain/loaders/discourse.py
embedchain/models/data_type.py
embedchain/utils.py
tests/chunkers/test_chunkers.py
tests/helper_classes/test_json_serializable.py
tests/loaders/test_discourse.py

[Feature] Discourse Loader

---

configs/gpt4.yaml
docs/get-started/quickstart.mdx
embedchain/loaders/discourse.py
embedchain/loaders/unstructured_file.py
pyproject.toml
tests/loaders/test_discourse.py
tests/test_utils.py

[Improvements] improve package ux

---

docs/data-sources/discourse.mdx
embedchain/loaders/discourse.py
embedchain/loaders/substack.py
embedchain/loaders/youtube_video.py
pyproject.toml
tests/loaders/test_discourse.py

[Improvement] fix discourse loader to avoid rate limit

---

pyproject.toml

Bump version to 0.1.13

---

embedchain/chunkers/base_chunker.py
embedchain/data_formatter/data_formatter.py
embedchain/loaders/github.py
embedchain/loaders/sitemap.py
embedchain/loaders/youtube_channel.py
embedchain/models/data_type.py
embedchain/utils.py
poetry.lock
pyproject.toml

[Features] Add Github and Youtube Channel loaders

---

embedchain/loaders/github.py
embedchain/loaders/unstructured_file.py
poetry.lock
pyproject.toml

[Bugfix] fix poetry lock

---

embedchain/embedder/base.py

This PR updates the embedding function signature for our `embed_function`s, with the newest chromadb releases this is a breaking change (Ref: https://github.com/chroma-core/chroma/issues/1388)
Fixes #926 
Fixes #925

Update embedding_fn signature to newest chroma db's

---

pyproject.toml

- Update version to 0.1.18
cc @deshraj

Update version to 0.1.18

---

configs/chroma.yaml
embedchain/embedder/openai.py
pyproject.toml
tests/apps/test_apps.py

[Bug fix] Fix Azure OpenAI related issue

---

docs/components/embedding-models.mdx

Forgot to update the docs in the last PR #973. Hence, updating here.

Update Azure OpenAI embedding model docs

---

.github/workflows/ci.yml

Runs the workflow (install/tests) when any changes are made to the following directories:
- 'embedchain/**'
- 'tests/**'
- 'examples/**'
Fixes #935

update workflow to run when required

---

embedchain/apps/app.py
embedchain/embedchain.py
embedchain/memory/base.py
embedchain/pipeline.py
pyproject.toml

Seems like we missed to skip the thread check in the chat memory implementation. Adding it there as well.

[BugFix] Skip checking thread when making sqlite connection

---

notebooks/anthropic.ipynb
notebooks/azure-openai.ipynb
notebooks/chromadb.ipynb
notebooks/cohere.ipynb
notebooks/elasticsearch.ipynb
notebooks/gpt4all.ipynb
notebooks/hugging_face_hub.ipynb
notebooks/jina.ipynb
notebooks/llama2.ipynb
notebooks/openai.ipynb
notebooks/opensearch.ipynb
notebooks/pinecone.ipynb
notebooks/vertex_ai.ipynb

Converted multi-line dependency download to one-liner with all dependencies listed in that file

Improve deps installation by converting them to one liner

---

docs/data-sources/custom.mdx
docs/data-sources/overview.mdx
embedchain/chunkers/common_chunker.py
embedchain/data_formatter/data_formatter.py
embedchain/embedchain.py
embedchain/models/data_type.py
tests/chunkers/test_chunkers.py

This PR improves the `add` method to add data using `custom` data type by providing custom loader and chunker.

[Improvement] customize add method

---

docs/get-started/quickstart.mdx
embedchain/embedchain.py

Package Improvements - 
- update docs to show multiple ways of using configs.
- fix `add` function to re-sync all ready added data source to pick up the diff.

Package improvements

---

pyproject.toml

Updated the package version to v0.1.26

Bump package version to 0.1.26

---

embedchain/loaders/sitemap.py

local file path support for sitemap loader

---

embedchain/embedchain.py
pyproject.toml

Update ec query and chat function

---

docs/data-sources/overview.mdx
docs/data-sources/substack.mdx
embedchain/loaders/substack.py

Ref: https://github.com/embedchain/embedchain/pull/949#discussion_r1393675184

Substack loader improvements

---

docs/components/vector-databases.mdx
embedchain/config/llm/base.py
embedchain/config/vectordb/elasticsearch.py
embedchain/vectordb/elasticsearch.py

This PS allows setting up the elasticsearch db with `cloud_id`.

[Improvements] allow setting up the elasticsearch cloud instance

---

embedchain/loaders/beehiiv.py
embedchain/loaders/rss_feed.py
embedchain/loaders/sitemap.py
embedchain/loaders/substack.py
embedchain/utils.py
pyproject.toml

Fix sitemap loader logic with `https` url.

[Bugfix] fix sitemap loader

---

pyproject.toml

Update package version to v0.1.32

---

embedchain/llm/cohere.py
embedchain/llm/huggingface.py
embedchain/llm/llama2.py

Occurred during version update of langchain.
Ref: https://github.com/langchain-ai/langchain/pull/11237

[chore] fix wrong import of LLMs from langchain

---

embedchain/chunkers/web_page.py
tests/chunkers/test_chunkers.py

Update web page chunker's default chunk size to 2000. This fixes the Elasticsearch context retrieval issue.

[improvement] update web page default chunk size to 2000

---

docs/get-started/faq.mdx
embedchain/loaders/directory_loader.py
embedchain/utils.py

Update example for using mistral AI in docs to use hugging face embedding model instead of openAI embedding model.

[Doc update] update mistral example

---

README.md
embedchain/config/add_config.py

- update readme to show package downloads
- make logging more accurate when `chunk_overlap` value is greater than `min_chunk_size`

update readme to show package downloads

---

docs/_snippets/missing-data-source-tip.mdx
docs/api-reference/pipeline/delete.mdx
docs/api-reference/pipeline/reset.mdx
docs/get-started/faq.mdx
docs/mint.json
embedchain/embedchain.py
embedchain/llm/base.py

- add redirect for broken link
- add stream example when using OpenAI model
- Fix the `delete_chat_history` method and add documentation

[Docs] Documentation updates

---

docs/components/data-sources/directory.mdx
docs/components/data-sources/overview.mdx
docs/mint.json

Adds docs for the directory loader added in #1008

Docs for directory data loader usage

---

configs/google.yaml
docs/components/embedding-models.mdx
docs/components/llms.mdx
embedchain/config/embedder/google.py
embedchain/embedder/google.py
embedchain/factory.py
embedchain/llm/base.py
embedchain/llm/google.py
embedchain/loaders/github.py
embedchain/models/vector_dimensions.py
embedchain/utils.py
pyproject.toml
tests/llm/test_base_llm.py

This PR adds the embedder function that Google released.

[Feature] add google ai embedder

---

docs/components/data-sources/slack.mdx
embedchain/data_formatter/data_formatter.py
embedchain/models/data_type.py

- Added a simple example
- Added missing data types

Add docs for slack and add missing datatype

---

docs/api-reference/advanced/configuration.mdx
embedchain/utils.py
examples/chainlit/app.py

This PR fixes bug when defining `min_chunk_size` in yaml for chunker config

[Bugfix] fix chunker config bug

---

docs/integration/chainlit.mdx
docs/integration/streamlit-mistral.mdx

- Remove indentation from code
- Remove accordion
- Add a screenshot
- update models everywhere to `mistralai/Mixtral-8x7B-Instruct-v0.1` which is better

Improve Streamlit docs

---

docs/components/llms.mdx
embedchain/llm/openai.py
tests/llm/test_openai.py

This PR aims to add Open AI function calling support into Embedchain.
Examples:
Pydantic
```python
import os
from embedchain import Pipeline as App
from embedchain.llm.openai import OpenAILlm
import requests
from pydantic import BaseModel, Field, ValidationError, field_validator
os.environ["OPENAI_API_KEY"] = "sk-xxx"
class QA(BaseModel):
"""
A question and answer pair.
"""
question: str = Field(
..., description="The question.", example="What is a mountain?"
)
answer: str = Field(
..., description="The answer.", example="A mountain is a hill."
)
person_who_is_asking: str = Field(
..., description="The person who is asking the question.", example="John"
)
@field_validator("question")
def question_must_end_with_a_question_mark(cls, v):
"""
Validate that the question ends with a question …
```

OpenAI function calling support

---

docs/deployment/fly_io.mdx
docs/deployment/modal_com.mdx
docs/mint.json
pyproject.toml

Add docs for modal.com deployment

Add docs for modal.com deployment

---

docs/deployment/fly_io.mdx
embedchain/cli.py
embedchain/deployment/fly.io/app.py
embedchain/deployment/fly.io/requirements.txt
embedchain/deployment/modal.com/requirements.txt
embedchain/llm/openai.py
examples/mistral-streamlit/app.py
pyproject.toml

Telemetry support for `ec` cli commands

Telemetry support for `ec` cli commands

---

docs/get-started/deployment.mdx

Add correct deployment link for modal.com in the card

[chore] fix deployment link for modal.com card

---

README.md
docs/get-started/introduction.mdx

Update introduction in README and docs

---

docs/deployment/streamlit_io.mdx
docs/get-started/deployment.mdx
docs/mint.json
embedchain/cli.py
embedchain/deployment/streamlit.io/.env.example
embedchain/deployment/streamlit.io/.streamlit/secrets.toml
embedchain/deployment/streamlit.io/app.py
embedchain/deployment/streamlit.io/requirements.txt

This PR adds support for streamlit templates facilitating quick streamlit deployments

[new] streamlit deployment

---

examples/unacademy-ai/README.md
examples/unacademy-ai/app.py
examples/unacademy-ai/requirements.txt

Adds code for creating the Unacademy AI demo.

Add Unacademy AI demo

---

docs/deployment/modal_com.mdx
embedchain/cli.py
embedchain/deployment/modal.com/.env.example
poetry.lock
pyproject.toml

This PR fixes bug in modal.com deployment flow.

[Bugfix] Improve/modal deployment

---

examples/mistral-streamlit/app.py

- cache app to persist data in dev mode

[fix] streamlit app init by caching it

---

docs/examples/chat-with-PDF.mdx
docs/mint.json
embedchain/llm/ollama.py
examples/chat-pdf/README.md
examples/chat-pdf/app.py
examples/chat-pdf/embedchain.json
examples/chat-pdf/requirements.txt
tests/llm/test_ollama.py

This PR adds an example to create a Chat with PDF app using Streamlit and OpenAI.

[App Deployment] create chat with PDF app

---

examples/chat-pdf/requirements.txt

Fixes dependencies to run Chat PDF example app on streamlit

[Bugfix] fix chat PDF dependencies

---

examples/chat-pdf/app.py

[Chat PDF] update chat pdf logic

---

README.md
examples/chat-pdf/README.md

[Update] update readme

---

embedchain/cli.py
embedchain/client.py
embedchain/telemetry/posthog.py
pyproject.toml

Fixes #1055 (see more details related to the issue there).

[Bug Fix] Fix `FileExistsError` when using Embedchain in multithreading setting

---

docs/get-started/deployment.mdx
docs/mint.json

Add cards for gradio and hf

---

docs/contribution/dev.mdx

Update framework description and Deshraj's profile link in docs/development section

docs: Update framework desc & link

---

docs/components/data-sources/overview.mdx
docs/components/data-sources/youtube-channel.mdx
docs/components/data-sources/youtube-video.mdx
embedchain/embedchain.py
embedchain/loaders/directory_loader.py
embedchain/utils.py

- This PR add docs for `youtube_channel` data loader.
- Also adds logging in directory loader for more visibility.
- remove unnecessary error logging when detecting data type.

[Docs] add docs for youtube channel

---

pyproject.toml

Update version to 0.1.46

---

pyproject.toml

Updates the package version to 0.1.47.

Update version to 0.1.47

---

docs/api-reference/pipeline/chat.mdx
docs/api-reference/pipeline/query.mdx
docs/components/data-sources/pdf-file.mdx

This PR improves docs to mention following things:
- showcase we return `score` when `citations` is set to `True` in `query()` and `chat()` methods.
- showcase we return `page` in metadata when `citations` is `True` in `query()` and `chat()` methods.

[Improvements] update docs

---

README.md

Update
* slack and discord links
* description
* code

Update links, code and description

---

embedchain/embedchain.py
embedchain/utils.py

This PR fixes bug related to the use of google llm with example provided in the [docs](https://docs.embedchain.ai/components/llms#google-ai)

[Bugfix] fix config validation for google llm config

---

embedchain/app.py
pyproject.toml

This PR fixes the `search()` method bug.

[BugFix] search method in app

---

docs/api-reference/pipeline/search.mdx

[Docs] update search docs

---

docs/api-reference/advanced/configuration.mdx
embedchain/app.py
embedchain/cache.py
embedchain/config/cache_config.py
embedchain/llm/openai.py
embedchain/utils.py

- This PR updates the configurable options for GPTCache.
- Added docs for using GPTCache.

[Updates] Update GPTCache configuration/docs

---

embedchain/llm/gpt4all.py

Gpt4all is an offline model and can work without internet. Right now allow_download flags download list of model, due to which its not working offline. This PR removes the flag for now, but in future we will add support in the yaml config so that users can configure themselves.

feat: Make gpt4all work offline.

---

examples/private-ai/README.md
examples/private-ai/config.yaml
examples/private-ai/privateai.py
examples/private-ai/requirements.txt

feat: Add private ai example

---

docs/api-reference/pipeline/chat.mdx

We already added support for passing `session_id` in the `chat` python API. Adding docs for the same in this PR.

Update docs for session_id

---

examples/chat-pdf/app.py
examples/private-ai/privateai.py

This PR fixes bug related to chat-pdf streamlit app.

[Bugfix] fix chat pdf streamlit example

---

embedchain/embedchain.py
embedchain/llm/gpt4all.py
examples/private-ai/privateai.py

This PR enables caching per chat session.

[Bugfix] fix cache session id in chat method

---

embedchain/embedchain.py
examples/sadhguru-ai/app.py

This PR fixes sadhguru example code to return source urls instead of all the metadata.

[Bugfix] fix sadhguru example sources return logic

---

docs/api-reference/advanced/configuration.mdx
embedchain/cli.py

Also, include a fix of template name for `ec create` command with huggingface/streamlit app

[Bug fix] quickfix custom configuration doc

---

embedchain/loaders/slack.py

[BugFixes] slack loader

---

docs/get-started/full-stack.mdx
embedchain/cli.py
pyproject.toml

Several users requested about docker support for the full stack application. Hence, adding support for it.

[Feature] Add support for docker in fullstack app

---

pyproject.toml

Updates the version of the package to 0.1.56.

Update package version to 0.1.56

---

embedchain-js/README.md

README.md: Fix typo

---

docs/components/data-sources/csv.mdx
docs/components/data-sources/pdf-file.mdx
docs/get-started/quickstart.mdx

Updating documentation based on the user feedback from this livestream about Embedchain: https://www.youtube.com/watch?v=Pw_7_r63q_U
Will keep incorporating other suggestions in follow up PR.

Update documentation based on user feedback

---

pyproject.toml

Update version to 0.1.57

---

configs/vllm.yaml
docs/components/llms.mdx
embedchain/app.py
embedchain/config/llm/base.py
embedchain/embedchain.py
embedchain/llm/base.py
embedchain/llm/vllm.py
embedchain/vectordb/zilliz.py
pyproject.toml

This PR adds support for loading llms from the vLLM package. 
Fixes #1027

[Feature] Add support for vllm as llm source

---

README.md

README.md: Expand the acronym to help readers understand

---

docs/components/data-sources/dropbox.mdx

Updating docs for dropbox based on a user feedback on discord where the user forgot to install `dropbox`.

[Docs] Update docs for dropbox loader

---

pyproject.toml

Update version to 0.1.61

---

docs/components/evaluation.mdx
embedchain/eval/metrics/groundedness.py

[Docs] Update docs for evaluation

---

embedchain/embedchain.py
embedchain/memory/base.py
pyproject.toml
tests/memory/test_chat_memory.py

This PR updates LLM memory's `get()` method to be able to fetch app's entire chat history for all session with by passing `fetch_all` param as true.

[Improvement] update LLM memory get function

---

embedchain/chunkers/base_chunker.py
embedchain/embedchain.py
embedchain/vectordb/chroma.py
embedchain/vectordb/elasticsearch.py
embedchain/vectordb/opensearch.py
embedchain/vectordb/pinecone.py
embedchain/vectordb/qdrant.py
embedchain/vectordb/weaviate.py
embedchain/vectordb/zilliz.py
tests/vectordb/test_elasticsearch_db.py
tests/vectordb/test_pinecone.py
tests/vectordb/test_qdrant.py
tests/vectordb/test_weaviate.py

Fixes the issue mentioned by the user  on our slack forum.

[Bug fix] Fix embedding issue for opensearch and some other vector databases

---

embedchain/app.py
embedchain/cli.py
pyproject.toml

This PR fixes cli bug for `hf/streamlit.io` template

[Bugfix] fix ec dev command for hf spaces

---

embedchain/evaluation/metrics/groundedness.py
tests/evaluation/test_answer_relevancy_metric.py
tests/evaluation/test_context_relevancy_metric.py
tests/evaluation/test_groundedness_metric.py

This PR adds test for evaluation metrics.

[Tests] add tests for evaluation metrics

---

docs/examples/showcase.mdx

Update Askabraham showcase

---

embedchain/embedder/google.py

This PR fixes the google ai embedder function to migrate to the new Embedding function from ChromaDB.

[Bugfix] fix google ai embedding function

---

pyproject.toml
tests/test_factory.py

Add test for passing `vector_dimension` in embedder config.

[Update] add test for passing vector dimension in embedder config

---

docs/components/llms.mdx
embedchain/embedder/mistralai.py
embedchain/factory.py
embedchain/llm/mistralai.py
embedchain/models/vector_dimensions.py
embedchain/utils/misc.py
poetry.lock
pyproject.toml
tests/llm/test_mistralai.py

This PR enable support for Mistral API.
```python
import os
os.environ["MISTRAL_API_KEY"] = "xxx"
config = {
"llm": {
"provider": "mistralai",
"config": {
"model": "mistral-tiny",
"temperature": 0.5,
"max_tokens": 1000,
"top_p": 1,
"stream": False,
},
},
"embedder": {
"provider": "mistralai",
"config": {
"model": "mistral-embed",
},
},
}
app.add("https://www.forbes.com/profile/elon-musk")
response = app.query("what is the net worth of Elon Musk?")
response = app.chat("which companies does elon own?")
response = app.chat("what question did I ask you already?")
```

[Feature] Add support for Mistral API

---

docs/api-reference/advanced/configuration.mdx
docs/components/llms.mdx
embedchain/factory.py
embedchain/llm/aws_bedrock.py
embedchain/utils/misc.py
poetry.lock
pyproject.toml
tests/llm/test_aws_bedrock.py

This PR adds support for AWS Bedrock LLM.
```python
import os
os.environ["AWS_ACCESS_KEY_ID"] = "xxx"
os.environ["AWS_SECRET_ACCESS_KEY"] = "xxxx"
config = {
"llm": {
"provider": "aws_bedrock",
"config": {
"model": "amazon.titan-text-express-v1",
"model_kwargs": {
"temperature": 0.5,
"topP": 1,
"maxTokenCount": 1000,
},
},
},
}
app.add("https://www.forbes.com/profile/elon-musk")
response = app.query("what is the net worth of Elon Musk?")
response = app.chat("which companies does elon own?")
response = app.chat("what question did I ask you already?")
```

[Feature] Add support for AWS Bedrock LLM

---

docs/_snippets/get-help.mdx
docs/_snippets/missing-data-source-tip.mdx
docs/_snippets/missing-llm-tip.mdx
docs/_snippets/missing-vector-db-tip.mdx
docs/community/connect-with-us.mdx
docs/mint.json

This PR fixes the slack link in docs.

[Docs] fix slack join link

---

embedchain/vectordb/elasticsearch.py

This PR includes following changes:
```python
config = {
"vectordb": {
"provider": "elasticsearch",
"config": {
"collection_name": "ec-test",
"cloud_id": "xxx",
"basic_auth": ("elastic", "password"),
"verify_certs": True,
},
}
}
print(list(map(lambda x: x[1]["url"], context)))
```
Please delete options …

[bugfix] fix elasticsearch db

---

embedchain/vectordb/opensearch.py

This PR includes following changes:
```python
config = {
"vectordb": {
"provider": "opensearch",
"config": {
"collection_name": "my-app",
"opensearch_url": "https://localhost:9200",
"http_auth": ["admin", "admin"],
"vector_dimension": 1536,
"use_ssl": False,
"verify_certs": True,
},
}
} …
```

[Bugfix] fix opensearch db

---

embedchain/vectordb/pinecone.py

This PR includes following changes:
```python
config = {
"vectordb": {
"provider": "pinecone",
"config": {"metric": "cosine", "vector_dimension": 1536, "collection_name": "my-pinecone-index"},
}
}
print(list(map(lambda x: x[1]["url"], context)))
```

[Bugfix] fix pinecone db

---

docs/api-reference/app/delete.mdx
embedchain/embedchain.py
embedchain/vectordb/base.py

This PR enables deleting sources from the db.
```python
app = App()
source_id = app.add("https://www.forbes.com/profile/elon-musk")
app.delete(source_id=source_id)
```

[Feature] add `app.delete()` method

---

docs/components/vector-databases.mdx
embedchain/config/vectordb/pinecone.py
embedchain/vectordb/pinecone.py
tests/vectordb/test_pinecone.py

Enable using custom index name with Pinecone.
Fixes #1171 

enable using custom Pinecone index name

---

docs/api-reference/app/get.mdx
docs/mint.json

This PR adds docs for showing the list of already added data sources in the app.

[Docs] add docs for getting the list of added data sources

---

docs/get-started/quickstart.mdx

This PR updates the mistral model in quickstart example for open source model.

[Docs] Update mistral model in quickstart example

---

docs/components/vector-databases.mdx
embedchain/config/vectordb/pinecone.py
embedchain/vectordb/pinecone.py
poetry.lock
pyproject.toml
tests/vectordb/test_pinecone.py

This PR upgrades the pinecone client to newer version (v3)
```python
import os
os.environ["OPENAI_API_KEY"] = "xxxx"
os.environ["PINECONE_API_KEY"] = "xxx"
config = {
"vectordb": {
"provider": "pinecone",
"config": {
"metric": "cosine",
"vector_dimension": 1536,
"collection_name": "my-pinecone-index",
"serverless_config": {
"cloud": "aws",
"region": "us-west-2",
},
},
}
}
bill_source_id = ""
elon_source_id = ""
def test_add_data():
global bill_source_id, elon_source_id
id_1 = app.add("https://www.forbes.com/profile/elon-musk", metadata={"source": "forbes", "person": "elon"})
print(id_1)
id_2 = app.add("https://en.wikipedia.org/wiki/Elon_Musk", metadata={"source": "wikipedia", …
```

[Improvement] update pinecone client v3

---

embedchain/vectordb/opensearch.py

This PR fixes opensearch db bug.

[Bugfix] fix typo in opensearch db

---

embedchain/loaders/web_page.py

This PR adds default user agent header in web page loader.

[Improvement] add default user-agent header in webpage loader

---

embedchain/embedchain.py
pyproject.toml

We want to fetch the list of all the chat history for the embedchain full stack application. Hence, adding support for fetching all the chat history in the package itself.

[Feature] Add support for optionally fetch all chat history for app

---

docs/deployment/railway.mdx
docs/get-started/deployment.mdx
docs/mint.json

Added documentation for deploying to Railway.app, a popular hosting platform for developers.
Used `mintlify dev` command to run the docs and verify them locally.

[Docs] Added documentation to deploy to Railway.app

---

embedchain/config/llm/base.py
embedchain/llm/base.py
embedchain/llm/openai.py
embedchain/memory/base.py
pyproject.toml

This PR fixes some issues related to the package such as:
- Order of history sent to the prompt
- Formatting of history when injected to the prompt

[Bug fix] Fix history sequence in prompt

---

tests/llm/test_generate_prompt.py

Missed to fix the test in my last PR.

[Bug fix] Fix test

---

pyproject.toml

Update version to 0.1.78

---

pyproject.toml

Allow for people to use with more recent version of python

Updating python version to including <=3.13

---

docs/components/data-sources/data-type-handling.mdx

Resolving the comment from a user on Github thread: https://github.com/embedchain/embedchain/issues/884#issuecomment-1968813323

[Docs] Update docs for resetting vector database

---

docs/components/vector-databases/pinecone.mdx

[Docs] Update pinecone integration docs

---

docs/integration/langsmith.mdx

Fixed missing word and grammatical error in langsmith.mdx
Used `mintlify dev` command to run the docs and verify them locally.

[docs] update langsmith.mdx

---

README.md
docs/get-started/introduction.mdx
docs/get-started/quickstart.mdx

[Docs] Update docs and readme

---

docs/components/embedding-models.mdx
embedchain/embedder/cohere.py
embedchain/factory.py
embedchain/models/vector_dimensions.py

Adding support for Cohere Embeddings
Fixes #1248 
Yes

Support for Cohere Embeddings

---

docs/components/data-sources/github.mdx
embedchain/loaders/github.py

Add support for extraction of data from specific Branch or File.
Fixes #1243
Yes

Add folder and branch to GitHub

---

embedchain/embedchain.py

fix Cannot add documents to chromadb with inconsistent sizes.documents & metadatas & ids need consistent sizes.
run test

[Bug fix]: fix Cannot add documents to chromadb with inconsistent sizes.

---

pyproject.toml

[Version] Update version to 0.1.96

---

embedchain/alembic.ini
embedchain/app.py
embedchain/migrations/env.py
pyproject.toml

Changes:
- Remove global logging config by alembic
- Remove the debug statements added by mistake
- Update package version

[Bug fix] Fix issues related to logging configuration

---

embedchain/vectordb/qdrant.py

The original code always generates new uuid for the PK.

avoid saving the duplicated docs

---

pyproject.toml

Update package version to 0.1.98

---

embedchain/app.py
embedchain/embedchain.py
embedchain/llm/anthropic.py
pyproject.toml

Changes:
- Fix issue when the source type in data_sources is not a string. Convert it specifically
- Convert the print statements to logging

[Improvements] Improve logging and fix insertion in data_sources table

---

embedchain/constants.py
pyproject.toml

Requested by a user on slack: https://embedchain.slack.com/archives/C05RG7CJKC6/p1713438823755449

[Improvement] Make embedchain home dir configurable

---

embedchain/telemetry/posthog.py
pyproject.toml

Missed to remove the duplicate constants in the last PR. Fixed it in the current one.

[Bug fix] Remove duplicate constants

---

docs/components/data-sources/qna.mdx

docs: fix typo

---

poetry.lock
pyproject.toml

[Misc] Update package version for chroma and pypdf

---

embedchain/loaders/youtube_video.py

This PR introduces a new feature to extract timestamps from youtube videos and store them with other metadata elements .
This enhancement aims to provide richer data insights and improve content navigation and usability.
Fixes # (#1244)
Manual testing was conducted to ensure the accuracy and reliability of the timestamp extraction. Tests included videos of various lengths and formats to verify that the timestamps are correctly identified and recorded.
Example of timestamps added to metadata 
and this is an example of the transcript format which  is generated:

Feature to extract timestamps from youtube videos

---

embedchain/embedchain.py

Add proper docstring for the functions in embechain.py.
Fixes #193

Doc string fix for embedchain.py

---

pyproject.toml

Update version to 0.1.105

---

docs/components/embedding-models.mdx
embedchain/embedder/ollama.py

Ollama embeddings tested and proper documentation provided.

Ollama embeddings tested and Docs ready

---

embedchain/vectordb/chroma.py
embedchain/vectordb/elasticsearch.py
embedchain/vectordb/opensearch.py
embedchain/vectordb/pinecone.py
embedchain/vectordb/qdrant.py
embedchain/vectordb/weaviate.py
embedchain/vectordb/zilliz.py
tests/vectordb/test_elasticsearch_db.py
tests/vectordb/test_qdrant.py
tests/vectordb/test_weaviate.py
tests/vectordb/test_zilliz_db.py

Replacing all query functions for vectordb where list[str] was used to now str.
Fixes #776 

Change lit[str] -> str for vectordbs

---

embedchain/store/assistants.py

Fixes openai assistant. PLEASE USE OPENAI==1.20.0 (https://github.com/openai/openai-python/issues/1416)
Fixes #1369

Fix OpenAI Assistant

---

pyproject.toml

Update package version to 0.1.108

---

Makefile
embedchain/llm/ollama.py
tests/llm/test_ollama.py

Download model from ollama if not present locally

Download Ollama model if not present

---

docs/components/llms.mdx

added needed environment variable and point the embedder to ollama ( othewise goes to openai)
- [ X] Documentation update
- [X ] Test Script (please provide)
#!/mnt/g/trabaho/embedchain/.venv/bin/python
import os
os.environ["OLLAMA_HOST"] = "http://127.0.0.1:11434"
app = App.from_config(config_path="config.yaml") …

Update llms card to properly use local ollama

---

docs/components/data-sources/text-file.mdx

Add documentation for the data type text_file
Fixes # 1069
Below, there is a screenshot of the preview in http://localhost:3000

Add documentation for text_file data type

---

CONTRIBUTING.md
poetry.lock
pyproject.toml

Verion bump, chromadb_version change and doc update

---

Makefile
docs/components/data-sources/audio.mdx
docs/components/data-sources/overview.mdx
embedchain/chunkers/audio.py
embedchain/data_formatter/data_formatter.py
embedchain/loaders/audio.py
embedchain/models/data_type.py
embedchain/utils/misc.py
tests/chunkers/test_chunkers.py
tests/loaders/test_audio.py

Support for Audio Files
Fixes #1335 

Support for Audio Files

---

embedchain/llm/anthropic.py
embedchain/llm/cohere.py
embedchain/llm/google.py
embedchain/llm/groq.py
embedchain/llm/huggingface.py
embedchain/llm/jina.py
embedchain/llm/llama2.py
embedchain/llm/nvidia.py
embedchain/llm/together.py
tests/llm/test_jina.py

Try to access api_key or var from os
Fixes #1420 

access api_key in every llm

---

docs/integration/openlit.mdx
docs/mint.json

Add doc/guide on how users can use OpenLIT to monitor their LLM Application and visualize in any of their existing Observability tools like Grafana, DataDog etc. 

[Docs]: Add Integration for OpenLIT (OpenTelemetry-native LLM Application O11y)

---

docs/api-reference/advanced/configuration.mdx
docs/components/llms.mdx
embedchain/config/llm/base.py
embedchain/llm/azure_openai.py
embedchain/utils/misc.py
tests/llm/test_azure_openai.py

- Adds correct documentation for azure open-ai environment variables.
- Allows users to add azure open-ai `api_version` from config. 
- (documented + added tests for `api_version`)
- Azure OpenAI embedder is already present in the [code](https://github.com/embedchain/embedchain/blob/main/embedchain/embedder/openai.py#L23) and [docs](https://docs.embedchain.ai/components/embedding-models#azure-openai). 
Fixes #1347 
Tested using my Azure AI connection, added test-cases.

azure openai features and bugs solve - openai_version, docs

---

tests/llm/test_ollama.py

Fix Ollama test

---

embedchain/llm/google.py
embedchain/llm/ollama.py

For Ollama and Google LLMs raise import error if module is not found.

Raise import error if Ollama and Google not found

---

Makefile
embedchain/embedder/huggingface.py

Fixes HF emedder models.
Fixes #1439 

Change HF embedding library

---

embedchain/loaders/image.py

change: replaced deprecated gpt-4-perview with gpt-4o

---

docs/components/vector-databases/lancedb.mdx

Updated LanceDB Doc

---

pyproject.toml

Version bump -> 0.1.113

---

docs/api-reference/advanced/configuration.mdx
embedchain/config/vectordb/base.py
embedchain/vectordb/chroma.py
embedchain/vectordb/elasticsearch.py
embedchain/vectordb/lancedb.py
embedchain/vectordb/opensearch.py
embedchain/vectordb/pinecone.py
embedchain/vectordb/qdrant.py
embedchain/vectordb/weaviate.py
tests/vectordb/test_weaviate.py

Support to add batch_size in vectordb config.
Fixes https://embedchain.slack.com/archives/C05RG7CJKC6/p1719407963572489

Add batch_size in config for VectorDB

---

Makefile
docs/api-reference/advanced/configuration.mdx
docs/api-reference/app/chat.mdx
embedchain/app.py
embedchain/config/__init__.py
embedchain/config/llm/base.py
embedchain/config/mem0_config.py
embedchain/embedchain.py
embedchain/llm/base.py
embedchain/utils/misc.py
poetry.lock
pyproject.toml

Integrate mem0 in for storing chat history. https://docs.mem0.ai/

Integrate Mem0

---

pyproject.toml

Version bump -> 0.1.116

---

embedchain/embedchain/config/llm/base.py
embedchain/embedchain/config/model_prices_and_context_window.json

Move model pricing json to config folder in embedchain. It's used for enabling token usage.

Add model pricing file

---

pyproject.toml

Update mem0 version to 0.0.4

---

docs/quickstart.mdx

add delete and reset in docs

---

cookbooks/mem0-multion.ipynb
docs/integrations/multion.mdx
docs/llms.mdx
docs/mint.json

Adding a notebook for how to use multion with mem0.

[Docs] Add multion integration

---

embedchain/docs/api-reference/advanced/configuration.mdx
embedchain/docs/api-reference/app/chat.mdx
embedchain/embedchain/app.py
embedchain/embedchain/embedchain.py
embedchain/poetry.lock
embedchain/pyproject.toml
pyproject.toml

Change mem0 package from using memzero to mem0ai

Change dependency to mem0ai

---

docs/llms.mdx
mem0/llms/litellm.py
mem0/utils/factory.py
poetry.lock
pyproject.toml
tests/llms/test_litellm.py

Add Litellm support

---

mem0/configs/llms/base.py
mem0/llms/aws_bedrock.py
mem0/llms/base.py
mem0/llms/configs.py
mem0/llms/groq.py
mem0/llms/litellm.py
mem0/llms/openai.py
mem0/llms/together.py
mem0/memory/main.py
mem0/utils/factory.py
tests/llms/test_groq.py
tests/llms/test_litellm.py
tests/llms/test_openai.py
tests/llms/test_together.py

Add support to pass the model parameters in config for LLMs.

Support model config in LLMs

---

docs/llms.mdx
embedchain/docs/api-reference/app/chat.mdx

Added documentation on using Google AI and Anthropic. Also added explanation on how Mem0 is used with Embedchain.

Update Mem0 LLM docs

---

.github/workflows/ci.yml
Makefile
embedchain/embedchain/llm/aws_bedrock.py
mem0/llms/aws_bedrock.py

Fix CI tests so that tests for Mem0 and Embedchain works.

Fix CI tests for Mem0

---

embedchain/embedchain/config/llm/base.py
embedchain/embedchain/embedchain.py
embedchain/embedchain/llm/openai.py
embedchain/embedchain/utils/misc.py
embedchain/pyproject.toml

Fixes few issues related to mem0 integration in embedchain.

Mem0 fix in embedchain

---

docs/llms.mdx
docs/mint.json
docs/overview.mdx

Update Docs:
- Add docs on how to use Mistral and Azure AI models.
- Explaining how Mem0 works.
- [] Unit Test

Update docs for LLMs and Overview

---

docs/platform/quickstart.mdx
mem0/client/main.py
pyproject.toml

Changes:
- Update response format for following APIs:
- Search API
- Get all memories API
- History API
- Improve memory deduction and update logic
- Make platform memory ingestion and retrieval ~2x faster
- Update docs for how to use platform client

[Mem0] Update platform client, improve deduction logic and update client docs

---

README.md
embedchain/pyproject.toml

Update mem0 version in embedchain and update README.

Update mem0 version in embedchain

---

docs/integrations/multion.mdx

update multion docs

---

README.md

- Add mem0 newsletter link
- update slack link

feat: Add mem0 newsletter link

---

README.md

fix: substack link

---

cookbooks/multion_travel_agent.ipynb
docs/integrations/multion.mdx
docs/platform/quickstart.mdx

Add output examples and multion travel agent notebook

Add output examples and multion travel agent notebook

---

mem0/memory/main.py

Fix redundant code line in Base Memory.
Fixes #1600

Redundant code fix

---

docs/platform/quickstart.mdx
mem0/client/main.py

Add update method in client

---

embedchain/docs/api-reference/advanced/configuration.mdx
embedchain/embedchain/config/embedder/base.py
embedchain/embedchain/embedder/azure_openai.py
embedchain/embedchain/llm/azure_openai.py
embedchain/embedchain/utils/misc.py
embedchain/poetry.lock
embedchain/tests/embedder/test_azure_openai_embedder.py
embedchain/tests/llm/test_azure_openai.py

This PR allows users to access AzureOpenai from behind company proxy servers. I wanted to make this PR so my teammates can test out embedchain library.
Fixes #1451 #1597
Added unit tests, and tested behind company proxy.
Test script `main.py` - 
```
import os
os.environ["OPENAI_API_TYPE"] = "azure"
os.environ["AZURE_OPENAI_ENDPOINT"] = "endpoint"
os.environ["AZURE_OPENAI_API_KEY"] = "key"
os.environ["OPENAI_API_VERSION"] = "2024-02-01"
app = App.from_config(config_path="./config.yaml")
app.add("https://en.wikipedia.org/wiki/Sun_Tzu")
while True:
question = input("Enter question: ")
if question in ["q", "exit", "quit"]:
break
answer = app.query(question)
print(answer)
```
and the `config.yaml` - 
```
llm:
provider: …
```

AzureOpenai access from behind company proxies.

---

embedchain/embedchain/config/evaluation/base.py

chore: update base.py

---

mem0/memory/main.py

docs(memory): add  field doc

---

docs/components/llms.mdx

llm doc fix

---

embedchain/docs/contribution/guidelines.mdx

docs: fix guidelines link

---

mem0/configs/prompts.py

Just correcting a typo, and getting back to contributing after re-branding 😅
Fixes #1531 

correcting prompt for UPDATE_MEMORY_PROMPT

---

mem0/embeddings/huggingface.py

fix: method name should be same with abstrct base class

---

embedchain/pyproject.toml
pyproject.toml

Version bump for Mem0 and Embedchain

---

mem0/configs/llms/base.py
mem0/embeddings/base.py
mem0/embeddings/ollama.py
mem0/embeddings/openai.py
mem0/memory/telemetry.py
mem0/utils/factory.py
mem0/vector_stores/configs.py

Add ollama embeddings

---

docs/mint.json

doc fix for components

---

mem0/vector_stores/chroma.py
mem0/vector_stores/configs.py

Fix client for both vector store in configs.

Fix config for vector store

---

docs/components/vectordb.mdx
mem0/configs/vector_stores/chroma.py
mem0/configs/vector_stores/qdrant.py
mem0/utils/factory.py
mem0/vector_stores/chroma.py
mem0/vector_stores/configs.py
pyproject.toml

Handle chromadb dep and version bump

---

mem0/configs/vector_stores/chroma.py
mem0/configs/vector_stores/qdrant.py
mem0/memory/main.py
mem0/memory/storage.py
mem0/utils/factory.py
mem0/vector_stores/configs.py
tests/test_proxy.py

Fix lint issues

---

mem0/memory/main.py

fix serialized_existing_memories dump field bug

fix serialized_existing_memories dump field bug

---

docs/examples/ai_companion.mdx

Companion Example

---

docs/platform/quickstart.mdx

[Docs] Fix numbering in docs

---

mem0/configs/vector_stores/qdrant.py
mem0/vector_stores/qdrant.py

Added the `on_disk` param to Qdrant configs, which will enable persistent storage locally.
Fixes #1623 
Test script: 
``` 
import os
config = {
"provider": "qdrant",
"config": {
"on_disk": True,
"path": "./qdrant-db",
}
},  
}
result = m.add("I am working on improving my pickle-ball skills. Suggest some online courses.", user_id="Joe", metadata={"category": "hobbies"})
result = m.add("The Tree is on fire", user_id="Joe", metadata={"category": "hobbies"})
all_memories = m.get_all()
print(all_memories)
```

added on_disk param to qdrant configs

---

docs/components/embedders.mdx
docs/mint.json
mem0/configs/embeddings/base.py
mem0/configs/llms/base.py
mem0/configs/vector_stores/chroma.py
mem0/configs/vector_stores/qdrant.py
mem0/embeddings/ollama.py
mem0/embeddings/openai.py
mem0/llms/openai.py
mem0/memory/main.py
mem0/vector_stores/configs.py
pyproject.toml

Changes:
- Add docs for embedders
- Param validation in vector configs
- Add hash to db for update call
- Version bump

Add embedder docs and config changes

---

docs/components/embedders.mdx

embedding doc fix

---

docs/components/vectordb.mdx
mem0/configs/vector_stores/pgvector.py
mem0/memory/main.py
mem0/utils/factory.py
mem0/vector_stores/chroma.py
mem0/vector_stores/configs.py
mem0/vector_stores/pgvector.py
mem0/vector_stores/qdrant.py

Add support for pgvector as vector db and also update the docs.
```python
import os
os.environ["OPENAI_API_KEY"] = "sk-xx"
config = {
"vector_store":{
"provider": "pgvector",
"config": {
"user": "test",
"password": "123",
}
}
}
m.add("visiting to paris", user_id="test", run_id="123")
```

Add support for pgvector

---

docs/components/embedders.mdx

Embedding docs fix

---

mem0/memory/setup.py
pyproject.toml

Handle telementry exception and version bump.

Handle telementry exception

---

mem0/vector_stores/chroma.py
pyproject.toml

Fix chroma `get_all` method
Fixes #

Fix chroma `get_all` method

---

docs/integrations/multion.mdx

add notebook link in multion page

---

embedchain/docs/components/data-sources/mysql.mdx

Embedchain doc, there is a typo, I fix it.

[embedchain doc] fix typo mysql.mdx

---

docs/components/llms/models/litellm.mdx

fix litellm doc link

---

docs/examples/langgraph.mdx
docs/mint.json

Add langgraph doc

---

docs/examples/mem0-with-ollama.mdx
docs/mint.json
docs/open-source/quickstart.mdx

Add ollama example

---

embedchain/poetry.lock
embedchain/pyproject.toml

bump version for embedchain

---

docs/examples/autogen.mdx
docs/mint.json

Add autogen docs

---

mem0/memory/main.py

Any of the ID is needed for .add() and .search() to work.

User ID needed for .add() and .search()

---

pyproject.toml

Version Update

---

poetry.lock
pyproject.toml

added neo4j dependency

---

README.md
docs/mint.json
docs/open-source/graph-memory.mdx

Readme Changes

---

docs/features/selective-memory.mdx
docs/mint.json

Added customized memory part to the docs

Added customized memory to docs

---

docs/api-reference/entities/delete-user.mdx
docs/api-reference/entities/get-users.mdx
docs/api-reference/memory/add-memories.mdx
docs/api-reference/memory/delete-memories.mdx
docs/api-reference/memory/delete-memory.mdx
docs/api-reference/memory/get-memories.mdx
docs/api-reference/memory/get-memory.mdx
docs/api-reference/memory/history-memory.mdx
docs/api-reference/memory/search-memories.mdx
docs/api-reference/memory/update-memory.mdx
docs/api-reference/overview.mdx
docs/mint.json
docs/openapi.json

Add API Reference docs

---

docs/features/custom-categories.mdx
docs/mint.json

Added docs for custom categories. Users can now define categories based on their preference and usecase.

Added docs for custom categories

---

docs/open-source/graph-memory.mdx

Added a video of graph memory in the docs

Added graph memory video in docs

---

docs/openapi.json

add api-reference for custom categories

add api-reference for custom categories

---

README.md

Small fix on readme - `m.get_all()` returns dict. 
Fixes #1755 

get_all returns dictionary

---

docs/api-reference/memory/add-memories.mdx
docs/api-reference/memory/delete-memories.mdx
docs/api-reference/memory/delete-memory.mdx
docs/api-reference/memory/get-memories.mdx
docs/api-reference/memory/get-memory.mdx
docs/api-reference/memory/history-memory.mdx
docs/api-reference/memory/search-memories.mdx
docs/api-reference/memory/update-memory.mdx
docs/api-reference/memory/v1-search-memories.mdx
docs/api-reference/memory/v2-search-memories.mdx
docs/mint.json
docs/openapi.json

Add docs for V2 search in API reference page.

API reference docs for Search V2

---

docs/api-reference/entities/delete-user.mdx
docs/api-reference/entities/get-users.mdx
docs/openapi.json

- Use `api-key` for authentication.
- Fix entities APIs

Fixes in API-reference page

---

docs/open-source/graph-memory.mdx

Added a notebook for graph memory, users can now play with the graph component of mem0.

Added Google Colab link for Graph Memory

---

docs/open-source/graph-memory.mdx

Updated the location of the google colab link for graph memory.

Modified the location of graph memory's colab link

---

docs/components/embedders/config.mdx
docs/components/llms/config.mdx
mem0/configs/embeddings/base.py
mem0/configs/llms/base.py
mem0/embeddings/azure_openai.py
mem0/llms/azure_openai.py
tests/llms/test_azure_openai.py

Pass http proxies from config for Azure OpenAI services.
Fixes #1754 
added this config to the example - 
```
os.environ["OPENAI_API_VERSION"] = "2024-02-01"
config = {
"llm": {
"provider": "azure_openai",
"config": {
"model": "gpt-35-turbo-16k",
"temperature": 0.1,
"max_tokens": 2000,
"http_client_proxies": "http://testproxy.mem0.net:8000/",
}
},
"embedder": {
"provider": "azure_openai",
"config": {
"model": "text-embedding-3-large",
"http_client_proxies": "http://testproxy.mem0.net:8000/",
"embedding_dims": 3072
}
}, …
```

Adding proxy server settings to azure openai

---

docs/components/embedders/config.mdx
docs/components/llms/config.mdx

Update docs for the `openai_base_url` parameter added in #1737

docs: add `openai_base_url` related docs

---

mem0/memory/main.py

Fix the docstring of memory addition operation.

fix(docs): memory addition return type

---

tests/test_memory.py

This PR improves consistency of `tests/test_memory.py`.
Fixes #1770 

Improve: consistency in the test_memory.py

---

docs/components/llms/models/together.mdx
mem0/graphs/configs.py
mem0/graphs/tools.py
mem0/graphs/utils.py
mem0/llms/configs.py
mem0/llms/openai_structured.py
mem0/llms/utils/tools.py
mem0/memory/main_graph.py
mem0/utils/factory.py
pyproject.toml
tests/test_memory.py

Following improvements have been made to the Graph Memory
1. Graph Memory now supports all existing LLMs, previously it only supported ```gpt-4o-2024-08-06```.
2. Users can now give their custom prompt to extract entities from the text to create nodes and relationships.
3. Improved Graph Memory search using BM25 algorithm, previously the search result was random.
4. A new openai structured class has been added to the LLMs, now user can use the ```gpt-4o-2024-08-06``` model using the ```openai_structured``` llm provider.

Improvements to Graph Memory

---

docs/components/llms/models/openai.mdx
docs/mint.json
docs/open-source/graph_memory/features.mdx
docs/open-source/graph_memory/overview.mdx

Updated the Graph Memory docs about custom LLM support.

Graph memory docs update

---

docs/platform/quickstart.mdx
mem0/client/main.py

Added Reset API for Client
Fixes #1776

add-reset-api-for-client

---

README.md

While the version of the repo is different with pypi package version, these badges should help.

docs(readme): add pypi related badges

---

mem0/configs/vector_stores/chroma.py
mem0/llms/aws_bedrock.py
mem0/llms/groq.py
mem0/llms/litellm.py
mem0/llms/ollama.py
mem0/llms/together.py

Implement a mechanism to automatically prompt users to install missing packages. If they agree, the required package will be installed.
- progresses #1768 
Updated files:
`mem0/configs/vector_stores/chroma.py`
`mem0/llms/aws_bedrock.py`
`mem0/llms/groq.py`
`mem0/llms/litellm.py`
`mem0/llms/ollama.py`
`mem0/llms/together.py`

feat: automates package installation

---

mem0/embeddings/ollama.py
mem0/proxy/main.py
mem0/vector_stores/chroma.py
mem0/vector_stores/pgvector.py

This commit automates the installation of the `ollama`, `litellm`, `chromadb`, and `psycopg2` libraries when they are not found. 
- progresses: #1768 
With this pull request, we have completed automating the installation of all dependencies in the `mem0/*` directory.
File changes:
`mem0/embeddings/ollama.py`
`mem0/proxy/main.py`
`mem0/vector_stores/chroma.py`
`mem0/vector_stores/pgvector.py`

feat: Automate installation of required libraries.

---

mem0/memory/main.py
mem0/memory/main_graph.py

Users now can create multiple graphs in the same Neo4j project using the user_id. Add, Search, and Get_all all supports filtering by user_id.

Added user_id support for graph memory

---

docs/examples/personal-travel-assistant.mdx

`v1.1` had a breaking change, doc examples won't work. Fixing them here. 
Fixes #1784 

Adding v1.1 code snipper for personal-travel-assistant

---

docs/open-source/graph_memory/overview.mdx
pyproject.toml

Changed the relative path to the absolute path for images in graph memory

Bug fixes in docs

---

mem0/memory/main.py

fix: fix bug about MemoryGraph can't find

---

docs/open-source/quickstart.mdx

Add contributing doc

---

docs/api-reference/memory/v2-search-memories.mdx

Explain how v2 is different from v1 search API and add an example for `filters` param.

Improve api reference for v2 search api

---

pyproject.toml

Fixed a small import bug and increased the version of the release.

Bug fixes and version bump

---

mem0/llms/openai_structured.py

docs: fix docstring

---

mem0/embeddings/azure_openai.py
mem0/embeddings/openai.py
mem0/llms/azure_openai.py
mem0/llms/groq.py
mem0/llms/openai.py
mem0/llms/openai_structured.py
mem0/llms/together.py

This pr is aimed to solve these problems caused by `self.config_xxx = os.getnev('xxx') or self.config.xxx`.
https://github.com/mem0ai/mem0/blob/da2fd1a51a08b43a4fc84026cdb5170004d666e1/mem0/llms/openai.py#L24-L25
The implementation will continue to utilize the environment variables, even if we explicitly set the api_key or openai_base_url in the code.
Typically, we anticipate that our explicitly defined configurations should prevail. However, this is not the current behavior in our implementations. After spending hours debugging, I discovered expired environment variables, emphasizing the need for a more accurate approach.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list …

fix: get config from config value first then environment variable

---

mem0/configs/prompts.py

- Memory Save(deduced fact): Keep the memory's language same with input
Fixes #1817 

feat(memory): keep memory language

---

docs/components/llms/models/anthropic.mdx
mem0/llms/anthropic.py
mem0/llms/aws_bedrock.py
mem0/llms/azure_openai.py
mem0/llms/groq.py
mem0/llms/litellm.py
mem0/llms/ollama.py
mem0/llms/openai.py
mem0/llms/together.py
mem0/llms/utils/tools.py
mem0/utils/factory.py
mem0/vector_stores/chroma.py
mem0/vector_stores/pgvector.py

Add support standalone support for anthropic models. Previously it was provided through litellm.
```python
import os
os.environ["OPENAI_API_KEY"] = "sk-xx" # for embedding model
os.environ["ANTHROPIC_API_KEY"] = "sk-xx"
config = {
"llm": {
"provider": "anthropic"
}
}
m.add("Alice's favorite food is pizza", user_id="dev")
```

Add support for anthropic

---

docs/platform/quickstart.mdx

fix v2 search doc

---

embedchain/pyproject.toml

Release version of mem0ai changed for embedchain
closes https://github.com/mem0ai/mem0/issues/1791

[minor]: mem0ai version changed for embedchain

---

docs/components/llms/models/litellm.mdx
embedchain/configs/chroma.yaml
embedchain/configs/full-stack.yaml
embedchain/configs/opensearch.yaml
embedchain/docs/api-reference/advanced/configuration.mdx
embedchain/docs/components/llms.mdx
embedchain/docs/examples/rest-api/create.mdx
embedchain/docs/get-started/faq.mdx
embedchain/embedchain/config/model_prices_and_context_window.json
embedchain/embedchain/llm/azure_openai.py
embedchain/embedchain/llm/openai.py
embedchain/examples/chat-pdf/app.py
embedchain/examples/rest-api/sample-config.yaml
embedchain/notebooks/openai.ipynb
embedchain/tests/llm/test_azure_openai.py
embedchain/tests/llm/test_openai.py
mem0/llms/litellm.py
tests/test_proxy.py

feat: openai default model uses `gpt-4o-mini`

---

docs/components/llms/models/azure_openai.mdx
docs/components/llms/overview.mdx
docs/platform/quickstart.mdx
mem0/llms/ollama.py

The following updates have been made to the docs:
1. Added details about the v1.1 formatting for add/search/get_all calls
2. Difference between structured and unstructured output of Open AI models has been added

Doc Updates

---

pyproject.toml

chore: version -> `0.1.12`

---

mem0/configs/prompts.py

After some debugging, it has come down to these prompts haha.
The single quotes cause the facts, memories dictionary to be something like - 
`{"facts" : [\'Working on improving tennis skills\']}`
and just that additional `\` causes json decode errors for me.
sometimes though, the llms would return 
` '{\n "facts": ["Working on improving tennis skills"]\n}'` 
and everything would work fine.
The grok guy from the comments in issue has a similar problem - 
`'{"facts" : [\'Likes to have ice-cream after dinner\']}'`
I am changing the prompts so llm always double quotes the keys and values. 
**Let me know if you want to write that explicitly in the  prompt as well.**
Fixes #1841 
Please describe the tests that you ran to verify your changes. Provide …

Fixing memory adding errors 

---

docs/features/custom-prompts.mdx
docs/mint.json
mem0/configs/base.py
mem0/memory/main.py
pyproject.toml

Now users can define a custom prompt that can help them extract memories based on their use cases.

Added custom prompt support

---

mem0/llms/openai.py

In the initialization process of the `OpenAILLM`, the environment variables should be prioritized because there exists an initial value in the `BaseLlmConfig` already.
If not, setting the environment variable `OPENAI_API_BASE` does nothing and can not affect any of the configs, and the `base_url` of the `OpenAILLM` will be initialized with the value of `https://api.openai.com/v1`.
Fixes #1850
Specifying a base URL in the entrance of the project.
```python
os.environ["OPENAI_API_BASE"] = "https://dashscope.aliyuncs.com/compatible-mode/v1"
config = {
"embedder": {
"provider": "openai",
"config": {
"model": "qwen-long"
}
}
}
```
Simply adding a log (print, logger, etc) below the code can check whether `base_url` is correct. …

Fixed environment variables priority in OpenAILLM

---

docs/components/embedders/config.mdx
docs/components/embedders/models/vertexai.mdx
docs/components/embedders/overview.mdx
mem0/embeddings/configs.py
mem0/embeddings/litellm.py
mem0/embeddings/vertexai.py

Added support for  vertex ai embeddings 
Fixes #1827

Add Support for Vertex AI Embeddings

---

docs/api-reference/organization/add-org-member.mdx
docs/api-reference/organization/create-org.mdx
docs/api-reference/organization/delete-org-member.mdx
docs/api-reference/organization/delete-org.mdx
docs/api-reference/organization/get-org-members.mdx
docs/api-reference/organization/get-org.mdx
docs/api-reference/organization/get-orgs.mdx
docs/api-reference/organization/update-org-member.mdx
docs/api-reference/overview.mdx
docs/api-reference/project/add-project-member.mdx
docs/api-reference/project/create-project.mdx
docs/api-reference/project/delete-project-member.mdx
docs/api-reference/project/delete-project.mdx
docs/api-reference/project/get-project-members.mdx
docs/api-reference/project/get-project.mdx
docs/api-reference/project/get-projects.mdx
docs/api-reference/project/update-project-member.mdx
docs/mint.json
docs/openapi.json

Add API-Reference docs for Organization

Add API-Reference docs for Organization/Project

---

docs/openapi.json

Update docs for exisiting APIs to support organization/project.

Update docs for exisiting APIs to support organization/project

---

docs/openapi.json

Show all the possible responses for all the APIs in API-Reference section in docs.

Shows all responses in api-reference

---

pyproject.toml

chore: version -> 0.1.14

---

docs/open-source/graph_memory/overview.mdx
mem0/configs/vector_stores/chroma.py
mem0/memory/graph_memory.py
mem0/memory/telemetry.py
mem0/vector_stores/qdrant.py

Updated the docs for graph memory and corrected a few code formatting.

Docs update

---

docs/mint.json

update milvus docs

---

mem0/client/main.py
mem0/memory/telemetry.py
pyproject.toml

Changes:
- Remove stale code in events
- Add more attributes for events for better developer support

Remove stale code and events improvements

---

docs/components/llms/config.mdx
mem0/configs/llms/base.py
mem0/llms/openai.py
mem0/llms/openai_structured.py
tests/llms/test_openai.py

fix(llm): consume llm base url config with a better way

---

docs/integrations/langgraph.mdx

Change `Memory` -> `MemoryClient`

Fix langgraph doc

---

mem0/memory/main.py

If the new memory is not modified after `new_memories_with_actions`, we can utilise the embedding that were already created while `search`.
PR might reduce some latency.
Reference: https://discord.com/channels/1121119078191480945/1287035882624385035

[improvement]: Duplicate embedding generation removed.

---

pyproject.toml

chore: version -> 0.1.16

---

Makefile
tests/embeddings/test_vertexai_embeddings.py

Added test cases for Vertex AI embeddings.
Fixes #1902

Add vertexai test cases

---

mem0/client/main.py

Fix return types for client methods
Fixes #1912

Fix return types for client methods

---

docs/features/openai_compatibility.mdx

Add example to openai compatibility page in docs

Improve openai compatibility page

---

docs/features/openai_compatibility.mdx

multiline code for openai doc

---

mem0/llms/aws_bedrock.py

add-missing-response_format-parameter

---

mem0/memory/graph_memory.py
mem0/memory/main.py
pyproject.toml

Bug Fixes:
1. Graph Memory was not returning anything during the ADD call.
2. GET_ALL and SEARCH did not have wait statements.

Graph memory bug fix

---

poetry.lock
pyproject.toml

Changes:
- Mem0 Version -> 0.1.18
- Langchain community -> 0.3.1

version bump and update langchain-community

---

embedchain/poetry.lock
embedchain/pyproject.toml

Changes:
- Version bump for emebedchain -> 0.1.123
- Update all langchain dependencies 

Update langchain dependencies and version bump for embedchain

---

mem0/vector_stores/milvus.py

fixes - 1911 autoindex does not require params

---

pyproject.toml

chore: version -> 0.1.19

---

docs/platform/quickstart.mdx

Add custom_categories in get_all docs

---

docs/openapi.json

Reordering of code blocks for API reference page

---

docs/openapi.json

Update python code in API reference page.

update python code in API reference

---

mem0/memory/main.py
mem0/memory/storage.py
tests/test_main.py

[bug]: Memory.reset() deletes collection and table without re-creating it

---

docs/api-reference/memory/v1-get-memories.mdx
docs/api-reference/memory/v2-get-memories.mdx
docs/api-reference/memory/v2-search-memories.mdx
docs/mint.json
docs/openapi.json
docs/platform/quickstart.mdx
mem0/client/main.py

Add support for V2 get_all API

Add V2 get_all

---

README.md

Add npmjs package badge on README

---

docs/platform/quickstart.mdx
mem0/__init__.py
mem0/client/main.py
mem0/configs/base.py
mem0/embeddings/gemini.py
mem0/embeddings/huggingface.py
mem0/llms/gemini.py
mem0/llms/openai.py
mem0/memory/main.py
mem0/proxy/main.py
mem0/vector_stores/milvus.py

Add support for async Mem0 client.

Support async client

---

pyproject.toml

version-bump -> 0.1.22

---

docs/features/async-client.mdx
docs/mint.json

Update docs for showing the AsyncClient

Update docs for AsyncClient

---

mem0/client/main.py
pyproject.toml

Proper error message if api key not found and Version bump

Proper error message if api key not found

---

docs/open-source/quickstart.mdx

[docs]: Quickstart docs changed for v1.1 responses

---

embedchain/pyproject.toml
pyproject.toml

version bump -> 0.1.25

---

docs/platform/quickstart.mdx
mem0/client/main.py
pyproject.toml

Remove `session_id` deprecation warning and version bump.

Remove session_id deprecation warning

---

docs/components/embedders/models/together.mdx
docs/components/embedders/overview.mdx
mem0/embeddings/configs.py
mem0/embeddings/together.py
mem0/utils/factory.py

Ref: https://discord.com/channels/1121119078191480945/1300849088748589076/1300849088748589076

[integration]: Together embedder added

---

mem0/memory/graph_memory.py

Remove redudant code (relation_list) in graph_memory.py.
- Refactor (does not change functionality, e.g. code style improvements, linting)

remove redudant code from graph_memory.py

---

docs/platform/quickstart.mdx

Changes:
- Add deprecation warning that `v1.0` for add will be removed in `0.1.30`
- Add `categories` to API responses where required.

Modify docs to  update response format

---

mem0/memory/main.py

Set the `vectordb` response as the default for ADD calls. 

update ADD response

---

pyproject.toml

version bump -> 0.1.27

---

embedchain/docs/mint.json

Add audio as data source to Docs.

Add audio as data source to Docs

---

docs/api-reference/organization/add-org-member.mdx
docs/api-reference/organization/update-org-member.mdx
docs/api-reference/project/add-project-member.mdx
docs/api-reference/project/update-project-member.mdx
docs/openapi.json

Fixes for API reference

---

mem0/client/main.py
pyproject.toml

Changes:
- Version bump -> 0.1.29
- Fix client for Org_id

Version bump and client fixes

---

mem0/memory/graph_memory.py

If the given text is a question, LLM sometime answer the question instead of extracting entities.

refine prompt of graph memory extract entities for search

---

embedchain/poetry.lock
embedchain/pyproject.toml

Version bump and upgrade chromadb version.
Fixes #1982 

Version bump and upgrade chromadb version

---

docs/openapi.json

Updated Docs to include mem0-node functions.
Docs changes have been verified manually

(Docs) Updated Docs to include mem0-node

---

docs/integrations/crewai.mdx
docs/mint.json

Add a doc page showing how to use Mem0 with CrewAI.

Add CrewAI Usage doc

---

docs/platform/quickstart.mdx

add example for filtering through categories and metadata

Doc: add example for filtering through categories and metadata

---

docs/components/embedders/models/azure_openai.mdx
docs/components/embedders/models/gemini.mdx
docs/components/embedders/models/huggingface.mdx
docs/components/embedders/models/ollama.mdx
docs/components/embedders/models/together.mdx
docs/components/embedders/models/vertexai.mdx

Update embedder docs to show openai key is used for LLM

Update embedder docs to show openai key is used for LLM

---

mem0/memory/main.py
mem0/vector_stores/base.py

[bug_improvement]: Update hash changed and Vector base class improved

---

mem0/graphs/tools.py
mem0/graphs/utils.py
mem0/memory/graph_memory.py
mem0/memory/utils.py

Related issues: 
#1975 
#1906 
#1805

[improvement]: Graph nodes extraction improved

---

docs/platform/quickstart.mdx
docs/quickstart.mdx

(Docs Update) update mem0ai usage examples to use ES6 imports

---

docs/platform/quickstart.mdx
mem0/client/main.py

Handle pagination for GET_ALL

---

mem0/client/main.py

Pass `page` and `page_size` in query params

pass page and page_size in query params

---

docs/platform/quickstart.mdx

(Docs) Updated docs for new paginated output format

---

docs/platform/quickstart.mdx

(Docs) Updated Docs to Include V2 Paginated/Non-Paginated Output

---

docs/platform/quickstart.mdx

Support categories filtering for GET_ALL API

Support categories filtering for GET_ALL API

---

docs/openapi.json

Add page and page_size in api-reference

add page and page_size in api-reference

---

mem0/client/main.py
pyproject.toml

Add support for batch update/delete APIs

Add support for batch update/delete

---

docs/api-reference/memory/batch-delete.mdx
docs/api-reference/memory/batch-update.mdx
docs/mint.json
docs/openapi.json
docs/platform/quickstart.mdx

Update docs and API reference to show Batch Update/Delete APIs

Doc update

---

docs/features/custom-categories.mdx

update custom categories doc

---

docs/platform/quickstart.mdx

show proper format for sending data

Doc: Update batch delete

---

docs/features/custom-categories.mdx

Doc update for custom categories

Doc: update custom categories

---

docs/openapi.json

Added params Org/Proj ID to APIs and show the Org/Proj Name will be deprecated.

Doc: Add Org/Proj Id to API reference

---

docs/openapi.json

Added params:
- filter_memories
- categories
- only_metadata_based_search

Doc: Update V1 search params

---

docs/openapi.json

Doc: modify Update memory API

---

docs/openapi.json

Doc: show Token <api-key> in API-reference

Doc: show Token <api-key> in API-reference

---

vercel-ai-sdk/package.json
vercel-ai-sdk/src/mem0-chat-settings.ts
vercel-ai-sdk/src/mem0-utils.ts

- Added method to convert Vercel L1 Prompts to Mem0 format

(Update) Vercel AI SDK v0.0.10

---

docs/openapi.json

Doc: Update API reference

---

docs/overview.mdx

Updated the docs to mention the scenarios where Mem0 will not extract memories from certain text.

Updated docs about cases where memories will not be created

---

pyproject.toml

fix graph dependecies

---

embedchain/pyproject.toml
pyproject.toml

Update embedchain package and fix for mem0 package

Update embedchain package and fix for mem0 package

---

pyproject.toml

version bump -> 0.1.40

---

README.md

Included the commit tracking button for the repo.

Commit tracking

---

docs/features/langchain-tools.mdx
mem0/client/main.py
mem0/embeddings/together.py
mem0/graphs/tools.py
mem0/graphs/utils.py
mem0/llms/aws_bedrock.py
mem0/llms/gemini.py
mem0/memory/graph_memory.py
mem0/memory/main.py
mem0/memory/utils.py

Code formatting and doc update

Code formatting and doc update

---

docs/openapi.json

update api-reference for get_all

update api-reference for get_all

---

docs/components/vectordbs/dbs/pgvector.mdx
mem0/configs/vector_stores/pgvector.py
mem0/vector_stores/pgvector.py

Add HNSW support to pgvector
Fixes #2136 

HNSW support for pgvector

---

docs/components/vectordbs/overview.mdx
docs/mint.json
pyproject.toml

Doc: Update the ES doc to show up in directory
Version bump -> 0.1.42

Doc: Update ES and version bump

---

docs/api-reference/project/get-instructions-and-categories.mdx
docs/api-reference/project/update-instructions-and-categories.mdx
docs/features/custom-instructions.mdx

Doc: Custom instructions/Categories

Doc: Custom instructions/Categories

---

examples/vercel-ai-sdk-chat-app/components.json
examples/vercel-ai-sdk-chat-app/src/components/memories.tsx
examples/vercel-ai-sdk-chat-app/src/components/ui/avatar.tsx
examples/vercel-ai-sdk-chat-app/src/components/ui/badge.tsx
examples/vercel-ai-sdk-chat-app/src/components/ui/button.tsx
examples/vercel-ai-sdk-chat-app/src/components/ui/card.tsx
examples/vercel-ai-sdk-chat-app/src/components/ui/dialog.tsx
examples/vercel-ai-sdk-chat-app/src/components/ui/input.tsx
examples/vercel-ai-sdk-chat-app/src/components/ui/label.tsx
examples/vercel-ai-sdk-chat-app/src/components/ui/scroll-area.tsx
examples/vercel-ai-sdk-chat-app/src/components/ui/select.tsx
examples/vercel-ai-sdk-chat-app/src/contexts/GlobalContext.tsx
examples/vercel-ai-sdk-chat-app/src/libs/utils.ts

Fix lib/utils issue

---

docs/components/vectordbs/dbs/pgvector.mdx
docs/features.mdx
mem0/client/main.py
mem0/vector_stores/elasticsearch.py

Code formatting

---

docs/openapi.json
docs/platform/quickstart.mdx

Doc: Update V2 Search/GetAll docs

---

tests/vector_stores/test_elasticsearch.py

Fix pytests

---

pyproject.toml

version bump -> 0.1.46

---

docs/platform/quickstart.mdx

Doc: update delete_users

---

docs/components/llms/config.mdx
docs/components/llms/models/deepseek.mdx
docs/components/llms/overview.mdx
docs/overview.mdx
mem0/configs/llms/base.py
mem0/llms/configs.py
mem0/llms/deepseek.py
mem0/utils/factory.py
tests/llms/test_deepseek.py

Add support for Deepseek models

DeepSeek Integration

---

pyproject.toml

version bump - 0.1.48

---

docs/overview.mdx

Doc: update banner link

---

docs/open-source/quickstart.mdx

Update doc to show all config params for `Memory()` i.e OSS client
Fixes #2192

Doc: Add config params for Memory()

---

docs/overview.mdx
docs/platform/quickstart.mdx
docs/quickstart.mdx

Added Typescript Docs and fixed a broken url

---

docs/features/advanced-retrieval.mdx
docs/features/custom-categories.mdx

Docs update for custom categories.

updated custom categories docs

---

mem0/client/main.py
pyproject.toml

increase timeout and version bump

increase timeout and version bump

---

docs/api-reference/memory/v2-search-memories.mdx
docs/openapi.json
docs/platform/quickstart.mdx
docs/quickstart.mdx

Changes:
- Removed `hash` and `input`.
- Added `categories`

Doc: Update search output

---

README.md

Update client in README

---

tests/llms/test_azure_openai.py

Fixed the failing azure openai tests.

Fix Azure OpenAI test

---

docs/api-reference/overview.mdx

Update API reference to remove Org/Proj

Update API reference to remove Org/Proj

---

mem0/client/main.py

Proper error msg for API Key validation

Proper error msg for API Key validation

---

docs/docs.json
docs/features/webhook.mdx
mem0/client/main.py
pyproject.toml

Webhook Support

---

docs/features/webhook.mdx

Docs: Update webhook

---

docs/overview.mdx

Webhooks announcement in the overview page of Docs.

Docs: webhook announcement

---

docs/core-concepts/memory-operations.mdx
docs/core-concepts/memory-types.mdx
docs/docs.json
docs/overview.mdx

Docs: Docs updates

---

docs/integrations/vercel-ai-sdk.mdx

Update Docs for Mem0 AI SDK

---

docs/openapi.json

Added custom_instructions field in openapi specs

Updated docs

---

docs/components/vectordbs/dbs/redis.mdx

Update Redis doc to add `version="v1.1` in the config.

Doc: Update Redis config

---

examples/vercel-ai-sdk-chat-app/src/components/memories.tsx

Fix Build Errors

---

docs/features/webhook.mdx
mem0/client/main.py

Add event_types support in Webhook

Add event_types support in Webhook

---

docs/features/webhook.mdx
mem0/client/main.py

Project_id mandatory for Webhooks. First #2234 needs to be reviewed and merged.

Project_id mandatory for Webhooks

---

pyproject.toml

version bump -> 0.1.53

---

docs/api-reference/webhook/create-webhook.mdx
docs/api-reference/webhook/delete-webhook.mdx
docs/api-reference/webhook/get-webhook.mdx
docs/api-reference/webhook/update-webhook.mdx
docs/docs.json
docs/features/webhook.mdx
docs/openapi.json
mem0/client/main.py

Webhook API reference and update/delete function change. Now `update` and `delete` can be used without `project_id` param.

Webhook API reference and update/delete function change

---

pyproject.toml

version bump -> 0.1.54

---

docs/openapi.json
docs/platform/quickstart.mdx

Changes:
- Add immutable param to ADD
- Update the output format of Search/Get All

Docs: Add immutable param to ADD

---

mem0/client/main.py
mem0/configs/vector_stores/opensearch.py
mem0/memory/main.py
mem0/memory/telemetry.py
mem0/memory/utils.py
mem0/utils/factory.py
mem0/vector_stores/azure_ai_search.py
mem0/vector_stores/elasticsearch.py
mem0/vector_stores/opensearch.py

Formatting and Client changes

---

pyproject.toml

version bump -> 0.1.55

---

docs/features/webhook.mdx

Simplify the language and make the wording consistent for webhooks documentation.

improvement: Update webhook docs.

---

docs/features/multimodal-support.mdx

Simplify language, and make the wording consistent for multimodal support.

improvement: Update multimodal docs.

---

docs/docs.json
docs/features/async-client.mdx
docs/features/multimodal-support.mdx
docs/features/webhooks.mdx
docs/integrations/langchain-tools.mdx
docs/open-source/quickstart.mdx

Doc: api_key changes

---

docs/features/custom-categories.mdx
docs/features/selective-memory.mdx
docs/integrations/autogen.mdx
docs/integrations/langchain.mdx
docs/integrations/multion.mdx

Docs: set api_key to env

---

docs/integrations/crewai.mdx
docs/integrations/langchain-tools.mdx
docs/integrations/multion.mdx
docs/integrations/overview.mdx

Doc: fix integrations page

---

docs/components/llms/config.mdx
docs/components/llms/models/xai.mdx
docs/components/llms/overview.mdx
docs/docs.json
mem0/configs/llms/base.py
mem0/llms/configs.py
mem0/llms/xai.py
mem0/utils/factory.py

Add Grok Support

---

pyproject.toml

version bump -> 0.1.56

---

docs/components/llms/models/xai.mdx
docs/components/llms/overview.mdx
docs/docs.json

Doc: fix xai

---

docs/openapi.json
docs/platform/quickstart.mdx

Doc: upate v2 GetAll

---

docs/openapi.json

Doc: add param fields in v2 get_all

Doc: add param fields in v2 get_all

---

mem0/client/main.py
mem0/llms/configs.py
mem0/llms/xai.py
mem0/proxy/main.py

User_id creation for client and formatting

User_id creation for client and formatting

---

examples/vercel-ai-sdk-chat-app/package.json
examples/vercel-ai-sdk-chat-app/src/components/api-settings-popup.tsx
examples/vercel-ai-sdk-chat-app/src/constants/messages.ts
examples/vercel-ai-sdk-chat-app/src/contexts/GlobalContext.tsx
examples/vercel-ai-sdk-chat-app/src/hooks/useAuth.ts
examples/vercel-ai-sdk-chat-app/src/hooks/useChat.ts
examples/vercel-ai-sdk-chat-app/src/hooks/useFileHandler.ts
examples/vercel-ai-sdk-chat-app/src/utils/fileUtils.ts

Update AI SDK Example

---

tests/test_proxy.py

Fix proxy pytests

---

docs/components/llms/models/aws_bedrock.mdx
docs/components/llms/models/deepseek.mdx
docs/components/llms/models/gemini.mdx
docs/components/llms/models/google_AI.mdx
docs/components/llms/models/groq.mdx
docs/components/llms/models/litellm.mdx
docs/components/llms/models/openai.mdx
docs/components/llms/models/together.mdx
docs/components/llms/models/xAI.mdx
docs/examples/mem0-with-ollama.mdx
docs/features/custom-prompts.mdx
docs/integrations/llama-index.mdx
docs/open-source/graph_memory/overview.mdx
mem0/configs/llms/base.py
mem0/embeddings/azure_openai.py
mem0/embeddings/base.py
mem0/embeddings/gemini.py
mem0/embeddings/huggingface.py
mem0/embeddings/ollama.py
mem0/embeddings/openai.py
mem0/embeddings/together.py
mem0/embeddings/vertexai.py
mem0/llms/groq.py
mem0/llms/openai.py
tests/llms/test_azure_openai.py
tests/llms/test_deepseek.py

Update max_token and formatting

Update max_token and formatting

---

mem0/vector_stores/qdrant.py
pyproject.toml

fix deprecation warning: qdrant and version bump -> 0.1.58

fix deprecation warning: qdrant and version bump -> 0.1.58

---

docs/open-source/graph_memory/features.mdx
docs/open-source/graph_memory/overview.mdx
docs/open-source/python-quickstart.mdx
mem0/configs/base.py
mem0/memory/main.py
pyproject.toml
tests/test_main.py
tests/vector_stores/test_qdrant.py

Make api_version=v1.1 default and version bump -> 0.1.59

Make api_version=v1.1 default and version bump -> 0.1.59

---

pyproject.toml

version bump -> 0.1.60

---

tests/vector_stores/test_qdrant.py

Fix Qdrant Tests

---

docs/components/embedders/models/azure_openai.mdx
docs/components/embedders/models/gemini.mdx
docs/components/embedders/models/huggingface.mdx
docs/components/embedders/models/ollama.mdx
docs/components/embedders/models/openai.mdx
docs/components/embedders/models/together.mdx
docs/components/embedders/models/vertexai.mdx
docs/components/llms/models/anthropic.mdx
docs/components/llms/models/aws_bedrock.mdx
docs/components/llms/models/azure_openai.mdx
docs/components/llms/models/deepseek.mdx
docs/components/llms/models/gemini.mdx
docs/components/llms/models/google_AI.mdx
docs/components/llms/models/groq.mdx
docs/components/llms/models/litellm.mdx
docs/components/llms/models/mistral_AI.mdx
docs/components/llms/models/ollama.mdx
docs/components/llms/models/openai.mdx
docs/components/llms/models/together.mdx
docs/components/llms/models/xAI.mdx
docs/components/vectordbs/dbs/azure_ai_search.mdx
docs/components/vectordbs/dbs/chroma.mdx
docs/components/vectordbs/dbs/elasticsearch.mdx
docs/components/vectordbs/dbs/milvus.mdx
docs/components/vectordbs/dbs/opensearch.mdx
docs/components/vectordbs/dbs/pgvector.mdx
docs/components/vectordbs/dbs/qdrant.mdx
docs/components/vectordbs/dbs/redis.mdx

Doc: Update examples in LLMs, VectorDBs and Embedding models pages

Doc: Update examples in LLMs, VectorDBs and Embedding models pages

---

docs/contributing/development.mdx
docs/contributing/documentation.mdx
docs/docs.json

Add contribution docs

---

mem0/memory/utils.py
pyproject.toml

fix multimodal functionality and version bump -> 0.1.62

fix multimodal functionality and version bump -> 0.1.62

---

docs/open-source/graph_memory/features.mdx
docs/open-source/graph_memory/overview.mdx
mem0-ts/package.json
mem0-ts/src/oss/examples/basic.ts
mem0-ts/src/oss/src/config/defaults.ts
mem0-ts/src/oss/src/config/manager.ts
mem0-ts/src/oss/src/graphs/configs.ts
mem0-ts/src/oss/src/graphs/tools.ts
mem0-ts/src/oss/src/graphs/utils.ts
mem0-ts/src/oss/src/llms/base.ts
mem0-ts/src/oss/src/llms/openai.ts
mem0-ts/src/oss/src/llms/openai_structured.ts
mem0-ts/src/oss/src/memory/graph_memory.ts
mem0-ts/src/oss/src/memory/index.ts
mem0-ts/src/oss/src/memory/memory.types.ts
mem0-ts/src/oss/src/prompts/index.ts
mem0-ts/src/oss/src/types/index.ts
mem0-ts/src/oss/src/utils/bm25.ts
mem0-ts/src/oss/src/utils/factory.ts
mem0-ts/src/oss/src/utils/logger.ts
mem0-ts/src/oss/src/vector_stores/memory.ts

Graph Support for NodeSDK

---

docs/faqs.mdx

Add AWS lambda issue to FAQ

---

README.md
docs/docs.json
docs/examples/mem0-demo.mdx
docs/open-source/graph_memory/overview.mdx
docs/open-source/node-quickstart.mdx
docs/open-source/python-quickstart.mdx
examples/mem0-demo/app/assistant.tsx
examples/mem0-demo/app/layout.tsx
examples/mem0-demo/components/assistant-ui/thread-list.tsx
examples/mem0-demo/components/assistant-ui/thread.tsx
examples/mem0-demo/public/images/assistant-ui-dark.svg
examples/mem0-demo/public/images/assistant-ui.svg

Updated Docs to add Mem0 Demo Link/ Updated Mem0 Demo

---

pyproject.toml

version bump -> 0.1.64

---

docs/platform/quickstart.mdx

Doc: Update doc for both user and agent

Doc: Update doc for both user and agent

---

README.md

The sample code on README.md seems outdate, the search API retrun a dict with `results` field for now.
https://github.com/mem0ai/mem0/blob/431866369749479bcc100ba4491a040fd2986e07/mem0/memory/main.py#L444
No need

fix: fix sample code on README.md

---

.github/workflows/cd.yml

CD changes

---

docs/features/multimodal-support.mdx
docs/open-source/multimodal-support.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.ts
mem0-ts/src/client/mem0.types.ts
mem0-ts/src/oss/src/llms/anthropic.ts
mem0-ts/src/oss/src/llms/groq.ts
mem0-ts/src/oss/src/llms/openai.ts
mem0-ts/src/oss/src/llms/openai_structured.ts
mem0-ts/src/oss/src/memory/index.ts
mem0-ts/src/oss/src/types/index.ts
mem0-ts/src/oss/src/utils/memory.ts

Multimodal Support NodeSDK

---

docs/docs.json
docs/integrations/cursor.mdx
docs/integrations/mcp-server.mdx
docs/integrations/overview.mdx

Doc: Mem0 mcp with cursor

---

docs/docs.json
docs/integrations/chrome-extension.mdx
docs/integrations/overview.mdx

Doc: Chrome extension

---

mem0/memory/utils.py

Enhanced the prompt for detecting description from the image during multimodal setting.

Changed multimodal prompt to extract better text from images

---

mem0/memory/main.py

Catch json error for new_memories_with_action

Catch json error for new_memories_with_action

---

mem0/memory/main.py

Fixes for new_memories_with_actions

Fixes for new_memories_with_actions

---

docs/docs.json
docs/examples/document-writing.mdx
docs/examples/overview.mdx

Doc: Document editing with Mem0

Doc: Document editing with Mem0

---

mem0/memory/main.py

Handle empty  field in new_memories_with_actions

---

docs/docs.json
docs/examples/multimodality.mdx
docs/examples/overview.mdx

Doc: Multimodality usecase

---

docs/components/vectordbs/overview.mdx
docs/docs.json

Fixing the documentation for `vertex_ai_vector_search`.

[ Fix ] for the vertex_ai_vector_search documentation

---

pyproject.toml

version bump -> 0.1.66

---

docs/docs.json
docs/examples/document-writing.mdx
docs/examples/multimodal-demo.mdx
docs/examples/overview.mdx
docs/examples/personalized-deep-research.mdx

Doc: update examples name

---

docs/examples/overview.mdx

Doc: update examples page

---

pyproject.toml

version bump -> 0.1.67

---

examples/mem0-demo/app/assistant.tsx
examples/mem0-demo/components/assistant-ui/thread-list.tsx
examples/mem0-demo/components/assistant-ui/thread.tsx

Updated Demo

---

docs/docs.json
docs/examples/mem0-agentic-tool.mdx
docs/examples/overview.mdx

Add integration cookbook for Mem0 + OpenAI Agents SDK
This PR introduces a new MDX cookbook demonstrating how to combine Mem0's memory capabilities with OpenAI's Agents SDK. The cookbook provides step-by-step instructions for creating AI agents with persistent memory, including:
- Complete setup and installation guidance
- Implementation of memory management tools (add, search, retrieve)

Added agentic tool in docs

---

docs/docs.json
docs/examples/openai-inbuilt-tools.mdx
docs/examples/overview.mdx
examples/openai-inbuilt-tools/index.js
examples/openai-inbuilt-tools/package.json

OpenAI Inbuilt Tools

---

pyproject.toml

version bump -> 0.1.68

---

mem0/llms/anthropic.py
mem0/llms/aws_bedrock.py
mem0/llms/azure_openai.py
mem0/llms/azure_openai_structured.py
mem0/llms/configs.py
mem0/llms/deepseek.py
mem0/llms/gemini.py
mem0/llms/groq.py
mem0/llms/litellm.py
mem0/llms/ollama.py
mem0/llms/openai.py
mem0/llms/openai_structured.py
mem0/llms/together.py
mem0/llms/xai.py
tests/llms/test_azure_openai.py
tests/llms/test_deepseek.py
tests/llms/test_gemini_llm.py
tests/llms/test_groq.py
tests/llms/test_litellm.py
tests/llms/test_openai.py
tests/llms/test_together.py

Removed the use of `tools` from all LLMs, also removed unnecessary LLM test cases.
Fixes #2283 
Tested locally with the test cases.

Remove `tools` from LLMs

---

mem0-ts/package.json
mem0-ts/src/client/mem0.types.ts
mem0-ts/src/client/telemetry.browser.ts

Added Custom Categories in Mem0-TS

---

examples/mem0-demo/app/assistant.tsx
examples/mem0-demo/components/assistant-ui/thread.tsx
examples/mem0-demo/components/mem0/github-button.tsx
mem0-ts/package.json
mem0-ts/src/client/mem0.ts
mem0-ts/src/client/mem0.types.ts

**Changes for demo.mem0.ai**
- New Responsive UI for demo.mem0.ai
- Auto-focus on Selecting Suggestions
**Changes for Mem0 TS SDK**
- Support for api_version

Make DEMO UI Responsive

---

mem0/client/main.py
mem0/memory/main.py

Neo4j embeddings error

---

docs/open-source/python-quickstart.mdx
mem0/memory/main.py
pyproject.toml
tests/test_main.py

Add an `infer` parameter to the `Add` method to store messages as they are in memory.. Also bumped up the version.

Add infer param and version bump

---

mem0-ts/package.json
mem0-ts/src/oss/src/vector_stores/redis.ts

Fix Redis Search

---

docs/open-source/python-quickstart.mdx

Doc: update oss quickstart page

Doc: update oss quickstart page

---

mem0/llms/azure_openai_structured.py
mem0/llms/openai_structured.py

Add back support for tools in `azure_openai_structured` and `openai_structured`.
Fixes #2397

Fix: made tools support for graph

---

pyproject.toml

version bump -> 0.1.71

---

pyproject.toml

version bump -> 0.1.72

---

pyproject.toml

bump version -> 0.1.73

---

docs/components/vectordbs/dbs/azure_ai_search.mdx
docs/components/vectordbs/dbs/pinecone.mdx

Updated VDB Docs

---

docs/openapi.json

Update Node SDK Docs for Update Method

---

docs/docs.json
docs/examples/mem0-openai-voice-demo.mdx
docs/examples/overview.mdx

Doc: Openai Agents SDK voice demo

Openai Agents SDK voice demo

---

mem0-ts/package.json
mem0-ts/src/community/.prettierignore
mem0-ts/src/community/package.json
mem0-ts/src/community/src/index.ts
mem0-ts/src/community/src/integrations/langchain/index.ts
mem0-ts/src/community/src/integrations/langchain/mem0.ts
mem0-ts/src/community/tsconfig.json

Adds Langchain Community Package

---

docs/components/embedders/config.mdx
docs/components/embedders/models/lmstudio.mdx
docs/components/embedders/overview.mdx
docs/components/llms/config.mdx
docs/components/llms/models/lmstudio.mdx
docs/components/llms/overview.mdx
mem0/configs/embeddings/base.py
mem0/configs/llms/base.py
mem0/embeddings/configs.py
mem0/embeddings/lmstudio.py
mem0/llms/configs.py
mem0/llms/lmstudio.py
mem0/utils/factory.py
tests/embeddings/test_lm_studio_embeddings.py
tests/llms/test_lm_studio.py

Add LM Studio support

---

pyproject.toml

version bump -> 0.1.75

---

tests/vector_stores/test_azure_ai_search.py

Fixed Azure AI Search test cases
Fixes #2406 
Locally with unit tests.

fix-azure-ai-search-test-cases

---

docs/components/llms/models/azure_openai.mdx
docs/components/vectordbs/dbs/pinecone.mdx
mem0/llms/azure_openai.py
tests/vector_stores/test_pinecone.py

Fixed the supported parameters for the reasoning models by `azure openaii`. Fixed failing tests for pinecone.
Fixes #2420 

Azure openai fixes

---

docs/open-source/node-quickstart.mdx
mem0-ts/package.json
mem0-ts/src/oss/src/config/defaults.ts
mem0-ts/src/oss/src/config/manager.ts
mem0-ts/src/oss/src/memory/index.ts
mem0-ts/src/oss/src/storage/DummyHistoryManager.ts
mem0-ts/src/oss/src/storage/MemoryHistoryManager.ts
mem0-ts/src/oss/src/storage/SQLiteManager.ts
mem0-ts/src/oss/src/storage/SupabaseHistoryManager.ts
mem0-ts/src/oss/src/storage/base.ts
mem0-ts/src/oss/src/storage/index.ts
mem0-ts/src/oss/src/types/index.ts
mem0-ts/src/oss/src/utils/factory.ts
mem0-ts/src/oss/src/vector_stores/supabase.ts

Add Supabase History DB to run Mem0 OSS on Serverless

---

docs/api-reference/memory/feedback.mdx
docs/docs.json
docs/features/feedback-mechanism.mdx
docs/openapi.json
mem0/client/main.py

Add feeback method to client and doc changes

Add feeback method to client and doc changes

---

mem0/vector_stores/azure_ai_search.py
pyproject.toml

Changes:
- fix for Azure AI
-  version bump -> 0.1.76
Fixes #2431

fix for Azure AI and version bump -> 0.1.76

---

docs/components/vectordbs/dbs/supabase.mdx
mem0-ts/package.json
mem0-ts/src/oss/src/vector_stores/supabase.ts

docs(supabase-ts): Update Docs for Supabase TS

---

docs/features/multimodal-support.mdx

Added support for document file types (MDX, TXT, and PDF) to the multimodal capabilities. Updated documentation to include examples for integrating these document types via URL and Base64 encoding methods, alongside the existing image support. This enhancement allows users to extract information from various document formats, significantly expanding Mem0's multimodal functionality.

Updated multimodal docs

---

docs/docs.json
docs/examples/overview.mdx
docs/integrations/elevenlabs.mdx
docs/integrations/livekit.mdx
docs/integrations/overview.mdx

Changes:
- Update API reference section to show project APIs
-  Add elevenlabs example

Doc: Update API reference section and Add elevenlabs example

---

docs/openapi.json

doc: update API reference for expiration_date

doc: update API reference for expiration_date

---

docs/changelog/overview.mdx
docs/docs.json

Doc: Add changelog

---

docs/docs.json
docs/examples/email_processing.mdx
docs/examples/overview.mdx

Doc: Add example for email processing

Doc: Add example for email processing

---

Makefile
docs/components/vectordbs/dbs/faiss.mdx
docs/components/vectordbs/overview.mdx
mem0/configs/vector_stores/faiss.py
mem0/utils/factory.py
mem0/vector_stores/configs.py
mem0/vector_stores/faiss.py
pyproject.toml
tests/vector_stores/test_faiss.py

Add Faiss Support

---

docs/changelog/overview.mdx
pyproject.toml

bump version -> 0.1.79

---

docs/docs.json

update for faiss doc

---

mem0/__init__.py
mem0/configs/enums.py
mem0/configs/prompts.py
mem0/configs/vector_stores/azure_ai_search.py
mem0/configs/vector_stores/supabase.py
mem0/configs/vector_stores/weaviate.py
mem0/memory/main.py
mem0/memory/storage.py
mem0/vector_stores/supabase.py
pyproject.toml

Adds support for procedural memory for AI Agents.

Add support for procedural memory

---

mem0/configs/prompts.py
mem0/memory/main.py
mem0/vector_stores/faiss.py
pyproject.toml

Minor fixes in procedural memory

---

docs/changelog/overview.mdx
vercel-ai-sdk/package.json
vercel-ai-sdk/pnpm-lock.yaml
vercel-ai-sdk/src/mem0-generic-language-model.ts
vercel-ai-sdk/src/mem0-types.ts
vercel-ai-sdk/src/mem0-utils.ts

**New Features:**
- **Vercel AI SDK Update:** Support threshold and rerank
**Improvements:**
- **Made add calls async to avoid blocking**
- **Bump `mem0ai` to use `2.1.12`**
Also introduces lock file
Ran the Unit Tests

AI SDK Updates

---

docs/changelog/overview.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.ts

- **Introuced `ping` method to check if API key is valid and populate org/project id**

Introduce Ping in Mem0 Client

---

examples/mem0-demo/app/api/chat/route.ts
examples/mem0-demo/package.json

Update Demo Mem0AI to use Reranking and Min Threshold

Update Demo Mem0AI

---

docs/docs.json
docs/examples/mem0-mastra.mdx
docs/integrations/vercel-ai-sdk.mdx

Added Mastra Example

---

docs/components/vectordbs/dbs/azure.mdx
docs/components/vectordbs/dbs/vertex_ai.mdx
docs/components/vectordbs/overview.mdx
docs/docs.json

Fix doc links for Azure and Vertex AI search.

doc: fix links

---

docs/docs.json
docs/integrations/flowise.mdx

This pull request updates the documentation for the Mem0 Memory integration with Flowise. The enhancements include:
- Overview Section: Added a brief introduction to the Mem0 Memory integration, highlighting its key features and benefits for users.
- Setup and Configuration: Detailed steps for setting up Flowise and configuring Mem0, including obtaining the Mem0 API Key and entering credentials.
- Memory Features: Included instructions for testing memory storage and validating memory retention, ensuring users can effectively utilize the integration.
- Advanced Configuration: Provided insights into advanced memory settings and platform configuration options to optimize user experience.
- Best Practices: Added recommendations for user identification, memory organization, and regular …

docs: Flowise Integration Documentation for Mem0 Memory Setup

---

docs/platform/quickstart.mdx
mem0/client/main.py

Set output_format='v1.1' and update docs

Set output_format='v1.1' and update docs

---

docs/docs.json

Adds lmstudio and together embedders to sidebar.
Fixes #2483 

adding lmstudio and together in docs

---

docs/docs.json
docs/integrations/overview.mdx
docs/integrations/pipecat.mdx

Doc: pipecat integration

---

docs/openapi.json

Doc: update output_format

---

docs/components/llms/config.mdx
docs/components/llms/models/langchain.mdx
docs/components/llms/overview.mdx
docs/docs.json
mem0/configs/llms/base.py
mem0/llms/configs.py
mem0/llms/langchain.py
mem0/utils/factory.py
tests/llms/test_langchain.py

Support for langchain LLMs

---

mem0/memory/graph_memory.py
mem0/memory/main.py
poetry.lock
pyproject.toml

Formatting and version bump -> 0.1.82

Formatting and version bump -> 0.1.82

---

Makefile
docs/changelog/overview.mdx
mem0/llms/langchain.py
pyproject.toml

Changes:
- Update changelog
- Fix langchain for Anthropic models
- Version bump -> 0.1.83

Fix langchain llm and update changelog

---

mem0/configs/vector_stores/faiss.py
mem0/vector_stores/faiss.py
pyproject.toml

Add embeding_dims param to FAISS and version bump -> 0.1.86
Fixes #2505

Add embeding_dims param to FAISS

---

docs/openapi.json

Fix Batch API docs, as the URL and body was wrong

Fix Batch API docs

---

Makefile
docs/components/vectordbs/config.mdx
docs/components/vectordbs/dbs/upstash-vector.mdx
docs/components/vectordbs/overview.mdx
mem0/configs/vector_stores/upstash_vector.py
mem0/embeddings/mock.py
mem0/memory/main.py
mem0/utils/factory.py
mem0/vector_stores/configs.py
mem0/vector_stores/upstash_vector.py
tests/vector_stores/test_upstash_vector.py

This PR adds support for [Upstash Vector](https://upstash.com/docs/vector/overall/whatisvector).
This PR also has support for built-in [upstash embeddings](https://upstash.com/docs/vector/features/embeddingmodels).
```py
m = Memory.from_config(
{
"provider": "upstash_vector",
"config": {
"url": os.getenv("UPSTASH_VECTOR_REST_URL"),
"token": os.getenv("UPSTASH_VECTOR_REST_TOKEN"),
"enable_embeddings": True,
},
},
}
)
```
To add support for this, I needed a way to bypass the current embedding model.
I added a new class `MockEmbeddings` which generates the same vector, and used it when upstash embeddings are enabled. Please see `main/memory.py`.
I evaluated adding if cases to skip the usage of the embedding model, but the first approach is much cleaner.
Please delete …

Add Upstash Vector support

---

mem0/memory/main.py

Remove redundant lines

---

docs/api-reference/memory/get-memory-export.mdx
docs/docs.json
docs/features/memory-export.mdx
docs/openapi.json
mem0/client/main.py

Changes: 
- Doc: update memory export
- Update get_memory_export in Client

Doc: update memory export

---

docs/changelog/overview.mdx
mem0-ts/package.json
mem0-ts/pnpm-lock.yaml
mem0-ts/src/client/telemetry.ts
mem0-ts/src/oss/src/llms/google.ts
mem0-ts/src/oss/src/memory/index.ts
mem0-ts/src/oss/src/utils/telemetry.ts
mem0-ts/src/oss/src/utils/telemetry.types.ts
mem0-ts/src/oss/src/vector_stores/base.ts
mem0-ts/src/oss/src/vector_stores/memory.ts
mem0-ts/src/oss/src/vector_stores/pgvector.ts
mem0-ts/src/oss/src/vector_stores/qdrant.ts
mem0-ts/src/oss/src/vector_stores/redis.ts
mem0-ts/src/oss/src/vector_stores/supabase.ts

Add user_id in TS OSS SDK

---

pyproject.toml

version bump -> 0.1.87

---

docs/changelog/overview.mdx

update python changelog

---

mem0/embeddings/huggingface.py

Suppress the INFO logs from HuggingFace

Handle HF logging

---

pyproject.toml

version bump -> 0.1.88

---

docs/examples/personal-ai-tutor.mdx
docs/examples/personal-travel-assistant.mdx

Doc: modify 2 examples to show OpenAIResponses API

Doc: modify 2 examples to show OpenAIResponses API

---

mem0/memory/graph_memory.py
mem0/memory/main.py

Formatting

---

docs/docs.json
docs/integrations/agno.mdx
docs/integrations/overview.mdx

Doc: Add agno example

---

examples/misc/personal_assistant_agno.py

This is a quickstart example to create your personal AI Assistant powered by memory that supports both text and images and remembers your preferences.
Built using Agno and Mem0.

personal assistant

---

pyproject.toml

version bump -> 0.1.89

---

docs/features/selective-memory.mdx

Memory exclusion example in the doc didn't reflect the correct parameter

Fix: memory exclusion example in doc

---

docs/components/llms/models/xAI.mdx
docs/overview.mdx

Doc; Update xAI doc

---

docs/docs.json
docs/integrations/keywords.mdx
docs/integrations/overview.mdx

Doc: Add keywords AI

---

examples/misc/movie_recommendation_grok3.py

Memory-Powered Movie Recommendation Assistant (Grok 3 + Mem0) This script builds a personalized movie recommender that remembers your preferences (e.g. dislikes horror, loves romcoms) using Mem0 as a memory layer and Grok 3 for responses.
In order to run this file, you need to set up your Mem0 API at Mem0 platform and also need an XAI API key.
export XAI_API_KEY="your_xai_api_key"
export MEM0_API_KEY="your_mem0_api_key"

movie recommendation using grok3

---

docs/changelog.mdx

Doc: update changelog

---

examples/misc/voice_assistant_elevenlabs.py

Personal Voice Assistant with Memory (Whisper + CrewAI + Mem0 + ElevenLabs) This script creates a personalized AI assistant that can:
- Understand voice commands using Whisper (OpenAI STT)
- Respond intelligently using CrewAI Agents and OpenAI LLM
- Remember user preferences and facts using Mem0 memory
- Speak responses back using ElevenLabs text-to-speech

Voice Assistant using Elevenlabs

---

docs/changelog.mdx
docs/components/embedders/models/langchain.mdx
docs/components/llms/models/langchain.mdx
docs/components/vectordbs/dbs/langchain.mdx
mem0-ts/package.json
mem0-ts/pnpm-lock.yaml
mem0-ts/src/oss/src/config/defaults.ts
mem0-ts/src/oss/src/config/manager.ts
mem0-ts/src/oss/src/embeddings/langchain.ts
mem0-ts/src/oss/src/graphs/tools.ts
mem0-ts/src/oss/src/index.ts
mem0-ts/src/oss/src/llms/base.ts
mem0-ts/src/oss/src/llms/langchain.ts
mem0-ts/src/oss/src/memory/index.ts
mem0-ts/src/oss/src/prompts/index.ts
mem0-ts/src/oss/src/types/index.ts
mem0-ts/src/oss/src/utils/factory.ts
mem0-ts/src/oss/src/vector_stores/langchain.ts

TypeScript OSS: Langchain Integration

TypeScript OSS: Langchain Integration

---

mem0/vector_stores/faiss.py
pyproject.toml

silence faiss info logs

---

mem0/memory/main.py
mem0/memory/storage.py
tests/test_main.py

Memory Reset

---

examples/misc/fitness_checker.py

Simple Fitness Memory Tracker that tracks your fitness progress and knows your health priorities. Uses Mem0 for memory and GPT-4o for image understanding.
In order to run this file, you need to set up your Mem0 API on Mem0 platform and also need an OpenAI API key. export OPENAI_API_KEY="your_openai_api_key"
export MEM0_API_KEY="your_mem0_api_key"

Fitness Checker powered by memory

---

docs/changelog.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.types.ts

Add Support for Custom Instructions

Add Support for Custom Instructions

---

docs/openapi.json

Doc: fix curl for v2 get_all

---

mem0/memory/setup.py
mem0/vector_stores/elasticsearch.py
mem0/vector_stores/opensearch.py
mem0/vector_stores/pgvector.py
mem0/vector_stores/qdrant.py
mem0/vector_stores/redis.py
mem0/vector_stores/weaviate.py

Init embedding_model_dims in all vectordbs

Init embedding_model_dims in all vectordbs

---

docs/integrations/agno.mdx

Doc: fix agno link

---

pyproject.toml

version bump -> 0.1.93

---

docs/changelog.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.types.ts

Added Timestamp

---

docs/api-reference/memory/v2-search-memories.mdx

Doc: fix v2 search

---

pyproject.toml

version bump -> 0.1.94

---

docs/overview.mdx

Removed Grok3 Announcement

---

docs/changelog.mdx
mem0-ts/package.json
mem0-ts/pnpm-lock.yaml
mem0-ts/src/oss/src/vector_stores/pgvector.ts

Bumped Anthropic SDK Version

---

docs/openapi.json

Doc: fix timestamp

---

README.md

Doc: Fix README links

---

docs/changelog.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.ts

Updated TS client to use proper types for deleteUsers

Updated TS client to use proper types for deleteUsers

---

mem0/proxy/main.py

Fix proxy for Mem0

---

docs/components/embedders/models/huggingface.mdx
mem0/configs/embeddings/base.py
mem0/embeddings/huggingface.py
pyproject.toml

Support for HF Inference

---

vercel-ai-sdk/package.json
vercel-ai-sdk/src/mem0-utils.ts

The filtering pattern was incorrect, which caused the entities to be filtered using an OR condition instead of AND. We’ll be releasing a patch soon.

Fix AI SDK Filters

---

docs/changelog.mdx
docs/platform/quickstart.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.ts

Updated `deleteUsers` to use `V2` API Endpoints

Updated `deleteUsers` to use `V2` API Endpoints

---

docs/features/timestamp.mdx

Doc: update timestamp

---

docs/changelog.mdx
docs/features/graph-memory.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.types.ts

Added New Param, output_format

Added New Param, output_format

---

mem0/graphs/configs.py
mem0/memory/graph_memory.py

Adding `database` config to neo4j

Add support for neo4j database

---

mem0/memory/graph_memory.py

- Use db.create.setNodeVectorProperty to store embeddings
- Switch to procedure for cosine similarity

Improve neo4j queries

---

docs/components/llms/models/azure_openai.mdx

Doc: update azure ai

---

docs/changelog.mdx
docs/examples/mem0-demo.mdx
examples/mem0-demo/app/api/chat/route.ts
examples/mem0-demo/app/assistant.tsx
examples/mem0-demo/next.config.ts
examples/mem0-demo/package.json
vercel-ai-sdk/package.json
vercel-ai-sdk/src/mem0-types.ts

Added Missing Param in AI SDK and Updated Demo Application

Added Missing Param in AI SDK and Updated Demo Application

---

docs/docs.json
docs/examples/eliza_os.mdx

Added ElizaOS Example

---

openmemory/ui/.env.example
openmemory/ui/components/dashboard/Install.tsx
openmemory/ui/hooks/useAppsApi.ts
openmemory/ui/hooks/useFiltersApi.ts
openmemory/ui/hooks/useMemoriesApi.ts
openmemory/ui/hooks/useStats.ts

Fix Backend Link in OpenMemory

 Fix Backend Link in OpenMemory

---

openmemory/api/app/mcp_server.py
openmemory/api/app/routers/memories.py

Fixed an issue where memories added via the Dashboard or Open Memory UI were not showing in the MCP client. This was due to improper saving in Qdrant—vectors/payloads were not correctly handled.
* Fixed Qdrant write logic to ensure proper memory indexing.
* Added correct route handling for `POST /messages` for both old (`/message`) and new (`/{client_name}/sse/{user_id}/messages/`) endpoints.
* Unified memory saving across all entry points.
All new memories now appear consistently in the MCP client, regardless of how they're added.

fix(OMM): Memories not appearing in MCP clients added from Dashboard

---

docs/examples/mem0-google-adk-healthcare-assistant.mdx
examples/misc/healthcare_assistant_google_adk.py

Added a Healthcare Assistant example for using Mem0 with Google ADK.

Healthcare assistant using Mem0 and Google ADK

---

pyproject.toml

version bump -> 0.1.100

---

docs/docs.json
docs/examples.mdx

Updated the index for adding Healthcare Example in docs

Update Index of Healthcare Example in docs

---

docs/docs.json
docs/features/criteria-retrieval.mdx
mem0/vector_stores/opensearch.py
tests/test_main.py

- Added detailed comparison between v1 and v2 search results with example outputs
- Clarified behavior of v2 search when no criteria are set
- Improved formatting and structure of code examples
- Added practical examples showing how criteria-based filtering affects search results
- Simplified score display in example outputs for better readability
1. **Clear Comparison**: Added side-by-side comparison of v1 and v2 search results, showing how criteria-based filtering affects memory ordering and scoring
2. **Behavior Clarification**: Added note explaining that v2 behaves like v1 when no criteria are set
3. **Practical Examples**: Added real-world examples demonstrating:
- How joy-based memories are prioritized in v2
- How negative content is scored differently
- How curiosity-based content …

Added docs for criteria based filtering

---

mem0/graphs/configs.py
mem0/memory/graph_memory.py

When adding base label `__Entity__` to the graph, we can index user_id and a combination of user_id and name for faster imports and retrieval

Add neo4j base label config

---

docs/openmemory/overview.mdx
docs/openmemory/quickstart.mdx
openmemory/README.md
openmemory/api/.dockerignore
openmemory/run.sh
openmemory/ui/.dockerignore

Added CurL Command to Easy Install OMM
`curl -sL https://raw.githubusercontent.com/mem0ai/mem0/main/openmemory/run.sh | bash`
Main Command After this PR is merged
`curl -sL https://raw.githubusercontent.com/whysosaket/mem0/omm/curl-intsaller/openmemory/run.sh | bash`

improvement(OMM): Added CurL Command to Easy Install OMM

---

docs/openapi.json

Doc: Update output of Org/Proj creation APIs

Doc: Update output of Org/Proj creation APIs

---

docs/changelog.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.ts
mem0-ts/src/client/mem0.types.ts
mem0-ts/src/client/telemetry.ts
mem0-ts/src/oss/src/utils/telemetry.ts

Fixed Types from Message Interface

fix(ts-sdk): Fixed Types from Message Interface

---

docs/components/llms/models/anthropic.mdx
docs/overview.mdx
docs/quickstart.mdx

Doc: announce claude 4

---

docs/changelog.mdx
vercel-ai-sdk/src/mem0-provider-selector.ts
vercel-ai-sdk/src/provider-response-provider.ts
vercel-ai-sdk/tests/mem0-provider-tests/mem0-google.test.ts
vercel-ai-sdk/tests/mem0-provider-tests/mem0-openai-structured-ouput.test.ts
vercel-ai-sdk/tests/text-properties.test.ts
vercel-ai-sdk/tests/utils-test/google-integration.test.ts

Added Support for Google Provider in AI SDK

feat(ai-sdk): Added Support for Google Provider in AI SDK

---

docs/openapi.json

Doc: update messages in api reference

Doc: update messages in api reference

---

openmemory/api/app/mcp_server.py

Fix: Typo in openmemory MCP tool description

Fix: Typos in openmemory MCP tool description

---

openmemory/api/Dockerfile
openmemory/api/alembic/versions/add_config_table.py
openmemory/api/app/mcp_server.py
openmemory/api/app/models.py
openmemory/api/app/routers/__init__.py
openmemory/api/app/routers/config.py
openmemory/api/app/routers/memories.py
openmemory/api/app/utils/memory.py
openmemory/api/config.json
openmemory/api/default_config.json
openmemory/api/main.py
openmemory/api/requirements.txt
openmemory/docker-compose.yml
openmemory/ui/app/settings/page.tsx
openmemory/ui/components/Navbar.tsx
openmemory/ui/components/form-view.tsx
openmemory/ui/components/json-editor.tsx
openmemory/ui/hooks/useConfig.ts
openmemory/ui/store/configSlice.ts
openmemory/ui/store/store.ts

Add support for LLM and Embedding Providers in OpenMemory

feat(OMM): Add support for LLM and Embedding Providers in OpenMemory

---

docs/openmemory/overview.mdx
docs/openmemory/quickstart.mdx

Fixed Broken Links

---

docs/changelog.mdx
mem0-ts/package.json
mem0-ts/pnpm-lock.yaml
mem0-ts/src/client/mem0.ts
mem0-ts/src/oss/src/config/manager.ts
mem0-ts/src/oss/src/llms/openai.ts

Updates Google SDK Peer Dependency Version

deps(ts-sdk): Updates Google SDK Peer Dependency Version

---

pyproject.toml

version bump -> 0.1.103

---

docs/changelog.mdx
mem0-ts/package.json
mem0-ts/pnpm-lock.yaml
mem0-ts/src/oss/src/types/index.ts
mem0-ts/src/oss/src/vector_stores/vectorize.ts

Version Bump/Formatting

---

docs/components/llms/overview.mdx
docs/integrations/livekit.mdx

Update code and examples of Livekit to 1.0 version.

Livekit Docs Migration Update

---

docs/openmemory/overview.mdx
docs/openmemory/quickstart.mdx

Updated Docs for OMM Hosted Version

Updated Docs for OMM Hosted Version

---

mem0/memory/storage.py
pyproject.toml

Fix: Migration in storage and version bump -> -0.1.107

Fix: Migration in storage and version bump -> -0.1.107

---

pyproject.toml

deploy minor version -> 0.1.107rc2

---

Makefile

Update make install_all to specify pinecone < 7.0.0
Fixes # 2772

Fix/pin pinecone issue #2772

---

pyproject.toml

version bump -> 0.1.108

---

docs/changelog.mdx
vercel-ai-sdk/package.json
vercel-ai-sdk/pnpm-lock.yaml
vercel-ai-sdk/src/mem0-types.ts

Added Param `output_format` in AI SDK

Added Param `output_format` in AI SDK

---

examples/misc/diet_assistant_voice_cartesia.py

Memory-powered agent powered by Cartesia + Agno

Memory agent powered by voice (Cartesia + Agno)

---

mem0/memory/main.py
mem0/vector_stores/pinecone.py

Fix pinecone for async memory

---

Makefile
docs/components/vectordbs/dbs/baidu.mdx
docs/docs.json
mem0/configs/vector_stores/baidu.py
mem0/vector_stores/baidu.py
mem0/vector_stores/configs.py
pyproject.toml
tests/vector_stores/test_baidu.py

Integration of Baidu Vector Database (BaiduDB) as a vector store backend. This implementation provides a complete interface for vector operations including insert, search, update, and delete operations, with support for metadata filtering and similarity search.

Feature: baidu vector db integration

---

docs/quickstart.mdx

Fix example in quickstart page

Doc: Fix example in quickstart page

---

docs/changelog.mdx
mem0-ts/package.json
mem0-ts/src/client/mem0.ts
mem0-ts/src/client/telemetry.ts

Make V2 Add as Default

---

docs/docs.json
docs/openmemory/integrations.mdx
openmemory/.gitignore
openmemory/README.md
openmemory/ui/components/dashboard/Install.tsx

- Added Documentation for MCP Clients on the Readme and Documentation Page
- Fixed issue with the npm command for mcp client

Fix: Add MCP Client Integration Guide and update installation commands

---

pyproject.toml

version bump -> 0.1.111

---

docs/components/llms/overview.mdx
docs/core-concepts/memory-operations/delete.mdx
docs/core-concepts/memory-operations/update.mdx
docs/examples/llama-index-mem0.mdx
docs/integrations/llama-index.mdx
docs/open-source/python-quickstart.mdx
docs/openmemory/overview.mdx
docs/platform/features/advanced-retrieval.mdx
docs/platform/features/criteria-retrieval.mdx
docs/platform/features/platform-overview.mdx
docs/platform/overview.mdx
docs/quickstart.mdx
docs/what-is-mem0.mdx
mem0-ts/README.md

Link fixes

---

openmemory/ui/components/form-view.tsx

This PR fixes a critical configuration validation issue in the OpenMemory UI that was causing memory initialization failures. The root cause was inconsistent provider name formatting between the UI display and backend validation.
**Problem**: 
- The UI was sending provider names with spaces (e.g., "lm studio") while the backend expected lowercase names without spaces (e.g., "lmstudio")
- This caused the MCP service to fail initialization with `ERROR: Configuration validation error: Unsupported LLM provider: lm studio`
- Memory client became unavailable, forcing the server to run with limited functionality
**Solution**:
- Converted provider arrays to objects that map display labels to actual values
- Display labels maintain proper formatting with spaces (e.g., "LM Studio", "Azure OpenAI") …

fix(ui-backend): resolve provider name format inconsistency in form configuration

---

docs/openapi.json
docs/platform/quickstart.mdx

Add a example on how to use `async_mode` and update the API reference to show this param.

Doc: Add async_mode

---

mem0/configs/embeddings/base.py
pyproject.toml

Fix: Gemini embedder config and version bump -> 0.1.113

Fix: Gemini embedder config and version bump -> 0.1.113

---

.github/workflows/ci.yml

Fixes the issue of pip install packages in the CI pipeline.

Reverting the changes of pip install

---

docs/docs.json
docs/integrations/openai-agents-sdk.mdx

Adding OpenAI Agents SDK to integration docs.
By running `mint dev` locally.

Openai agents sdk added

---

docs/docs.json
docs/integrations/crewai.mdx
docs/integrations/google-ai-adk.mdx
docs/integrations/langchain.mdx
docs/integrations/openai-agents-sdk.mdx
examples/misc/test.py

Added docs for Google AI ADK
Ran `mint dev` locally

Google AI ADK Integration Docs

---

docs/changelog.mdx
docs/components/llms/models/gemini.mdx
mem0-ts/package.json
mem0-ts/src/oss/src/utils/factory.ts
mem0-ts/src/oss/src/utils/telemetry.ts

This PR adds **Gemini support** to the TypeScript SDK, providing users with an additional LLM provider option for their memory operations.
---
* **Added Gemini provider support**:
Extended the `LLMFactory` and `EmbedderFactory` to recognize `"gemini"` as a provider alias alongside the existing `"google"` provider for backward compatibility.
* **Updated documentation**:
Added comprehensive TypeScript usage examples to the Gemini documentation page, showing how to configure and use the Gemini provider.
* **Updated changelog**:
Added entry for v2.1.34 documenting the new Gemini support feature.
* **Version bump**:
Updated package version from `2.1.33` to `2.1.34`.
---
* Users can now use either `provider: "gemini"` or `provider: "google"` in their TypeScript configuration.
* The …

feat: Add Gemini support to TypeScript SDK

---

docs/integrations/vercel-ai-sdk.mdx
vercel-ai-sdk/package.json
vercel-ai-sdk/src/provider-response-provider.ts

This PR adds support for Google's Gemini model to the Vercel AI SDK provider integration. The implementation includes adding `"gemini"` as an alias for the existing `"google"` provider configuration, making it easier for users to integrate with Gemini models.
---
* Added `"gemini"` as a supported provider case in the provider response handler
* Updated documentation to include Gemini in the list of supported LLM providers
* Added a comprehensive provider table showing all supported providers and their configuration values
* Version bump from `1.0.6` to `1.0.7` to reflect the new feature
---
This enhancement improves the developer experience by providing a more intuitive way to configure Gemini models, as users can now specify either `"google"` or `"gemini"` as the provider name when …

Add Gemini Model Support to Vercel AI SDK Provider

---

docs/contributing/development.mdx
mem0/memory/main.py
mem0/vector_stores/pinecone.py
mem0/vector_stores/qdrant.py
mem0/vector_stores/weaviate.py

This PR implements several improvements to enhance the developer experience and code quality:
~~1. **pyproject.toml configuration**: Added "dev" dependency group to all Python version-specific environments (dev_py_*) for missing isort package.~~
2. **Improved developer documentation**: Better guide developers new to the Hatch build system, including comprehensive command references and development workflows
3. **Standardized logging**: Implemented consistent logging patterns across the codebase for better debugging and tracking capabilities
- Streamline onboarding for new developers
- Improve debugging capabilities through consistent logging
- Ensure development environment consistency across Python versions
- Maintain high code quality standards
No breaking changes are introduced, and …

Fixes: Mem0 Setup, Logging, Docs

---

mem0/llms/vllm.py

Resolve the VLLM call error
Fix the error that occurs when VLLM is called
When a VLLM model is used, an error message is reported when the VLLM model is started
~~~json
config = {
"version": "v1.1",
"provider": "milvus",
"config": {
"collection_name": "test",
"url": "http://10.110.1.13:19530",
"embedding_model_dims": 1024,
"token": "root:Milvus",  # 尝试使用 token 字段进行身份验证
},
},
"llm": {
"provider": "vllm",
"config": {
"model": "Qwen3-32b",
"temperature": 0.8,
"max_tokens": 35000,
"top_p": 0.5,
"vllm_base_url": "http://10.220.0.9:12345/v1/",
},
},
"embedder": {
"provider": "ollama",
"config": {
"model": "bge-m3:latest",
"ollama_base_url": "http://10.110.1.13:11434",
}, …

Fix the error that occurs when VLLM is called

---

mem0/llms/openai.py
mem0/memory/memgraph_memory.py

This PR Includes crucial changes for Memgraph Integration Working, Closes the following issue : 
https://github.com/mem0ai/mem0/pull/3044
https://github.com/mem0ai/mem0/pull/2879
https://github.com/mem0ai/mem0/issues/2806
https://github.com/mem0ai/mem0/issues/2714

Fix: Memgraph Graph Generation Issue

---

docs/_snippets/security-compliance.mdx

Security Link updated

---

docs/platform/features/memory-export.mdx

Added JavaScript code samples for creating and retrieving memory exports, including usage of export instructions and filters. Updated documentation to clarify retrieval by export ID and filters, and reorganized code groups for better clarity.

Add JavaScript examples for memory export API

---

docs/changelog.mdx
docs/docs.json
docs/examples/ai_companion.mdx
docs/examples/llama-index-mem0.mdx
docs/examples/multimodal-demo.mdx
docs/faqs.mdx
docs/features.mdx
docs/integrations/agno.mdx
docs/integrations/aws-bedrock.mdx
docs/integrations/aws_bedrock.mdx
docs/integrations/langchain.mdx
docs/integrations/llama-index.mdx

Added AWS Bedrock and OpenSearch to integration
Spelling fixes
Tested locally using `mint dev`

AWS Bedrock Integration and spell checks

---

docs/integrations/agno.mdx

Updated the Agno Integration docs with error fix and tool update
Tested the changes locally using `mint dev`.

Agno Mem0Tools update

---

docs/docs.json
docs/examples/memory-guided-content-writing.mdx

Rewrite the full example with proper logic, adding v2 search with filters and adding llm answer to match with the example expectation.
Tested using `mint dev` locally

Content Writing Example Rewrite

---

docs/docs.json
docs/examples.mdx
docs/examples/personalized-search-tavily-mem0.mdx

Created an example of personalized search using Mem0 + Tavily and now adding that to docs as an example.
By running `mint dev` locally, and checked if the page is working and functional.

Personalized Search Example Docs

---

server/docker-compose.yaml
server/requirements.txt

Updated missing requirements and added warm up for neo4j instance to become healthy
Fixes #3255 

Update docker compose

---

mem0/memory/graph_memory.py

Fix: refer to 61~62, self.config.graph_store.lm.config should be prioritized for usage

Fix: refer to 61~62, self.config.graph_store.lm.config should be prioritized for usage

---

.github/workflows/ci.yml
CONTRIBUTING.md
Makefile
pyproject.toml

Added support for python 3.12

---

docs/docs.json
docs/open-source/features/async-memory.mdx
docs/open-source/features/overview.mdx
docs/open-source/graph_memory/overview.mdx
docs/open-source/python-quickstart.mdx

Updated docs for agent_id and run_id

---

docs/changelog.mdx
docs/components/embedders/models/google_AI.mdx
docs/components/embedders/models/langchain.mdx
docs/components/embedders/models/ollama.mdx
docs/components/llms/models/langchain.mdx
docs/components/llms/models/ollama.mdx
docs/components/vectordbs/dbs/pgvector.mdx

Fixes inconsistency in the typescript docs

Fix typescript docs

---

docs/platform/advanced-memory-operations.mdx

docs: fix typo in docs/platform/advanced-memory-operations.mdx

---

vercel-ai-sdk/package.json
vercel-ai-sdk/src/mem0-generic-language-model.ts
vercel-ai-sdk/src/mem0-types.ts
vercel-ai-sdk/src/mem0-utils.ts

fix(Vercel AI SDK): Streaming not working properly

---

docs/openapi.json

Add version param in search v2 API documentation.

Add version param in search v2 API documentation

---

mem0/utils/factory.py

Add missing provider config for baidu vector store.

fix: add missing provider for baidu vector db

---

docs/examples/aws_example.mdx
docs/examples/aws_neptune_analytics_hybrid_store.mdx
docs/v0x/examples/aws_example.mdx
docs/v0x/examples/aws_neptune_analytics_hybrid_store.mdx

Refactored example title for aws

---

docs/changelog.mdx
docs/open-source/graph_memory/overview.mdx
pyproject.toml

Update version to 0.1.118

---

docs/api-reference.mdx
docs/api-reference/memory/add-memories.mdx
docs/api-reference/memory/v1-get-memories.mdx
docs/api-reference/memory/v1-search-memories.mdx
docs/api-reference/memory/v2-get-memories.mdx
docs/api-reference/memory/v2-search-memories.mdx
docs/docs.json
docs/examples.mdx
docs/examples/aws_example.mdx
docs/examples/aws_neptune_analytics_hybrid_store.mdx
docs/examples/personalized-search-tavily-mem0.mdx
docs/integrations/google-ai-adk.mdx
docs/introduction.mdx
docs/openapi.json
docs/v0x/examples/aws_example.mdx
docs/v0x/examples/aws_neptune_analytics_hybrid_store.mdx
docs/v0x/examples/personalized-search-tavily-mem0.mdx
docs/v0x/integrations/google-ai-adk.mdx

This pr refactors docs for better alignement and fixes get memories playground.

Refactor docs and fix get memories playground

---

mem0/llms/langchain.py
tests/llms/test_langchain.py

LangchainLLM now uses tools passed to `generate_response` and parses tool calls.

Tool call support for LangchainLLM
